### ISSUE TITLE
`flutter run debugger` tests very broken

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1184]
Seeing lots of strange failures on Travis and locally if running via `npm test`.

```
  flutter run debugger

[main 16:50:31] update#setState checking for updates

[main 16:50:31] update#setState idle

    1) "before all" hook: run 'flutter create'



  flutter test debugger

This socket has been ended by the other party
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer.ts:6:41)
    at Promise (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at new Promise (<anonymous>)
    at Analyzer.sendRequest (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:4:55)
    at Analyzer.editGetFixes (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer_gen.ts:280:4)
    at Promise (/Users/dantup/Dev/Dart-Code/out/src/providers/fix_code_action_provider.js:1:4687)
    at new Promise (<anonymous>)
    at FixCodeActionProvider.provideCodeActions (/Users/dantup/Dev/Dart-Code/out/src/providers/fix_code_action_provider.js:1:4597)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:883
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:323
    at new n.Class.derive._oncancel (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:776)
    at Object.t.asWinJsPromise (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:286)
    at e.provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:837)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:306
    at e._withAdapter (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:747:177)
    at e.$provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:268)
    at e._doInvokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
    at e._invokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
    at e._receiveRequest (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
    at e._receiveOneMessage (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
    at e.fire (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at a (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
    at Socket._socketDataListener (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

This socket has been ended by the other party
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer.ts:6:41)
    at Promise (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at new Promise (<anonymous>)
    at Analyzer.sendRequest (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:4:55)
    at Analyzer.editGetAssists (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer_gen.ts:275:71)
    at Promise (/Users/dantup/Dev/Dart-Code/out/src/providers/assist_code_action_provider.js:1:4263)
    at new Promise (<anonymous>)
    at AssistCodeActionProvider.provideCodeActions (/Users/dantup/Dev/Dart-Code/out/src/providers/assist_code_action_provider.js:1:4176)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:883
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:323
    at new n.Class.derive._oncancel (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:776)
    at Object.t.asWinJsPromise (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:286)
    at e.provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:837)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:306
    at e._withAdapter (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:747:177)
    at e.$provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:268)
    at e._doInvokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
    at e._invokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
    at e._receiveRequest (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
    at e._receiveOneMessage (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
    at e.fire (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at a (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
    at Socket._socketDataListener (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

rejected promise not handled within 1 second

    2) "before each" hook: activate flutterTestMainFile for "runs a Flutter test script to completion"



  test environment

    ✓ has opened the correct folder



  extension

    ✓ activated

        "dart": "/Users/dantup/Dev/Google/flutter/bin/cache/dart-sdk",
        "flutter": "/Users/dantup/Dev/Google/flutter",
        "projectType": 1

        "analysis_server": 0.0.0

    ✓ found the Dart and Flutter SDK

    ✓ used Flutter's version of the Dart SDK



  completion_item_provider

This socket has been ended by the other party
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer.ts:6:41)
    at Promise (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at new Promise (<anonymous>)
    at Analyzer.sendRequest (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:4:55)
    at Analyzer.editGetFixes (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer_gen.ts:280:4)
    at Promise (/Users/dantup/Dev/Dart-Code/out/src/providers/fix_code_action_provider.js:1:4687)
    at new Promise (<anonymous>)
    at FixCodeActionProvider.provideCodeActions (/Users/dantup/Dev/Dart-Code/out/src/providers/fix_code_action_provider.js:1:4597)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:883
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:323
    at new n.Class.derive._oncancel (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:776)
    at Object.t.asWinJsPromise (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:286)
    at e.provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:837)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:306
    at e._withAdapter (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:747:177)
    at e.$provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:268)
    at e._doInvokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
    at e._invokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
    at e._receiveRequest (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
    at e._receiveOneMessage (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
    at e.fire (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at a (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
    at Socket._socketDataListener (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

This socket has been ended by the other party
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer.ts:6:41)
    at Promise (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at new Promise (<anonymous>)
    at Analyzer.sendRequest (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:4:55)
    at Analyzer.editGetAssists (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer_gen.ts:275:71)
    at Promise (/Users/dantup/Dev/Dart-Code/out/src/providers/assist_code_action_provider.js:1:4263)
    at new Promise (<anonymous>)
    at AssistCodeActionProvider.provideCodeActions (/Users/dantup/Dev/Dart-Code/out/src/providers/assist_code_action_provider.js:1:4176)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:883
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:323
    at new n.Class.derive._oncancel (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:776)
    at Object.t.asWinJsPromise (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:286)
    at e.provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:837)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:306
    at e._withAdapter (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:747:177)
    at e.$provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:268)
    at e._doInvokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
    at e._invokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
    at e._receiveRequest (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
    at e._receiveOneMessage (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
    at e.fire (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at a (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
    at Socket._socketDataListener (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

rejected promise not handled within 1 second

    3) "before each" hook: activate flutterHelloWorldMainFile for "returns expected items"



  dart_document_symbol_provider

This socket has been ended by the other party
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer.ts:6:41)
    at Promise (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at new Promise (<anonymous>)
    at Analyzer.sendRequest (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:4:55)
    at Analyzer.editGetFixes (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer_gen.ts:280:4)
    at Promise (/Users/dantup/Dev/Dart-Code/out/src/providers/fix_code_action_provider.js:1:4687)
    at new Promise (<anonymous>)
    at FixCodeActionProvider.provideCodeActions (/Users/dantup/Dev/Dart-Code/out/src/providers/fix_code_action_provider.js:1:4597)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:883
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:323
    at new n.Class.derive._oncancel (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:776)
    at Object.t.asWinJsPromise (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:286)
    at e.provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:837)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:306
    at e._withAdapter (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:747:177)
    at e.$provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:268)
    at e._doInvokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
    at e._invokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
    at e._receiveRequest (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
    at e._receiveOneMessage (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
    at e.fire (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at a (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
    at Socket._socketDataListener (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

This socket has been ended by the other party
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:351:12)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at Analyzer.sendMessage (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer.ts:6:41)
    at Promise (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:6:87)
    at new Promise (<anonymous>)
    at Analyzer.sendRequest (/Users/dantup/Dev/Dart-Code/src/services/stdio_service.ts:4:55)
    at Analyzer.editGetAssists (/Users/dantup/Dev/Dart-Code/src/analysis/analyzer_gen.ts:275:71)
    at Promise (/Users/dantup/Dev/Dart-Code/out/src/providers/assist_code_action_provider.js:1:4263)
    at new Promise (<anonymous>)
    at AssistCodeActionProvider.provideCodeActions (/Users/dantup/Dev/Dart-Code/out/src/providers/assist_code_action_provider.js:1:4176)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:883
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:323
    at new n.Class.derive._oncancel (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:84:776)
    at Object.t.asWinJsPromise (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:110:286)
    at e.provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:736:837)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:306
    at e._withAdapter (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:747:177)
    at e.$provideCodeActions (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:751:268)
    at e._doInvokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
    at e._invokeHandler (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
    at e._receiveRequest (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
    at e._receiveOneMessage (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
    at /Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
    at e.fire (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at a (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
    at Socket._socketDataListener (/Users/dantup/Dev/Dart-Code/.vscode-test/stable/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

    4) "before each" hook: activate flutterHelloWorldMainFile for "returns expected items for 'flutter/hello_world'"



  fix_code_action_provider

rejected promise not handled within 1 second

rejected promise not handled within 1 second

Process is still going after 300s.
Waiting another 300s before terminating
    ["node_modules/vscode/bin/test"]
```

**Comment by DanTup** [comment]
All fixed :)
