### ISSUE TITLE
Dart extension always spend a lot of memory

### ISSUE THREAD

**Issue by tungvn** [Dart-Code/Dart-Code#1285]
I have a problem with Dart extension on VSCode. It always spends a lot of memory, until I force quit it.
Here is some information for debugs:

- OS: macOS High Sierra v10.13.6
- VS Code: version 1.18.2
- Dart and Flutter extension version: 2.20.0

Provide some images and log from VS Code
![screen shot 2018-11-04 at 16 24 06](https://user-images.githubusercontent.com/7405101/47962449-68cb6b00-e04f-11e8-8356-3ef292d5bfcb.png)
And it still increases until making my laptop lagged.

Logs:
```
Sun Nov 04 2018 [16:31:21 GMT+0700 (+07)] Log file started
[16:31:21 GMT+0700 (+07)] [General] [Info] Searching for SDKs...
[16:31:21 GMT+0700 (+07)] [General] [Info] Environment PATH:
[16:31:21 GMT+0700 (+07)] [General] [Info]     /Users/tungvn/.fastlane/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /usr/local/opt/imagemagick@6/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /usr/local/mongodb/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /usr/local/bin/yarn/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /usr/local/flutter/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /usr/local/mysql/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /usr/local/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /usr/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /usr/sbin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /sbin
[16:31:21 GMT+0700 (+07)] [General] [Info]     /opt/X11/bin
[16:31:21 GMT+0700 (+07)] [General] [Info] Found Flutter project at /Users/tungvn/Works/VietED/my_app
[16:31:21 GMT+0700 (+07)] [General] [Info] Searching for flutter
[16:31:21 GMT+0700 (+07)] [General] [Info]     Looking in:
[16:31:21 GMT+0700 (+07)] [General] [Info]         /Users/tungvn/Works/VietED/my_app/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/flutter/bin/
[16:31:21 GMT+0700 (+07)] [General] [Info]         /Users/tungvn/.fastlane/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/opt/imagemagick@6/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/mongodb/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/bin/yarn/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/flutter/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/mysql/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/sbin/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /sbin/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /opt/X11/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     Found at /usr/local/flutter/bin/
[16:31:21 GMT+0700 (+07)] [General] [Info]     Returning SDK path /usr/local/flutter for flutter
[16:31:21 GMT+0700 (+07)] [General] [Info] Searching for dart
[16:31:21 GMT+0700 (+07)] [General] [Info]     Looking in:
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/flutter/bin/cache/dart-sdk/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /Users/tungvn/.fastlane/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/opt/imagemagick@6/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/mongodb/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/bin/yarn/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/flutter/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/mysql/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/sbin/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /sbin/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /opt/X11/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]         /usr/local/flutter/bin/cache/dart-sdk/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     Found at /usr/local/flutter/bin/cache/dart-sdk/bin
[16:31:21 GMT+0700 (+07)] [General] [Info]     Returning SDK path /usr/local/flutter/bin/cache/dart-sdk for dart
[16:32:20 GMT+0700 (+07)] [General] [Error] This socket has been ended by the other party
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:351:12)
	at Analyzer.sendMessage (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/services/stdio_service.js:65:28)
	at Analyzer.sendMessage (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/analysis/analyzer.js:110:19)
	at Promise (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/services/stdio_service.js:60:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/services/stdio_service.js:49:16)
	at Analyzer.analysisGetHover (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/analysis/analyzer_gen.js:297:21)
	at Promise (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/providers/dart_hover_provider.js:14:27)
	at new Promise (<anonymous>)
	at DartHoverProvider.provideHover (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/providers/dart_hover_provider.js:13:16)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:500:127
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:368
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:85:776)
	at Object.t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:333)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:500:86)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:514:826
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js…
[16:32:20 GMT+0700 (+07)] [General] [Error] This socket has been ended by the other party
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:351:12)
	at Analyzer.sendMessage (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/services/stdio_service.js:65:28)
	at Analyzer.sendMessage (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/analysis/analyzer.js:110:19)
	at Promise (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/services/stdio_service.js:60:18)
	at new Promise (<anonymous>)
	at Analyzer.sendRequest (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/services/stdio_service.js:49:16)
	at Analyzer.analysisGetHover (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/analysis/analyzer_gen.js:297:21)
	at Promise (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/providers/dart_hover_provider.js:14:27)
	at new Promise (<anonymous>)
	at DartHoverProvider.provideHover (/Users/tungvn/.vscode/extensions/dart-code.dart-code-2.20.0/out/src/providers/dart_hover_provider.js:13:16)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:500:127
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:368
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:85:776)
	at Object.t.asThenable (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:108:333)
	at e.provideHover (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:500:86)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:514:826
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js…
```

**Comment by DanTup** [comment]
I think you may be hitting https://github.com/flutter/flutter/issues/23155. Which version of Flutter are you using? If it's the `beta` channel, could you try switching to the `dev` channel to see if the issue persists?

**Comment by tungvn** [comment]
I using Flutter beta v0.9.4.
This issue newly happened yesterday, after one day I upgrade my Dart extension. I still work with Flutter about 1 month ago and I haven't seen this issue.
I have just looked about the link and seem it no fixed.
I will try switching to the `dev` channel.

**Comment by tungvn** [comment]
Hmm, I think it is a bug of Flutter. When I try switching to the `dev` channel, it doesn't happen anymore.
I think we can close this issue now. Thanks for your supporting!

**Comment by DanTup** [comment]
> This issue newly happened yesterday, after one day I upgrade my Dart extension.

I suspect this was just coincidence - it might be that you only recently added code that triggered the issue (see https://github.com/dart-lang/sdk/issues/34850#issuecomment-431020274).

> When I try switching to the dev channel, it doesn't happen anymore.

Glad to hear - probably it is the issue linked above then. It's probably worth sticking on the dev channel until the next beta update then.

Do shout if you hit any other issues!

**Comment by larssn** [comment]
Can I hijack this thread? When using this plugin, VSCode helper grabs 1.8GB of RAM in a fairly small flutter project. I'm on a 4GB laptop, and this just completely boils my CPU because of all the IO swapping. Restarting VSCode makes it fast again... for a little while.

The plugin seems extremely aggressive in its analysis, where every keystroke immediately triggers some logic, which I suspects overwhelms my machine.

**Comment by DanTup** [comment]
@larssn it would be better to raise a new issue since it's probably not related to the issue above (unless you're on a very old version of Dart).

When the issue gets bad, please could you:

- Run `code --status` from the terminal, and include its output
- Run the **Dart: Capture Logs* command, press a few keys to capture the poor performance, then click **Stop Logging** and provide the log (note: be sure to review it for sensitive info, or email it to logs@dartcode.org if you don't want to attach publicly)

Thanks!

**Comment by humam-xr** [comment]
Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS Version:       Windows_NT x64 10.0.18362
CPUs:             Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)
Memory (System):  15.94GB (5.93GB free)
VM:               0%
Screen Reader:    no
Process Argv:
GPU Status:       2d_canvas:                     enabled
                  flash_3d:                      enabled
                  flash_stage3d:                 enabled
                  flash_stage3d_baseline:        enabled
                  gpu_compositing:               enabled
                  metal:                         disabled_off
                  multiple_raster_threads:       enabled_on
                  oop_rasterization:             disabled_off
                  protected_video_decode:        unavailable_off
                  rasterization:                 enabled
                  skia_renderer:                 disabled_off
                  surface_control:               disabled_off
                  surface_synchronization:       enabled_on
                  video_decode:                  enabled
                  viz_display_compositor:        enabled_on
                  viz_hit_test_surface_layer:    disabled_off
                  webgl:                         enabled
                  webgl2:                        enabled

CPU %   Mem MB     PID  Process
    0       76   20404  code main
    0       68    1796     shared-process
    0       94   11160     gpu-process
    1      173   11400     window (home.dart - glcpoints - Visual Studio Code)
    0      118    8832       extensionHost
    0        4    9268         C:\WINDOWS\system32\cmd.exe /d /s /c ""D:\flutter_sdk\bin\cache\dart-sdk\bin\dart.exe" "D:\flutter_sdk\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot" "--client-id=Dart-Code.dart-code" "--client-version=3.6.0""
    0       11   12440           console-window-host (Windows internal process)
    0      354   19712           "D:\flutter_sdk\bin\cache\dart-sdk\bin\dart.exe"  "D:\flutter_sdk\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot" "--client-id=Dart-Code.dart-code" "--client-version=3.6.0"
    0        4   18072         C:\WINDOWS\system32\cmd.exe /d /s /c ""D:\flutter_sdk\bin\flutter.bat" "daemon""
    0       11   19432           console-window-host (Windows internal process)
    0      237   20056           "D:\flutter_sdk\bin\cache\dart-sdk\bin\dart.exe"  --packages="D:\flutter_sdk\packages\flutter_tools\.packages"  "D:\flutter_sdk\bin\cache\flutter_tools.snapshot" "daemon"
    0        6   11884       console-window-host (Windows internal process)
    0       68   15772       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0        4    1268         C:\WINDOWS\system32\cmd.exe /c ""C:\Users\humam.alayad\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd" --status"
    0       34   20020           electron_node cli.js
    0       58   18708             "C:\Users\humam.alayad\AppData\Local\Programs\Microsoft VS Code\Code.exe" --status
    4       31   14380               gpu-process
    0       34   16396       searchService
    0       13   20612       watcherService
    0       11   19440         console-window-host (Windows internal process)
    0       14   21512     electron-crash-reporter

Workspace Stats:
|  Window (home.dart - glcpoints - Visual Studio Code)
|    Folder (glcpoints): 6417 files
|      File types: class(872) png(837) flat(547) xml(361) dex(290) dart(232)
|                  jar(216) json(191) java(137) svg(108)
|      Conf files:


I have the same error 
I use stable channel of flutter

**Comment by DanTup** [comment]
@humam-xr in the info you pasted there are two Dart processes - the Flutter daemon using 237MB and the analysis server using 354MB. Neither of these seem particularly high (possibly the daemon is a little higher than I'd expect for what it does, but the analysis server doesn't seem so bad for what it's doing).

Is this typical for what you see, or do you see it much higher?

**Comment by humam-xr** [comment]
Its typical but i think there is something related with memory because when I close adobe xd (1200 MB) free ram  about ((7 GB ) application run normally .
also I closed Vs code and restarted PC many times but always find many proccess of  : dart.exe - openJDk , Why ? 
![flutter error 2](https://user-images.githubusercontent.com/48356354/69343065-eb848f80-0c7d-11ea-9aa9-6ba1faf938cd.PNG)
![flutter error 3](https://user-images.githubusercontent.com/48356354/69343090-f63f2480-0c7d-11ea-80b0-545fb588f34f.PNG)

**Comment by DanTup** [comment]
>  I closed Vs code and restarted PC many times but always find many proccess of : dart.exe - openJDk , Why ?

The Android SDK uses Java, so when VS Code starts the Flutter daemon and it queries for devices, it will be running Java programs (like `adb`).

It's not clear from your message if you mean you see these processes after rebooting *without opening VS Code* though? If so, something seems wrong - you should only see these if you open VS Code and then open a Flutter project?

**Comment by humam-xr** [comment]
The processes still after closing Vs Code and can I know if it's normal  that processes repeated specially I'd just open one project ?

**Comment by DanTup** [comment]
The dart processes should not persist after closing VS Code, though the java ones could because both Gradle and ADB start daemons that will stay around for a while (they're reused by multiple instances of VS Code or across sessions for performance).

It's normal to have multiple Dart processes when editing a single project too, because there are multiple Dart applications in use (for example the analysis server, and the flutter device daemon, and if you're in a debug session, the flutter run daemon).

If you're seeing more than 3 Dart processes (or more than 2 when not in a debug session) or if they're persisting after you close VS Code, then that sounds like it could be a bug - if so, please open a new issue and include the a screenshot of the **Details** page of Task Manager with the **Command Line** column visible:

![commandline](https://user-images.githubusercontent.com/1078012/69367003-568a9200-0c8f-11ea-9c60-49dc663e2a7c.png)

Thanks!
