### ISSUE TITLE
Unknown Instance kind : Null

### ISSUE THREAD

**Issue by jsuryahyd** [Dart-Code/Dart-Code#1426]
**Bug** : true

**Source of bug**: I made an error in my code as `print(jsonDecode(updateResponse.body).error);` where `jsonDecode(updatedResponse.body)` gives a `bool` value, which doesnot have getter 'error'. Debugger pauses on 'libobject_patch.dart' file showing _Could not load source 'dart:core/runtime/libobject_patch.dart': <source not available>._ App doesn't crash though.

[Dart-Code-Log-2019-00-06 15-20-44.txt](https://github.com/Dart-Code/Dart-Code/files/2798848/Dart-Code-Log-2019-00-06.15-20-44.txt)

**the debug console output asks me to raise a bug(as follows):**
```
Unknown instance kind: Null. Please raise a bug against the Dart extension for VS Code.
D/        ( 5318): HostConnection::get() New Host Connection established 0xa1a7d900, tid 5338
D/EGL_emulation( 5318): eglMakeCurrent: 0xad956fa0: ver 2 0 (tinfo 0xab2a7d70)
E/flutter ( 5318): NoSuchMethodError: Class 'bool' has no instance getter 'error'.
E/flutter ( 5318): Receiver: true
E/flutter ( 5318): Tried calling: error
E/flutter ( 5318): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 5318): #1      _AppScopedModel&Model&ConnectedScopedModel&UserScopedModel&ProductsScopedModel.favouriteProduct 
E/flutter ( 5318): <asynchronous suspension>
E/flutter ( 5318): #2      ProductsListItem._builderFunc.<anonymous closure>.<anonymous closure> 
E/flutter ( 5318): #3      _InkResponseState._handleTap 
E/flutter ( 5318): #4      _InkResponseState.build.<anonymous closure> 
E/flutter ( 5318): #5      GestureRecognizer.invokeCallback 
E/flutter ( 5318): #6      TapGestureRecognizer._checkUp 
E/flutter ( 5318): #7      TapGestureRecognizer.acceptGesture 
E/flutter ( 5318): #8      GestureArenaManager.sweep 
E/flutter ( 5318): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
E/flutter ( 5318): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
E/flutter ( 5318): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
E/flutter ( 5318): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
E/flutter ( 5318): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
E/flutter ( 5318): #14     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 5318): #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
E/flutter ( 5318): #7      TapGestureRecognizer.acceptGesture 
E/flutter ( 5318): #8      GestureArenaManager.sweep 
E/flutter ( 5318): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
E/flutter ( 5318): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
E/flutter ( 5318): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
E/flutter ( 5318): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
E/flutter ( 5318): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
E/flutter ( 5318): #14     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 5318): #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
E/flutter ( 5318): NoSuchMethodError: Class 'bool' has no instance getter 'error'.
E/flutter ( 5318): Receiver: true
E/flutter ( 5318): Tried calling: error
E/flutter ( 5318): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 5318): #1      _AppScopedModel&Model&ConnectedScopedModel&UserScopedModel&ProductsScopedModel.favouriteProduct 
E/flutter ( 5318): <asynchronous suspension>
E/flutter ( 5318): #2      ProductsListItem._builderFunc.<anonymous closure>.<anonymous closure> 
E/flutter ( 5318): #3      _InkResponseState._handleTap 
E/flutter ( 5318): #4      _InkResponseState.build.<anonymous closure> 
E/flutter ( 5318): #5      GestureRecognizer.invokeCallback 
E/flutter ( 5318): #6      TapGestureRecognizer._checkUp 
E/flutter ( 5318): #7      TapGestureRecognizer.acceptGesture 
E/flutter ( 5318): #8      GestureArenaManager.sweep 
E/flutter ( 5318): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
E/flutter ( 5318): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
E/flutter ( 5318): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
E/flutter ( 5318): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
E/flutter ( 5318): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
E/flutter ( 5318): #14     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 5318): #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)

```

**Comment by DanTup** [comment]
Thanks for the reporting! I'll fix this for the next update. In the meantime, it's safe to ignore the warning (only that one line in the output is related to this issue). It basically means I haven't handled that type of object (Null) when populating the `Variables` pane on the left, so it's been skipped.

Thanks!

**Comment by DanTup** [comment]
Aha, figured it out. Triggering the evaluation from a hover works. Eg.:

```dart
void main() {
  String a;
  print("test");
}
```

Then just hover over `a`. Doesn't seem to work in the Locals list as the variables are build differently.
