### ISSUE TITLE
Bad state: Too many elements, after importing `json_annotation` package

### ISSUE THREAD

**Issue by pd4d10** [Dart-Code/Dart-Code#1601]
VSCode: 1.33.0
Dart Code: 2.25.0

Reproduce steps:

1. Create a empty directory, open it with VSCode
2. Create `pubspec.yaml`:
```yaml
name: test
version: 0.0.1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  json_annotation: ^2.1.0
```
3. Run `pub get` to fetch dependencies
4. Create `test.dart`:
```dart
import 'package:json_annotation/json_annotation.dart';

var test = 1;
```

Then the code analysis becomes broken. If we remove `json_annotation` import statement, it works correctly.

Error stack:

```
workbench.main.js:sourcemap:235 [Extension Host] Analysis failed: /tmp/test/test.dart context: exception_20190408_214346_576
t.log @ workbench.main.js:sourcemap:235
$logExtensionHostMessage @ workbench.main.js:sourcemap:3187
_doInvokeHandler @ workbench.main.js:sourcemap:3314
_invokeHandler @ workbench.main.js:sourcemap:3313
_receiveRequest @ workbench.main.js:sourcemap:3312
_receiveOneMessage @ workbench.main.js:sourcemap:3311
_protocol.onMessage.e @ workbench.main.js:sourcemap:3309
fire @ workbench.main.js:sourcemap:75
a @ workbench.main.js:sourcemap:317
e @ workbench.main.js:sourcemap:317
fire @ workbench.main.js:sourcemap:75
_receiveMessage @ workbench.main.js:sourcemap:326
_socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:sourcemap:323
fire @ workbench.main.js:sourcemap:75
acceptChunk @ workbench.main.js:sourcemap:320
_register._socket.onData.e @ workbench.main.js:sourcemap:319
t @ workbench.main.js:sourcemap:328
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:sourcemap:235 [Extension Host] Bad state: Too many elements
#0      List.single (dart:core/runtime/libgrowable_array.dart:227:5)
#1      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:293:18)
#2      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2526:29)
#3      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5286:36)
#4      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5136:7)
#5      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#6      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#7      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5562:47)
#8      TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5121:48)
#9      CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1640:16)
#10     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3810:12)
#11     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3516:15)
#12     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3456:7)
#13     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2217:13)
#14     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2183:24)
#16     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2236:18)
#17     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3489:42)
#18     Linker.link (package:analyzer/src/summary/link.dart:4012:35)
#19     _relink (package:analyzer/src/summary/link.dart:305:57)
#20     link (package:analyzer/src/summary/link.dart:123:3)
#21     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:170:25)
#22     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#23     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:169:12)
#24     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:67:5)
#25     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1612:29)
#26     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1426:30)
#27     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#28     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1416:20)
#29     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1216:17)
<asynchronous suspension>
#30     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2145:24)
<asynchronous suspension>
#31     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2075:5)
#32     new AnalysisServer (package:analysis_server/src/analysis_server.dart:213:29)
#33     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
#34     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
#35     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:526:21)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:605:12)
#41     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:524:7)
#42     Driver.start (package:analysis_server/src/server/driver.dart:427:7)
#43     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:12:11)
#44     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#45     main (file:///b/s/w/ir/cache/builder/sdk/pkg/analysis_server/bin/server.dart:10:10)
#46     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by DanTup** [comment]
Can you try removing your `~/.dartServer` folder? See https://github.com/dart-lang/sdk/issues/36380#issuecomment-478297299.

**Comment by DanTup** [comment]
Can you try removing your `~/.dartServer/.analysis-driver` folder? See https://github.com/dart-lang/sdk/issues/36380#issuecomment-478297299.

**Comment by pd4d10** [comment]
It works.. Thanks!

**Comment by DanTup** [comment]
Great! I think the underlying issue is fixed in a newer SDK, but this is a simpler workaround instead of waiting for that. If you see it again after the next stable SDK release, please do shout!
