### ISSUE TITLE
Syntax highlighter not working

### ISSUE THREAD

**Issue by julienrbrt** [Dart-Code/Dart-Code#1674]
Since the version ```2.26.1``` the syntax highlighting does not seems to work.
Downgrading to ```2.26.0``` fix it.

```{bash}
$ code --version
1.33.1
x64
```

**Comment by DanTup** [comment]
@julienrbrt Could you open the dev tools (Help -> Show Developer Tools) and see if there are any errors reported when this happens (such as failure to activate the extension)?

Does any other functionality of the extension work in this case?

How does it appear - is code all one colour and does it affect every dare file?

Thanks!

**Comment by julienrbrt** [comment]
Sure, here is the result, there is some errors indeed:

```
  ERR Unable to load and parse grammar for scope source.dart from file:///home/julien/.vscode/extensions/dart-code.dart-code-2.26.1/syntaxes/dart.json SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONGrammar (/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:1583)
    at parseRawGrammar (/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:1574)
    at t.<anonymous> (textMateService.ts:252)
    at Generator.next (<anonymous>)
    at r (errors.ts:184)
    at process._tickCallback (internal/process/next_tick.js:68)

  ERR No grammar provided for <source.dart: Error: No grammar provided for <source.dart
    at Registry.<anonymous> (/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:3583:39)
    at step (/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:3511:23)
    at Object.next (/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:3492:53)
    at fulfilled (/usr/share/code/resources/app/node_modules.asar/vscode-textmate/release/main.js:3483:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

  ERR Cannot read property 'comments' of undefined: TypeError: Cannot read property 'comments' of undefined
    at f._extractValidCommentRule (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4002:202)
    at f._handleConfig (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4005:546)
    at _fileService.resolveContent.then.s (file:///usr/share/code/resources/app/out/vs/workbench/workbench.main.js:4002:119)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Actually, now you mention it, no the extension is simply not working. No auto completion, documentation, todos, nothing seems to work and yet the code is simply plain text color (white only).

**Comment by julienrbrt** [comment]
/home/julien/.vscode/extensions/dart-code.dart-code-2.26.1/syntaxes/dart.json is empty.

I have uninstalled the Flutter and Dart extensions and reinstalled them without any change, downgrading to 2.26.0 still fix the problem.

**Comment by DanTup** [comment]
Yes, please open an issue there and cc me on it. I'll do some more testing here and add some comments. Thanks!

**Comment by DanTup** [comment]
Also - please try deleting the `/home/julien/.vscode/extensions/dart-code.dart-code-2.26.1` folder after uninstalling - looks like it doesn't get removed, so re-installing probably didn't re-download the extension.

**Comment by julienrbrt** [comment]
Alright. Simply deleting the folder and updating the extension fixed it. The extension was indeed probably corrupted.

Weird that VS Code do not check that.

Thank you.

**Comment by DanTup** [comment]
@julienrbrt great, thanks for confirming! It may be worth opening an issue with VS Code still, it does seem strange that it could silently fail to extract the extension. Sadly it's not something I can account for in the extension :(

Thanks!

**Comment by braysonjohn148** [comment]
> 
> 
> Also - please try deleting the `/home/julien/.vscode/extensions/dart-code.dart-code-2.26.1` folder after uninstalling - looks like it doesn't get removed, so re-installing probably didn't re-download the extension.

This one fixed the issue.. Thank you so much

**Comment by neezystudio** [comment]
thank you DanTup reinstalling and installing the extension worked for me too

**Comment by B4eva** [comment]
Uninstalling and installing the extensions worked for me as well .. thanks
