### ISSUE TITLE
VScode tries to update to the latest Dart forever

### ISSUE THREAD

**Issue by rowild** [Dart-Code/Dart-Code#1893]
Today VS Ccode tried to update to the latest version of Dart. But that didn't not seem to work, the SDK download lasted forever and never stopped.

In order to clean up and try again, I removed the flutter and dart extensions manually from the .vscode folder (Mac) and also cleared out any and all cache folders that VS Code has. Then I tried again to install the Futter and the Dart extensions. The extensions themselves were installed quickly, but then they try to download the SDK - and that fails.

This is the message:
```
Flutter Setup: Downloading Dart SDK from Flutter engine 
[hash]

Source: Dart (Extension)
```
Upon trying to start the Debugger, I get these messages:
```
The Flutter Daemon has terminated.

Source: Dart (Extension)
```

... and:
```
e.message.trimRight is not a function
```

Upon restarting, this appears:
```
The Dart Analyzer could not be started.
```

I cannot `pub` anything since the SDK is not installed...

What's wrong here? How can this be resolved?

Log
```

[7:29:09 AM] [General] [Info] Starting debug session...
[7:29:09 AM] [General] [Info]     workspace: /Volumes/_II_/_SITES/_TestsWithFlutter/navigation
[7:29:09 AM] [General] [Info] Using found common entry point: /Volumes/_II_/_SITES/_TestsWithFlutter/navigation/lib/main.dart
[7:29:09 AM] [General] [Info] Using workspace as cwd: /Volumes/_II_/_SITES/_TestsWithFlutter/navigation
[7:29:09 AM] [General] [Info] Detected launch project as Flutter
[7:29:09 AM] [General] [Info] Using Flutter debug adapter for this session
[7:30:39 AM] [General] [Info] Performing silent extension reload...
[7:30:39 AM] [General] [Info] Searching for SDKs...
[7:30:39 AM] [General] [Info] Environment PATH:
[7:30:39 AM] [General] [Info]     /Users/rowild/.pyenv/shims
[7:30:39 AM] [General] [Info]     /Users/rowild/.pyenv/bin
[7:30:39 AM] [General] [Info]     /Users/rowild/.nvm/versions/node/v11.10.0/bin
[7:30:39 AM] [General] [Info]     /Users/rowild/flutter/bin
[7:30:39 AM] [General] [Info]     /Users/rowild/.composer/vendor/bin
[7:30:39 AM] [General] [Info]     /usr/local/opt/mysql@5.7/bin
[7:30:39 AM] [General] [Info]     /usr/local/sbin
[7:30:39 AM] [General] [Info]     /usr/local/bin
[7:30:39 AM] [General] [Info]     /usr/bin
[7:30:39 AM] [General] [Info]     /bin
[7:30:39 AM] [General] [Info]     /usr/sbin
[7:30:39 AM] [General] [Info]     /sbin
[7:30:39 AM] [General] [Info]     /usr/local/share/dotnet
[7:30:39 AM] [General] [Info]     /opt/X11/bin
[7:30:39 AM] [General] [Info]     ~/.dotnet/tools
[7:30:39 AM] [General] [Info]     /Library/Frameworks/Mono.framework/Versions/Current/Commands
[7:30:39 AM] [General] [Info]     /Applications/Wireshark.app/Contents/MacOS
[7:30:39 AM] [General] [Info]     /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
[7:30:39 AM] [General] [Info]     /Applications/Visual Studio Code.app/Contents/Resources/app/bin
[7:30:39 AM] [General] [Info] Found Flutter project at /Volumes/_II_/_SITES/_TestsWithFlutter/navigation:
			Mobile? true
			Web? false
			Create Trigger? false
			Stagehand Trigger? false
			Flutter Repo? false
[7:30:39 AM] [General] [Info] Searching for flutter
[7:30:39 AM] [General] [Info]     Looking for flutter in:
[7:30:39 AM] [General] [Info]         /Volumes/_II_/_SITES/_TestsWithFlutter/navigation
[7:30:39 AM] [General] [Info]         /Volumes/_II_/_SITES/_TestsWithFlutter/navigation/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin/
[7:30:39 AM] [General] [Info]         /Users/rowild/.pyenv/shims
[7:30:39 AM] [General] [Info]         /Users/rowild/.pyenv/shims/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/.pyenv/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/.nvm/versions/node/v11.10.0/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/.composer/vendor/bin
[7:30:39 AM] [General] [Info]         /usr/local/opt/mysql@5.7/bin
[7:30:39 AM] [General] [Info]         /usr/local/sbin
[7:30:39 AM] [General] [Info]         /usr/local/bin
[7:30:39 AM] [General] [Info]         /usr/bin
[7:30:39 AM] [General] [Info]         /bin
[7:30:39 AM] [General] [Info]         /usr/sbin
[7:30:39 AM] [General] [Info]         /sbin
[7:30:39 AM] [General] [Info]         /usr/local/share/dotnet
[7:30:39 AM] [General] [Info]         /usr/local/share/dotnet/bin
[7:30:39 AM] [General] [Info]         /opt/X11/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/.dotnet/tools
[7:30:39 AM] [General] [Info]         /Users/rowild/.dotnet/tools/bin
[7:30:39 AM] [General] [Info]         /Library/Frameworks/Mono.framework/Versions/Current/Commands
[7:30:39 AM] [General] [Info]         /Library/Frameworks/Mono.framework/Versions/Current/Commands/bin
[7:30:39 AM] [General] [Info]         /Applications/Wireshark.app/Contents/MacOS
[7:30:39 AM] [General] [Info]         /Applications/Wireshark.app/Contents/MacOS/bin
[7:30:39 AM] [General] [Info]         /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
[7:30:39 AM] [General] [Info]         /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin/bin
[7:30:39 AM] [General] [Info]         /Applications/Visual Studio Code.app/Contents/Resources/app/bin
[7:30:39 AM] [General] [Info]     Found at:
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin/
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin
[7:30:39 AM] [General] [Info]     Candidate paths to be post-filtered:
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter
[7:30:39 AM] [General] [Info]     Found at /Users/rowild/flutter
[7:30:39 AM] [General] [Info]     Returning SDK path /Users/rowild/flutter for flutter
[7:30:39 AM] [General] [Info] Searching for dart
[7:30:39 AM] [General] [Info]     Looking for dart in:
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin/cache/dart-sdk
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin/cache/dart-sdk/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/.pyenv/shims
[7:30:39 AM] [General] [Info]         /Users/rowild/.pyenv/shims/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/.pyenv/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/.nvm/versions/node/v11.10.0/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/.composer/vendor/bin
[7:30:39 AM] [General] [Info]         /usr/local/opt/mysql@5.7/bin
[7:30:39 AM] [General] [Info]         /usr/local/sbin
[7:30:39 AM] [General] [Info]         /usr/local/bin
[7:30:39 AM] [General] [Info]         /usr/bin
[7:30:39 AM] [General] [Info]         /bin
[7:30:39 AM] [General] [Info]         /usr/sbin
[7:30:39 AM] [General] [Info]         /sbin
[7:30:39 AM] [General] [Info]         /usr/local/share/dotnet
[7:30:39 AM] [General] [Info]         /usr/local/share/dotnet/bin
[7:30:39 AM] [General] [Info]         /opt/X11/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/.dotnet/tools
[7:30:39 AM] [General] [Info]         /Users/rowild/.dotnet/tools/bin
[7:30:39 AM] [General] [Info]         /Library/Frameworks/Mono.framework/Versions/Current/Commands
[7:30:39 AM] [General] [Info]         /Library/Frameworks/Mono.framework/Versions/Current/Commands/bin
[7:30:39 AM] [General] [Info]         /Applications/Wireshark.app/Contents/MacOS
[7:30:39 AM] [General] [Info]         /Applications/Wireshark.app/Contents/MacOS/bin
[7:30:39 AM] [General] [Info]         /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin
[7:30:39 AM] [General] [Info]         /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin/bin
[7:30:39 AM] [General] [Info]         /Applications/Visual Studio Code.app/Contents/Resources/app/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin/cache/dart-sdk
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin/cache/dart-sdk/bin
[7:30:39 AM] [General] [Info]     Found at:
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin/cache/dart-sdk/bin
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin/cache/dart-sdk/bin
[7:30:39 AM] [General] [Info]     Candidate paths to be post-filtered:
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin/cache/dart-sdk
[7:30:39 AM] [General] [Info]         /Users/rowild/flutter/bin/cache/dart-sdk
[7:30:39 AM] [General] [Info]     Found at /Users/rowild/flutter/bin/cache/dart-sdk
[7:30:39 AM] [General] [Info]     Returning SDK path /Users/rowild/flutter/bin/cache/dart-sdk for dart
[7:30:39 AM] [General] [Info] Activating Flutter extension for Flutter project...
[7:30:39 AM] [General] [Info] Done!
[7:30:39 AM] [Analyzer] [Error] Unhandled exception:
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      FolderBasedDartSdk.getSdkProperty (package:analyzer/src/dart/sdk/sdk.dart:697:14)
#2      FolderBasedDartSdk.defaultSdkDirectory (package:analyzer/src/dart/sdk/sdk.dart:684:26)
#3      Driver._getSdkPath (package:analysis_server/src/server/driver.dart:758:33)
#4      Driver.start (package:analysis_server/src/server/driver.dart:394:28)
#5      main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[7:30:39 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:406:19)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at module.exports.t.Analyzer.sendMessage (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:31942)
	at module.exports.t.Analyzer.sendMessage (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:46482)
	at module.exports.t.StdIOService.sendRequest.Promise (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:31750)
	at new Promise (<anonymous>)
	at module.exports.t.Analyzer.sendRequest (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:31562)
	at module.exports.t.Analyzer.editGetFixes (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:280663)
	at module.exports.t.FixCodeActionProvider.<anonymous> (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:394396)
	at Generator.next (<anonymous>)
	at module.exports.r (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:393932)
	at new Promise (<anonymous>)
	at module.exports.r (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:393709)
	at module.exports.t.FixCodeActionProvider.provideCodeActions (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:394237)
	at module.exports.t.RankingCodeActionProvider.provideCodeActions.r.codeActionProviders.filter.map.r (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:399440)
	at Array.map (<anonymous>)
	at module.exports.t.RankingCodeActionProvider.<anonymous> (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:399431)
	at Generator.next (<anonymous>)
	at module.exports.r (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:398886)
	at new Promise (<anonymous>)
	at module.exports.r (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:398663)
	at module.exports.t.RankingCodeActionProvider.provideCodeActions (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:399322)
	at define.provideCodeActions.o.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:548:394)
	at t.asPromise.Promise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:53:995)
	at new Promise (<anonymous>)
	at Object.t.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:53:967)
	at S.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:548:365)
	at define.$provideCodeActions._withAdapter.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:564:695)
	at W._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:560:499)
	at W.$provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:564:673)
	at d._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:653:1006)
	at d._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:653:698)
	at d._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/exten…
[7:30:39 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:406:19)
	at writeOrBuffer (_stream_writable.js:394:5)
	at Socket.Writable.write (_stream_writable.js:294:11)
	at module.exports.t.Analyzer.sendMessage (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:31942)
	at module.exports.t.Analyzer.sendMessage (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:46482)
	at module.exports.t.StdIOService.sendRequest.Promise (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:31750)
	at new Promise (<anonymous>)
	at module.exports.t.Analyzer.sendRequest (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:31562)
	at module.exports.t.Analyzer.editGetAssists (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:280386)
	at module.exports.t.AssistCodeActionProvider.<anonymous> (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:367623)
	at Generator.next (<anonymous>)
	at module.exports.r (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:367164)
	at new Promise (<anonymous>)
	at module.exports.r (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:366941)
	at module.exports.t.AssistCodeActionProvider.provideCodeActions (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:367465)
	at module.exports.t.RankingCodeActionProvider.provideCodeActions.r.codeActionProviders.filter.map.r (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:399440)
	at Array.map (<anonymous>)
	at module.exports.t.RankingCodeActionProvider.<anonymous> (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:399431)
	at Generator.next (<anonymous>)
	at module.exports.r (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:398886)
	at new Promise (<anonymous>)
	at module.exports.r (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:398663)
	at module.exports.t.RankingCodeActionProvider.provideCodeActions (/Users/rowild/.vscode/extensions/dart-code.dart-code-3.2.1/out/dist/extension.js:1:399322)
	at define.provideCodeActions.o.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:548:394)
	at t.asPromise.Promise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:53:995)
	at new Promise (<anonymous>)
	at Object.t.asPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:53:967)
	at S.provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:548:365)
	at define.$provideCodeActions._withAdapter.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:564:695)
	at W._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:560:499)
	at W.$provideCodeActions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:564:673)
	at d._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:653:1006)
	at d._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:653:698)
	at d._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/servic…
[7:30:53 AM] [FlutterDaemon] [Error] find: invalid mode ‘+100’
[7:30:53 AM] [FlutterDaemon] [Error] 

```

**Comment by rowild** [comment]
This problem disappeared. I wish I knew why, but it seems it was one of those typical Windows "shortcuts": restart the computer and try again...

**Comment by DanTup** [comment]
Weird, seems like the Flutter SDK didn't get set up correctly. If you see this again, try grabbing a copy of your Flutter SDK folder when it's in the broken state before trying to fix, and we can see if we can figure out what might have happened. Thanks!

**Comment by rowild** [comment]
@DanTup  Will do!
