### ISSUE TITLE
DevTools

### ISSUE THREAD

**Issue by NexisHunter** [Dart-Code/Dart-Code#1945]
Unable to launch devtools when running flutter application, DevTools is listed as being part of the Dart VScode plugin so here I am. I've aliased google-chrome to point to google-chrome-stable but it still will not launch. I have appended the log output:

```
Failed to launch browser: ProcessException: No such file or directory
  Command: google-chrome http://127.0.0.1:45441/?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A36317%2Fm73ipqRnvPY%3D%2F
#0      Chrome._startProcess (package:browser_launcher/src/chrome.dart:128:12)
<asynchronous suspension>
#1      Chrome.start (package:browser_launcher/src/chrome.dart:120:11)
<asynchronous suspension>
#2      registerLaunchDevToolsService.<anonymous closure> (package:devtools_server/src/server.dart:238:24)
<asynchronous suspension>
#3      VmService._routeRequest (package:vm_service_lib/vm_service_lib.dart:1631:39)
<asynchronous suspension>
#4      VmService._processRequest (package:vm_service_lib/vm_service_lib.dart:1609:25)
<asynchronous suspension>
#5      VmService._processMessageStr (package:vm_service_lib/vm_service_lib.dart:1577:9)
#6      VmService._processMessage (package:vm_service_lib/vm_service_lib.dart:1535:7)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:375:20)
#11     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#12     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#17     _StreamController._add (dart:async/stream_controller.dart:640:7)
#18     _StreamController.add (dart:async/stream_controller.dart:586:5)
#19     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1141:21)
#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#25     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#26     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#28     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#31     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#32     _StreamController._add (dart:async/stream_controller.dart:640:7)
#33     _StreamController.add (dart:async/stream_controller.dart:586:5)
#34     _Socket._onData (dart:io-patch/socket_patch.dart:1791:41)
#35     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#39     _StreamController._add (dart:async/stream_controller.dart:640:7)
#40     _StreamController.add (dart:async/stream_controller.dart:586:5)
#41     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1339:33)
#42     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:860:14)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```
System Info:
Manjaro Linux 18.04
12 GB RAM
Quad Core @ 2.8GHZ AMD
VSCode 1.37.1-2
Plugin Version: Current As of August 24th 2019 1130PM UTC
Most Recent Version of Google Chrome Stable from AUR

**Comment by NexisHunter** [comment]
Currently syslinking it to google-chrome works but there should be a nice way around this

**Comment by DanTup** [comment]
> I've aliased google-chrome to point to google-chrome-stable 

Out of interest, why isn't it already called google-chrome? If by  aliasing you mean a bash alias, then I wouldn't expect that to work. Symlinks should work (as you found) though.

I'm not very familiar with this, but [this SO post](https://askubuntu.com/questions/675842/difference-between-google-chrome-stable-and-google-chrome-binaries) suggests one should be a symlink to the other anyway. Do you know why this isn't the case for you?

**Comment by NexisHunter** [comment]
So Manjaro doesn't have a default package for chrome, but it has access to the Arch User Repository since it is based on Arch and that package breaks chrome up but channel type, stable, dev, cannary etc. whereas ubuntu has a deb package from available that would set it up in the predicted fashion.

**Comment by DanTup** [comment]
Ah, got it. I think the most sensible thing is to add a symlink. It may  also be worth raising an issue at https://github.com/flutter/devtools to handle this better (it's DevTools that launches the browser).

In the next version (there's a [beta you can try here](https://github.com/Dart-Code/Dart-Code/releases/tag/v3.4.0-beta.2)) we'll fall back to the default browser if launching via DevTools fails, which will probably work for you - however it will also show a warning that it may be launching an unsupported browser.

**Comment by NexisHunter** [comment]
thanks
