### ISSUE TITLE
Goto definition doesn't work for some elements

### ISSUE THREAD

**Issue by escamoteur** [Dart-Code/Dart-Code#2026]
I have this file:

```Dart
import 'package:aartos/model/drones_db/drones_db.dart';
import 'package:jaguar_serializer/jaguar_serializer.dart';

part 'target_category.jser.dart';

class TargetCategory {
  final String type;
  final String name;
  @Field(processor: StringColorProcessor())
  final List<int> colors;
  String icon;
  String image;
  String iconFilePath;
  String imageFilePath;

  @Field(processor: const ShowModesProcessor())
  ShowModes showModes;

  TargetCategory(
      {this.type,
      this.name,
      this.colors,
      this.icon,
      this.image,
      this.showModes});

  void clearImageData() {
    icon = null;
    image = null;
  }

  int getColor(bool isFirstTargetInCategory) {
    if (colors == null || colors.isEmpty) {
      print(name);
      return 0xff000000;
    }
    if (isFirstTargetInCategory) {
      return colors[0] ?? 0xff000000;
    }
    return colors[1] ?? 0xff000000;
  }
}

@GenSerializer()
class TargetCategoryJsonSerializer extends Serializer<TargetCategory>
    with _$TargetCategoryJsonSerializer {}

class StringColorProcessor implements FieldProcessor<int, String> {
  const StringColorProcessor();

  @override
  int deserialize(String value) {
    if (value[0] == '#') // String value as it comes from the server
    {
      return int.parse('ff${value.substring(1, value.length)}', radix: 16);
    }
    // From stored appConfig
    return int.parse(value);
  }

  @override
  String serialize(int value) {
    var asString = value.toString();
    return asString;
  }
}
```

In this file Goto definition doesn't work at all. I tried on all elements, as well as on the import statement which normally opens the imported file.
Other files work

Analysy log
```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.4.1
Flutter extension: 3.4.1 (not activated)
VS Code: 1.38.1
Platform: win
Workspace type: Flutter
Multi-root?: true
Dart SDK:
    Loc: C:\Entwicklung\flutter\bin\cache\dart-sdk
    Ver: 2.6.0-edge.6ff8d2199da265e0aa2e3ca0b677956db3d42231
Flutter SDK:
    Loc: C:\Entwicklung\flutter
    Ver: 1.10.7-pre.78
HTTP_PROXY: undefined
NO_PROXY: undefined

Mon Sep 30 2019 [13:03:33 GMT+0200 (Mitteleuropäische Sommerzeit)] Log file started
[13:03:43] [Analyzer] [Info] ==> {"id":"264","method":"analysis.getHover","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":434},"clientRequestTime":1569841423442}
[13:03:43] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:43] [Analyzer] [Info] <== {"id":"264","result":{"hovers":[]}}
[13:03:43] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:43] [Analyzer] [Info] ==> {"id":"265","method":"edit.getFixes","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":435},"clientRequestTime":1569841423744}
[13:03:43] [Analyzer] [Info] ==> {"id":"266","method":"edit.getAssists","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":435},"clientRequestTime":1569841423744}
[13:03:43] [Analyzer] [Info] ==> {"id":"267","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":435},"clientRequestTime":1569841423744}
[13:03:43] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:43] [Analyzer] [Info] <== {"id":"265","result":{"fixes":[]}}
[13:03:43] [Analyzer] [Info] <== {"id":"266","result":{"assists":[]}}
[13:03:43] [Analyzer] [Info] <== {"id":"267","result":{"kinds":[]}}
[13:03:43] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:45] [Analyzer] [Info] ==> {"id":"268","method":"analysis.getNavigation","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":435},"clientRequestTime":1569841425099}
[13:03:45] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:45] [Analyzer] [Info] <== {"id":"268","result":{"files":[],"targets":[],"regions":[]}}
[13:03:45] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:47] [Analyzer] [Info] ==> {"id":"269","method":"analysis.getHover","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":435},"clientRequestTime":1569841427394}
[13:03:47] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:47] [Analyzer] [Info] <== {"id":"269","result":{"hovers":[]}}
[13:03:47] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:47] [Analyzer] [Info] ==> {"id":"270","method":"analysis.getHover","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":436},"clientRequestTime":1569841427710}
[13:03:47] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:47] [Analyzer] [Info] <== {"id":"270","result":{"hovers":[]}}
[13:03:47] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:48] [Analyzer] [Info] ==> {"id":"271","method":"analysis.getHover","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":412},"clientRequestTime":1569841428677}
[13:03:48] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:48] [Analyzer] [Info] <== {"id":"271","result":{"hovers":[]}}
[13:03:48] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:49] [Analyzer] [Info] ==> {"id":"272","method":"edit.getFixes","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":412},"clientRequestTime":1569841429135}
[13:03:49] [Analyzer] [Info] ==> {"id":"273","method":"edit.getAssists","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":412},"clientRequestTime":1569841429135}
[13:03:49] [Analyzer] [Info] ==> {"id":"274","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":412},"clientRequestTime":1569841429135}
[13:03:49] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:49] [Analyzer] [Info] <== {"id":"272","result":{"fixes":[]}}
[13:03:49] [Analyzer] [Info] <== {"id":"273","result":{"assists":[]}}
[13:03:49] [Analyzer] [Info] <== {"id":"274","result":{"kinds":[]}}
[13:03:49] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:50] [Analyzer] [Info] ==> {"id":"275","method":"analysis.getNavigation","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":412},"clientRequestTime":1569841430051}
[13:03:50] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:50] [Analyzer] [Info] <== {"id":"275","result":{"files":[],"targets":[],"regions":[]}}
[13:03:50] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:52] [Analyzer] [Info] ==> {"id":"276","method":"analysis.getHover","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":98},"clientRequestTime":1569841432513}
[13:03:52] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:52] [Analyzer] [Info] <== {"id":"276","result":{"hovers":[]}}
[13:03:52] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:52] [Analyzer] [Info] ==> {"id":"277","method":"analysis.getHover","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":41},"clientRequestTime":1569841432827}
[13:03:52] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:52] [Analyzer] [Info] <== {"id":"277","result":{"hovers":[]}}
[13:03:52] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:53] [Analyzer] [Info] ==> {"id":"278","method":"edit.getFixes","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":41},"clientRequestTime":1569841433394}
[13:03:53] [Analyzer] [Info] ==> {"id":"279","method":"edit.getAssists","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":41},"clientRequestTime":1569841433394}
[13:03:53] [Analyzer] [Info] ==> {"id":"280","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":41},"clientRequestTime":1569841433394}
[13:03:53] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:53] [Analyzer] [Info] <== {"id":"278","result":{"fixes":[]}}
[13:03:53] [Analyzer] [Info] <== {"id":"279","result":{"assists":[]}}
[13:03:53] [Analyzer] [Info] <== {"id":"280","result":{"kinds":[]}}
[13:03:53] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:54] [Analyzer] [Info] ==> {"id":"281","method":"analysis.getNavigation","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":41},"clientRequestTime":1569841434299}
[13:03:54] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:54] [Analyzer] [Info] <== {"id":"281","result":{"files":[],"targets":[],"regions":[]}}
[13:03:54] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:55] [Analyzer] [Info] ==> {"id":"282","method":"edit.getFixes","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":152},"clientRequestTime":1569841435744}
[13:03:55] [Analyzer] [Info] ==> {"id":"283","method":"edit.getAssists","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":152},"clientRequestTime":1569841435744}
[13:03:55] [Analyzer] [Info] ==> {"id":"284","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":152},"clientRequestTime":1569841435744}
[13:03:55] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:55] [Analyzer] [Info] <== {"id":"282","result":{"fixes":[]}}
[13:03:55] [Analyzer] [Info] <== {"id":"283","result":{"assists":[]}}
[13:03:55] [Analyzer] [Info] <== {"id":"284","result":{"kinds":[]}}
[13:03:55] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:56] [Analyzer] [Info] ==> {"id":"285","method":"analysis.getHover","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":105},"clientRequestTime":1569841436119}
[13:03:56] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:56] [Analyzer] [Info] <== {"id":"285","result":{"hovers":[]}}
[13:03:56] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:56] [Analyzer] [Info] ==> {"id":"286","method":"edit.getFixes","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":106},"clientRequestTime":1569841436673}
[13:03:56] [Analyzer] [Info] ==> {"id":"287","method":"edit.getAssists","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":106},"clientRequestTime":1569841436673}
[13:03:56] [Analyzer] [Info] ==> {"id":"288","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":106},"clientRequestTime":1569841436674}
[13:03:56] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:56] [Analyzer] [Info] <== {"id":"286","result":{"fixes":[]}}
[13:03:56] [Analyzer] [Info] <== {"id":"287","result":{"assists":[]}}
[13:03:56] [Analyzer] [Info] <== {"id":"288","result":{"kinds":[]}}
[13:03:56] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:57] [Analyzer] [Info] ==> {"id":"289","method":"analysis.getNavigation","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":106},"clientRequestTime":1569841437651}
[13:03:57] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:57] [Analyzer] [Info] <== {"id":"289","result":{"files":[],"targets":[],"regions":[]}}
[13:03:57] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[13:03:59] [Analyzer] [Info] ==> {"id":"290","method":"edit.getFixes","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","offset":351},"clientRequestTime":1569841439672}
[13:03:59] [Analyzer] [Info] ==> {"id":"291","method":"edit.getAssists","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":351},"clientRequestTime":1569841439672}
[13:03:59] [Analyzer] [Info] ==> {"id":"292","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos\\lib\\model\\drones_db\\target_category.dart","length":0,"offset":351},"clientRequestTime":1569841439672}
[13:03:59] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[13:03:59] [Analyzer] [Info] <== {"id":"290","result":{"fixes":[]}}
[13:03:59] [Analyzer] [Info] <== {"id":"291","result":{"assists":[]}}
[13:03:59] [Analyzer] [Info] <== {"id":"292","result":{"kinds":[]}}
[13:03:59] [Analyzer] [Info] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
Mon Sep 30 2019 [13:04:01 GMT+0200 (Mitteleuropäische Sommerzeit)] Log file ended
```

**Comment by escamoteur** [comment]
Don't know if tis related but the analyzer just crashed in t5he same file:

```

Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

(please describe what you were doing when this exception occurred)

### Versions

- Flutter SDK 1.10.7-pre.78
- Visual Studio Code 1.38.1
- Dart Code 3.4.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
C:\Entwicklung\flutter\bin\cache\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=3.4.1
--enable-completion-model
```

### Exception

Analysis failed: C:\Entwicklung\projects\Aaronia\trunk\Sources\RTSAMobileDev\aartos\lib\model\drones_db\target_category.dart

```text
NoSuchMethodError: The getter 'isBottom' was called on null.
Receiver: null
Tried calling: isBottom
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _isLegacyBottom (package:analyzer/src/generated/type_system.dart:63:13)
#2      GenericInferrer._matchSubtypeOf (package:analyzer/src/generated/type_system.dart:1797:9)
#3      GenericInferrer.tryMatchSubtypeOf (package:analyzer/src/generated/type_system.dart:1418:20)
#4      GenericInferrer.constrainArgument (package:analyzer/src/generated/type_system.dart:1245:5)
#5      Dart2TypeSystem.inferGenericFunctionOrType (package:analyzer/src/generated/type_system.dart:294:16)
#6      ElementResolver._resolveAnnotationConstructor (package:analyzer/src/generated/element_resolver.dart:1279:41)
#7      ElementResolver._resolveAnnotationElement (package:analyzer/src/generated/element_resolver.dart:1341:23)
#8      ElementResolver.visitSimpleIdentifier (package:analyzer/src/generated/element_resolver.dart:873:7)
#9      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8987:49)
#10     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4209:10)
#11     UnifyingAstVisitor.visitSimpleIdentifier (package:analyzer/dart/ast/visitor.dart:3410:53)
#12     ResolverVisitor.visitSimpleIdentifier (package:analyzer/src/generated/resolver.dart:4356:11)
#13     SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8987:49)
#14     ResolverVisitor.visitAnnotation (package:analyzer/src/generated/resolver.dart:3243:16)
#15     AnnotationImpl.accept (package:analyzer/src/dart/ast/ast.dart:285:49)
#16     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#17     AnnotatedNodeImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:153:17)
#18     FieldDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4099:11)
#19     ResolverVisitor.visitNode (package:analyzer/src/generated/resolver.dart:4208:10)
#20     UnifyingAstVisitor.visitFieldDeclaration (package:analyzer/dart/ast/visitor.dart:3226:53)
#21     PartialResolverVisitor.visitFieldDeclaration (package:analyzer/src/generated/resolver.dart:2886:11)
#22     FieldDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:4095:49)
#23     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7682:20)
#24     ScopedVisitor.visitClassMembersInScope (package:analyzer/src/generated/resolver.dart:5186:18)
#25     ScopedVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:5164:11)
#26     ResolverVisitor.visitClassDeclaration (package:analyzer/src/generated/resolver.dart:3486:13)
#27     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1554:49)
#28     ResolverVisitor.visitCompilationUnit (package:analyzer/src/generated/resolver.dart:3528:23)
#29     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2140:49)
#30     LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:673:10)
#31     LibraryAnalyzer.analyzeSync.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:160:7)
#32     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#33     LibraryAnalyzer.analyzeSync (package:analyzer/src/dart/analysis/library_analyzer.dart:159:11)
#34     LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:117:14)
#35     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#36     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:116:43)
#37     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1260:63)
#38     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
#39     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1235:20)
#40     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1045:17)
#41     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#42     _rootRunUnary (dart:async/zone.dart:1132:38)
#43     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#44     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#45     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#46     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#47     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#51     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#54     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#55     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\packages\\rtsa_map\\example\\rtsa_map_test",
        "explicitFileCount": 1,
        "implicitFileCount": 777,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\packages\\rtsa_map",
        "explicitFileCount": 21,
        "implicitFileCount": 756,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    },
    {
        "name": "C:\\Entwicklung\\projects\\Aaronia\\trunk\\Sources\\RTSAMobileDev\\aartos",
        "explicitFileCount": 59,
        "implicitFileCount": 2188,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by escamoteur** [comment]
Ok, its a regression on the latest master. I switched to dev and it works

**Comment by DanTup** [comment]
There's an open SDK issue that looks like this, so closing in favour of that:

https://github.com/dart-lang/sdk/issues/38744
