### ISSUE TITLE
Remove the need for specific ports by default for ChromeOS

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2098]
This issue has been fixed. Once it's in stable ChromeOS, there's no need for us to use specific ports by default (which can result in binding errors if they're taken):

https://bugs.chromium.org/p/chromium/issues/detail?id=848063

**Comment by maks** [comment]
@DanTup sorry took me a while to get around to testing this.
So using Flutter (Channel beta, 2.5.0-5.2.pre, on Debian GNU/Linux 10 (buster) and VSCode 1.59.1 and DartCode 3.25.1, if I have in `~/.config/Code/User/settings.json`:
```
"dart.useKnownChromeOSPorts": false,
```
and then I launch app into the ChromeOS Android container runtime (where ChromeOS normally runs Android apps) and then click on the "magnify glass" icon in the debug toolbar to bring up Flutter Devtools, Devtools launches **just fine** in the normal ChromeOS browser window **but** I do also see a error in VSCode bottom right:

![Screenshot 2021-08-30 16 26 18](https://user-images.githubusercontent.com/71999/131295455-dc88084c-0a59-4e2c-ab7d-17b3c6e984c1.png)

and clicking on it I see this full error:
```
Failed to launch browser: ProcessException: No such file or directory
  Command: google-chrome
http://127.0.0.1:9100/#?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A34593%2FIFrZGQwamzM%3D%2F&page=inspector
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      Chrome._startProcess (package:browser_launcher/src/chrome.dart:145:26)
#3      Chrome.start (package:browser_launcher/src/chrome.dart:137:18)
#4      launchDevTools (package:devtools_server/src/server.dart:953:31)
<asynchronous suspension>
#5      registerLaunchDevToolsService.<anonymous closure>
(package:devtools_server/src/server.dart:845:9)
<asynchronous suspension>
#6      VmService._routeRequest (package:vm_service/src/vm_service.dart:2242:14)
<asynchronous suspension>
#7      VmService._processRequest
(package:vm_service/src/vm_service.dart:2212:19)
<asynchronous suspension>
```

Future clicks on the debug toolbar to bring up Devtools shows me the usual system notification about reusing existing devtools (once I allow Devtools to "show notifications" permission, as per usual when using Chrome on other OS's too).

**Comment by DanTup** [comment]
@maks thanks for testing! I suspect you'll also see that warning without the setting, and it's not affecting anything here. By default we still try to use Chrome to launch DevTools, and that's done in a way that tries to find Chrome on your system (and for ChromeOS, you'd need the Linux version of Chrome installed for that).

It's fine to ignore this warning - it will likely be removed sometime in the near future (as I'd like to just always use the default browser for DevTools once https://github.com/flutter/devtools/issues/2856 is resolved).

In that case, I'll remove this setting and tidy up a little for the next version. Thanks!

**Comment by DanTup** [comment]
Rather than just dropping this immediately, I'm going to change the default for `dart.useKnownChromeOSPorts` to `false` (#3577) for the next release then remove in the subsequent release.
