### ISSUE TITLE
The Dart Analyzer has terminated. 

### ISSUE THREAD

**Issue by yuezhilunhui2009** [Dart-Code/Dart-Code#2122]
![](https://user-images.githubusercontent.com/49218931/65828770-192e0780-e2d1-11e9-9cd4-dad7d8a9998d.png)

```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.6.0
Flutter extension: 3.6.0 (activated)
VS Code: 1.40.1
Platform: mac
HTTP_PROXY: undefined
NO_PROXY: undefined

Thu Nov 21 2019 [02:01:14 GMT+0800 (China Standard Time)] Log file started
[2:01:14 AM] [General] [Info] Searching for SDKs...
[2:01:14 AM] [General] [Info] Environment PATH:
[2:01:14 AM] [General] [Info]     /Users/cc/.rvm/gems/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]     /Users/cc/.rvm/gems/ruby-2.6.3@global/bin
[2:01:14 AM] [General] [Info]     /Users/cc/.rvm/rubies/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]     /usr/local/bin
[2:01:14 AM] [General] [Info]     /usr/bin
[2:01:14 AM] [General] [Info]     /bin
[2:01:14 AM] [General] [Info]     /usr/sbin
[2:01:14 AM] [General] [Info]     /sbin
[2:01:14 AM] [General] [Info]     /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]     /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]     /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]     /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]     /Users/cc/Library/Android/sdk
[2:01:14 AM] [General] [Info]     /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info]     /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]     /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]     /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]     /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]     /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info] Done!
[2:01:14 AM] [General] [Info] Found Flutter project at /Users/cc/github/nautilus/example:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[2:01:14 AM] [General] [Info] Searching for flutter
[2:01:14 AM] [General] [Info]     Looking for flutter in:
[2:01:14 AM] [General] [Info]         /Users/cc/github/nautilus/example
[2:01:14 AM] [General] [Info]         /Users/cc/github/nautilus/example/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/gems/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/gems/ruby-2.6.3@global/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/rubies/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]         /usr/local/bin
[2:01:14 AM] [General] [Info]         /usr/bin
[2:01:14 AM] [General] [Info]         /bin
[2:01:14 AM] [General] [Info]         /usr/sbin
[2:01:14 AM] [General] [Info]         /sbin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info]     Found at:
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]     Candidate paths to be post-filtered:
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]     Found at /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]     Returning SDK path /Users/cc/Downloads/flutter for flutter
[2:01:14 AM] [General] [Info] Searching for dart
[2:01:14 AM] [General] [Info]     Looking for dart in:
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/gems/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/gems/ruby-2.6.3@global/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/rubies/ruby-2.6.3/bin
[2:01:14 AM] [General] [Info]         /usr/local/bin
[2:01:14 AM] [General] [Info]         /usr/bin
[2:01:14 AM] [General] [Info]         /bin
[2:01:14 AM] [General] [Info]         /usr/sbin
[2:01:14 AM] [General] [Info]         /sbin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/platform-tools/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Library/Android/sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/.rvm/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]     Found at:
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk/bin
[2:01:14 AM] [General] [Info]     Candidate paths to be post-filtered:
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]         /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]     Found at /Users/cc/Downloads/flutter/bin/cache/dart-sdk
[2:01:14 AM] [General] [Info]     Returning SDK path /Users/cc/Downloads/flutter/bin/cache/dart-sdk for dart
[2:01:14 AM] [General] [Info] Activating Flutter extension for Flutter project...
[2:01:14 AM] [General] [Info] Extension:Startup timing: 32ms
[2:01:14 AM] [General] [Info] Analyzer:Startup timing: 396ms
[2:01:15 AM] [General] [Info] Checking 1 projects for supported platforms
[2:01:15 AM] [General] [Info] Supported platforms for the workspace are ios, android
[2:01:17 AM] [Analyzer] [Error] Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.
[2:01:18 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at l.sendMessage (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43601)
	at l.sendMessage (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:38875)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43409
	at new Promise (<anonymous>)
	at l.sendRequest (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43221)
	at l.analysisSetSubscriptions (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:283639)
	at g.<anonymous> (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:32675)
	at Generator.next (<anonymous>)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:31221
	at new Promise (<anonymous>)
	at r (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:30966)
	at g.updateSubscriptions (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:32528)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:31525
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:207)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:545:768
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:207)
	at p.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/ser…
[2:01:18 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at l.sendMessage (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43601)
	at l.sendMessage (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:38875)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43409
	at new Promise (<anonymous>)
	at l.sendRequest (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:43221)
	at l.editGetFixes (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:285177)
	at t.FixCodeActionProvider.<anonymous> (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:428072)
	at Generator.next (<anonymous>)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:427606
	at new Promise (<anonymous>)
	at r (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:427351)
	at t.FixCodeActionProvider.provideCodeActions (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:427912)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:433211
	at Array.map (<anonymous>)
	at t.RankingCodeActionProvider.<anonymous> (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:433202)
	at Generator.next (<anonymous>)
	at /Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:432651
	at new Promise (<anonymous>)
	at r (/Users/cc/.vscode/extensions/dart-code.dart-code-3.6.0/out/dist/extension.js:1:432396)
	at t.RankingCodeActionProvider.provideCodeActions (/Users/cc/.vscode/exte…
```

```
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/cc/Downloads/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/cc/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version openjdk version "1.8.0_202-release"
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version openjdk version "1.8.0_202-release"

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available
```

**Comment by DanTup** [comment]
The error here is 

> Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.

This has come up before and was related to a corrupt Dart SDK inside Flutter. How did you install Flutter? Are you using a zip file, or from Git?

If a zip file, could you try re-extracting it to see if that makes a difference? Or if you're using from Git (and can connect to GitHub) you could try the instructions at https://github.com/flutter/flutter/issues/36257#issuecomment-514114690 for clearing the cache and letting Flutter re-download the Dart SDK.

**Comment by yuezhilunhui2009** [comment]
I have tried to delete flutter/bin/cache folder and reinstall it, but the problem still exist.

But I found only a specific flutter project should cause the problem, how can I check if there is a problem with this project?

**Comment by yuezhilunhui2009** [comment]
When I delete the IOS directory, this error no longer appears.

So I deleted the whole flutter project and downloaded it from GitHub again. There was no error.

**Comment by DanTup** [comment]
Glad it's sorted - though I'm not sure why the `ios` folder would have any impact on the analyzer. If you see this again, please keep a copy of your `ios` folder so we can do some more investigation! I think there was previously a bug in the analysis server if there were symlinks inside some of the folders (possible `ios`), though I thought they were resolved.

**Comment by povpros** [comment]
Failed to remove build. A program may still be using a file in the directory or the directory itself. To find and stop such a program, 
see: https://superuser.com/questions/1333118/cant-delete-empty-folder-because-it-is-used
