### ISSUE TITLE
Creating a new project failed.(error message: Operation not permitted.)

### ISSUE THREAD

**Issue by shhhplus** [Dart-Code/Dart-Code#2200]
mac osx. vscode output message:

```console
[myapp1] flutter create --ios-language swift --android-language kotlin .
bash: /Users/un/Documents/development/flutter/bin/flutter: Operation not permitted
exit code 126
```

**Comment by DanTup** [comment]
Does this happen if you just run `flutter create my_test_app` from a terminal?

**Comment by shhhplus** [comment]
> Does this happen if you just run `flutter create my_test_app` from a terminal?

View -> Command Palette -> Flutter: New Project

**Comment by shhhplus** [comment]
In vscode, all operations on flutter failed. such as:
1.As main.dart opened: The Dart Analyzer could not be started. 
2.As No Device Clicked: The Flutter Daemon has terminated. 
3.As View -> Command Palette -> Flutter: Run Flutter Doctor

error log: 
`Error: EPERM: operation not permitted, open '/Users/un/Documents/development/flutter/bin/cache/dart-sdk/version'`
`Error: EPERM: operation not permitted, open '/Users/un/Documents/development/flutter/version'`
`bash: /Users/un/Documents/development/flutter/bin/flutter: Operation not permitted`

**Comment by DanTup** [comment]
> Does this happen if you just run flutter create my_test_app from a terminal?

Sorry, I meant - can you try this and see if it also occurs there, or if it *only* occurs from within VS Code?

**Comment by shhhplus** [comment]
> > Does this happen if you just run flutter create my_test_app from a terminal?
> 
> Sorry, I meant - can you try this and see if it also occurs there, or if it _only_ occurs from within VS Code?

Sorry. It only occurs from within VS Code.

**Comment by DanTup** [comment]
What about if you try it from the built-in terminal in VS Code?

Also, could you try:

- Run **Dart: Capture Logs** in VS Code (leave everything ticked)
- Run **Flutter: Run Flutter Doctor** command in VS Code
- Click **Cancel** on the logging notification to get a log file

Then paste the log here. Thanks!

**Comment by shhhplus** [comment]
> What about if you try it from the built-in terminal in VS Code?
> 
> Also, could you try:
> 
> * Run **Dart: Capture Logs** in VS Code (leave everything ticked)
> * Run **Flutter: Run Flutter Doctor** command in VS Code
> * Click **Cancel** on the logging notification to get a log file
> 
> Then paste the log here. Thanks!

[flutter] flutter doctor -v
bash: /Users/un/Documents/development/flutter/bin/flutter: Operation not permitted
exit code 126

**Comment by DanTup** [comment]
@shhhplus that doesn't seem like the right log - when you click **Cancel** on the logging notification after it finishes running, it should open a full log file in the editor that contains a lot more info.

**Comment by shhhplus** [comment]
@DanTup 


![WechatIMG3](https://user-images.githubusercontent.com/1873172/71977220-315bde00-3253-11ea-863d-19e75a0eee70.jpeg)

**Comment by shhhplus** [comment]
![111](https://user-images.githubusercontent.com/1873172/71978296-e55e6880-3255-11ea-9d32-7cd1f6fa4fd6.jpeg)

**Comment by shhhplus** [comment]
Another error. The Dart Analyzer could not be started. 

<img width="229" alt="222" src="https://user-images.githubusercontent.com/1873172/71979600-142a0e00-3259-11ea-9b2f-e4d9428f1bbc.png">

`!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (not activated)
VS Code: 1.41.1
Platform: mac
HTTP_PROXY: undefined
NO_PROXY: undefined

Wed Jan 08 2020 [20:55:15 GMT+0800 (China Standard Time)] Log file started
[8:55:15 PM] [General] [Info] Searching for SDKs...
[8:55:15 PM] [General] [Info] Environment PATH:
[8:55:15 PM] [General] [Info]     /usr/local/bin
[8:55:15 PM] [General] [Info]     /usr/bin
[8:55:15 PM] [General] [Info]     /bin
[8:55:15 PM] [General] [Info]     /usr/sbin
[8:55:15 PM] [General] [Info]     /sbin
[8:55:15 PM] [General] [Info]     /Applications/VMware Fusion.app/Contents/Public
[8:55:15 PM] [General] [Info]     /usr/local/go/bin
[8:55:15 PM] [General] [Info]     /Users/un/Documents/development/flutter/bin
[8:55:15 PM] [General] [Info] Found Flutter project at /Users/un/Documents/project/practice/flutter/app1:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[8:55:15 PM] [General] [Info] Searching for flutter
[8:55:15 PM] [General] [Info]     Looking for flutter in:
[8:55:15 PM] [General] [Info]         /Users/un/Documents/project/practice/flutter/app1
[8:55:15 PM] [General] [Info]         /Users/un/Documents/project/practice/flutter/app1/bin
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin/
[8:55:15 PM] [General] [Info]         /Users/un/Documents/project/practice/flutter/app1/.flutter
[8:55:15 PM] [General] [Info]         /Users/un/Documents/project/practice/flutter/app1/.flutter/bin
[8:55:15 PM] [General] [Info]         /Users/un/Documents/project/practice/flutter/app1/vendor/flutter
[8:55:15 PM] [General] [Info]         /Users/un/Documents/project/practice/flutter/app1/vendor/flutter/bin
[8:55:15 PM] [General] [Info]         /usr/local/bin
[8:55:15 PM] [General] [Info]         /usr/bin
[8:55:15 PM] [General] [Info]         /bin
[8:55:15 PM] [General] [Info]         /usr/sbin
[8:55:15 PM] [General] [Info]         /sbin
[8:55:15 PM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public
[8:55:15 PM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public/bin
[8:55:15 PM] [General] [Info]         /usr/local/go/bin
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin
[8:55:15 PM] [General] [Info]     Found at:
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin/
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin
[8:55:15 PM] [General] [Info]     Candidate paths to be post-filtered:
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter
[8:55:15 PM] [General] [Info]     Found at /Users/un/Documents/development/flutter
[8:55:15 PM] [General] [Info]     Returning SDK path /Users/un/Documents/development/flutter for flutter
[8:55:15 PM] [General] [Info] Searching for dart
[8:55:15 PM] [General] [Info]     Looking for dart in:
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin/cache/dart-sdk
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin/cache/dart-sdk/bin
[8:55:15 PM] [General] [Info]         /usr/local/bin
[8:55:15 PM] [General] [Info]         /usr/bin
[8:55:15 PM] [General] [Info]         /bin
[8:55:15 PM] [General] [Info]         /usr/sbin
[8:55:15 PM] [General] [Info]         /sbin
[8:55:15 PM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public
[8:55:15 PM] [General] [Info]         /Applications/VMware Fusion.app/Contents/Public/bin
[8:55:15 PM] [General] [Info]         /usr/local/go/bin
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin/cache/dart-sdk
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin/cache/dart-sdk/bin
[8:55:15 PM] [General] [Info]     Found at:
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin/cache/dart-sdk/bin
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin/cache/dart-sdk/bin
[8:55:15 PM] [General] [Info]     Candidate paths to be post-filtered:
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin/cache/dart-sdk
[8:55:15 PM] [General] [Info]         /Users/un/Documents/development/flutter/bin/cache/dart-sdk
[8:55:15 PM] [General] [Info]     Found at /Users/un/Documents/development/flutter/bin/cache/dart-sdk
[8:55:15 PM] [General] [Info]     Returning SDK path /Users/un/Documents/development/flutter/bin/cache/dart-sdk for dart
[8:55:15 PM] [General] [Error] EPERM: operation not permitted, open '/Users/un/Documents/development/flutter/bin/cache/dart-sdk/version'
Error: EPERM: operation not permitted, open '/Users/un/Documents/development/flutter/bin/cache/dart-sdk/version'
	at Object.openSync (fs.js:447:3)
	at Object.func (electron/js2c/asar.js:138:31)
	at Object.func [as openSync] (electron/js2c/asar.js:138:31)
	at Object.readFileSync (fs.js:349:35)
	at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
	at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
	at Object.t.getSdkVersion (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:13019)
	at t.SdkUtils.<anonymous> (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:84027)
	at Generator.next (<anonymous>)
	at o (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:78080)
[8:55:15 PM] [General] [Error] EPERM: operation not permitted, open '/Users/un/Documents/development/flutter/version'
Error: EPERM: operation not permitted, open '/Users/un/Documents/development/flutter/version'
	at Object.openSync (fs.js:447:3)
	at Object.func (electron/js2c/asar.js:138:31)
	at Object.func [as openSync] (electron/js2c/asar.js:138:31)
	at Object.readFileSync (fs.js:349:35)
	at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
	at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
	at Object.t.getSdkVersion (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:13019)
	at t.SdkUtils.<anonymous> (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:84083)
	at Generator.next (<anonymous>)
	at o (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:78080)
[8:55:15 PM] [General] [Error] EPERM: operation not permitted, open '/Users/un/Documents/development/flutter/bin/cache/dart-sdk/version'
Error: EPERM: operation not permitted, open '/Users/un/Documents/development/flutter/bin/cache/dart-sdk/version'
	at Object.openSync (fs.js:447:3)
	at Object.func (electron/js2c/asar.js:138:31)
	at Object.func [as openSync] (electron/js2c/asar.js:138:31)
	at Object.readFileSync (fs.js:349:35)
	at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
	at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
	at Object.t.getSdkVersion (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:13019)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:64672
	at Object.t.addToLogHeader (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:43586)
	at Xe (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:64607)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:67493
	at Generator.next (<anonymous>)
	at o (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:62192)
[8:55:15 PM] [General] [Error] EPERM: operation not permitted, open '/Users/un/Documents/development/flutter/version'
Error: EPERM: operation not permitted, open '/Users/un/Documents/development/flutter/version'
	at Object.openSync (fs.js:447:3)
	at Object.func (electron/js2c/asar.js:138:31)
	at Object.func [as openSync] (electron/js2c/asar.js:138:31)
	at Object.readFileSync (fs.js:349:35)
	at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
	at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
	at Object.t.getSdkVersion (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:13019)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:64774
	at Object.t.addToLogHeader (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:43586)
	at Xe (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:64703)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:67493
	at Generator.next (<anonymous>)
	at o (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:62192)
[8:55:15 PM] [General] [Info] Activating Flutter extension for Flutter project...
[8:55:15 PM] [General] [Info] Extension:Startup timing: 128ms
[8:55:15 PM] [FlutterDaemon] [Error] shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Operation not permitted
bash: /Users/un/Documents/development/flutter/bin/flutter: Operation not permitted
[8:55:16 PM] [Analyzer] [Error] Error: Error when reading 'Users/un/Documents/development/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot': Operation not permitted
[8:55:16 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:45556)
	at m.sendMessage (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:39197)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:45176)
	at m.editGetFixes (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:290549)
	at t.FixCodeActionProvider.<anonymous> (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:436166)
	at Generator.next (<anonymous>)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:435700
	at new Promise (<anonymous>)
	at r (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:435445)
	at t.FixCodeActionProvider.provideCodeActions (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:436006)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:441239
	at Array.map (<anonymous>)
	at t.RankingCodeActionProvider.<anonymous> (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:441230)
	at Generator.next (<anonymous>)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:440679
	at new Promise (<anonymous>)
	at r (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:440424)
	at t.RankingCodeActionProvider.provideCodeActions (/Use…
[8:55:16 PM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at m.sendMessage (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:45556)
	at m.sendMessage (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:39197)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:45364
	at new Promise (<anonymous>)
	at m.sendRequest (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:45176)
	at m.editGetAssists (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:290272)
	at t.AssistCodeActionProvider.<anonymous> (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:397337)
	at Generator.next (<anonymous>)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:396876
	at new Promise (<anonymous>)
	at r (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:396621)
	at t.AssistCodeActionProvider.provideCodeActions (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:397178)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:441239
	at Array.map (<anonymous>)
	at t.RankingCodeActionProvider.<anonymous> (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:441230)
	at Generator.next (<anonymous>)
	at /Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:440679
	at new Promise (<anonymous>)
	at r (/Users/un/.vscode/extensions/dart-code.dart-code-3.7.1/out/dist/extension.js:1:440424)
	at t.RankingCodeActionProvider.provideCodeActio…
`

**Comment by shhhplus** [comment]
@DanTup 
This issue has been resolved. [Fix Terminal “Operation not permitted” Error in MacOS.](http://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/)

**Comment by DanTup** [comment]
@shhhplus glad to hear, thanks for the info!
