### ISSUE TITLE
VScode The Dart Analyzer could not be started , I did not download a flatter

### ISSUE THREAD

**Issue by ZekDaniels** [Dart-Code/Dart-Code#2249]
```
[18:41:22] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\bin
[18:41:22] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\
[18:41:22] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\bin
[18:41:22] [General] [Info]         D:\Dart\dart-sdk\bin
[18:41:22] [General] [Info]         C:\Users\lenovo\AppData\Local\atom\bin
[18:41:22] [General] [Info]         D:\Microsoft VS Code\bin
[18:41:22] [General] [Info]     Found at:
[18:41:22] [General] [Info]     Candidate paths to be post-filtered:
[18:41:22] [General] [Info]     Returning SDK path undefined for flutter.bat
[18:41:22] [General] [Info] Searching for dart.exe
[18:41:22] [General] [Info]     Looking for dart.exe in:
[18:41:22] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[18:41:22] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\bin
[18:41:22] [General] [Info]         C:\Program Files (x86)\Common Files\Oracle\Java\javapath
[18:41:22] [General] [Info]         C:\Program Files (x86)\Common Files\Oracle\Java\javapath\bin
[18:41:22] [General] [Info]         C:\Windows\system32
[18:41:22] [General] [Info]         C:\Windows\system32\bin
[18:41:22] [General] [Info]         C:\Windows
[18:41:22] [General] [Info]         C:\Windows\bin
[18:41:22] [General] [Info]         C:\Windows\System32\Wbem
[18:41:22] [General] [Info]         C:\Windows\System32\Wbem\bin
[18:41:22] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[18:41:22] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[18:41:22] [General] [Info]         C:\Program Files\dotnet\
[18:41:22] [General] [Info]         C:\Program Files\dotnet\bin
[18:41:22] [General] [Info]         C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
[18:41:22] [General] [Info]         C:\Program Files\Microsoft SQL Server\130\Tools\Binn\bin
[18:41:22] [General] [Info]         C:\Opencv 3.4.1\opencv\build\x64\vc14\bin
[18:41:22] [General] [Info]         C:\Opencv 3.2\opencv\build\x64\vc14\bin
[18:41:22] [General] [Info]         D:\xampp\tmp
[18:41:22] [General] [Info]         D:\xampp\tmp\bin
[18:41:22] [General] [Info]         C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
[18:41:22] [General] [Info]         C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\bin
[18:41:22] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\
[18:41:22] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\bin
[18:41:22] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
[18:41:22] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\Tools\Binn\bin
[18:41:22] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\DTS\Binn\
[18:41:22] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\DTS\Binn\bin
[18:41:22] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\
[18:41:22] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\bin
[18:41:22] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\
[18:41:22] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\bin
[18:41:22] [General] [Info]         D:\Dart\dart-sdk\bin
[18:41:22] [General] [Info]         C:\Users\lenovo\AppData\Local\atom\bin
[18:41:22] [General] [Info]         D:\Microsoft VS Code\bin
[18:41:22] [General] [Info]     Found at:
[18:41:22] [General] [Info]         D:\Dart\dart-sdk\bin
[18:41:22] [General] [Info]     Candidate paths to be post-filtered:
[18:41:22] [General] [Info]         D:\Dart\dart-sdk
[18:41:22] [General] [Info]     Found at D:\Dart\dart-sdk
[18:41:22] [General] [Info]     Returning SDK path D:\Dart\dart-sdk for dart.exe
[18:41:22] [Analyzer] [Info] Spawning D:\Dart\dart-sdk\bin\dart.exe with args ["D:\\Dart\\dart-sdk\\bin\\snapshots\\analysis_server.dart.snapshot","--client-id=Dart-Code.dart-code","--client-version=3.8.1"]
[18:41:22] [Analyzer] [Info]     PID: 5816
[18:41:22] [Analyzer] [Info] ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1581003682933}
[18:41:22] [Analyzer] [Info] ==> {"id":"2","method":"analysis.setPriorityFiles","params":{"files":["D:\\Mobil\\Dart dersleri\\main.dart"]},"clientRequestTime":1581003682935}
[18:41:22] [Analyzer] [Info] ==> {"id":"3","method":"analysis.setSubscriptions","params":{"subscriptions":{"FOLDING":["D:\\Mobil\\Dart dersleri\\main.dart"],"OCCURRENCES":["D:\\Mobil\\Dart dersleri\\main.dart"],"OUTLINE":["D:\\Mobil\\Dart dersleri\\main.dart"]}},"clientRequestTime":1581003682936}
[18:41:22] [Analyzer] [Info] ==> {"id":"4","method":"analysis.updateContent","params":{"files":{"D:\\Mobil\\Dart dersleri\\main.dart":{"content":"main(List<String> args) {\r\n  print(\"merhaba dünya\");\r\n}","type":"add"}}},"clientRequestTime":1581003682950}
[18:41:22] [General] [Info] Extension:Startup timing: 1240ms
[18:41:22] [General] [Info] Found 0 folders requiring "pub get":
[18:41:23] [Analyzer] [Info] <== Komut istemi, y�neticiniz taraf�ndan devre d��� b�rak�lm��.
[18:41:23] [Analyzer] [Info] Process terminated! 255, null
[18:41:23] [Analyzer] [Info] ==> {"id":"5","method":"edit.getFixes","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","offset":55},"clientRequestTime":1581003683098}
[18:41:23] [Analyzer] [Info] ==> {"id":"6","method":"edit.getAssists","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","length":0,"offset":55},"clientRequestTime":1581003683104}
[18:41:23] [Analyzer] [Info] ==> {"id":"7","method":"edit.getAvailableRefactorings","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","length":0,"offset":55},"clientRequestTime":1581003683107}
[18:41:23] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\Users…
[18:41:23] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\Users…
[18:41:24] [General] [Info] Performing silent extension reload...
[18:41:24] [General] [Info] Searching for SDKs...
[18:41:24] [General] [Info] Environment PATH:
[18:41:24] [General] [Info]     C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[18:41:24] [General] [Info]     C:\Program Files (x86)\Common Files\Oracle\Java\javapath
[18:41:24] [General] [Info]     C:\Windows\system32
[18:41:24] [General] [Info]     C:\Windows
[18:41:24] [General] [Info]     C:\Windows\System32\Wbem
[18:41:24] [General] [Info]     C:\Windows\System32\WindowsPowerShell\v1.0\
[18:41:24] [General] [Info]     C:\Program Files\dotnet\
[18:41:24] [General] [Info]     C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
[18:41:24] [General] [Info]     C:\Opencv 3.4.1\opencv\build\x64\vc14\bin
[18:41:24] [General] [Info]     C:\Opencv 3.2\opencv\build\x64\vc14\bin
[18:41:24] [General] [Info]     D:\xampp\tmp
[18:41:24] [General] [Info]     C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
[18:41:24] [General] [Info]     C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\
[18:41:24] [General] [Info]     C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
[18:41:24] [General] [Info]     C:\Program Files\Microsoft SQL Server\120\DTS\Binn\
[18:41:24] [General] [Info]     C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\
[18:41:24] [General] [Info]     C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\
[18:41:24] [General] [Info]     D:\Dart\dart-sdk\bin
[18:41:24] [General] [Info]     C:\Users\lenovo\AppData\Local\atom\bin
[18:41:24] [General] [Info]     D:\Microsoft VS Code\bin
[18:41:24] [General] [Info] Done!
[18:41:24] [General] [Info] Searching for flutter.bat
[18:41:24] [General] [Info]     Looking for flutter.bat in:
[18:41:24] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[18:41:24] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\bin
[18:41:24] [General] [Info]         C:\Program Files (x86)\Common Files\Oracle\Java\javapath
[18:41:24] [General] [Info]         C:\Program Files (x86)\Common Files\Oracle\Java\javapath\bin
[18:41:24] [General] [Info]         C:\Windows\system32
[18:41:24] [General] [Info]         C:\Windows\system32\bin
[18:41:24] [General] [Info]         C:\Windows
[18:41:24] [General] [Info]         C:\Windows\bin
[18:41:24] [General] [Info]         C:\Windows\System32\Wbem
[18:41:24] [General] [Info]         C:\Windows\System32\Wbem\bin
[18:41:24] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[18:41:24] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[18:41:24] [General] [Info]         C:\Program Files\dotnet\
[18:41:24] [General] [Info]         C:\Program Files\dotnet\bin
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\130\Tools\Binn\bin
[18:41:24] [General] [Info]         C:\Opencv 3.4.1\opencv\build\x64\vc14\bin
[18:41:24] [General] [Info]         C:\Opencv 3.2\opencv\build\x64\vc14\bin
[18:41:24] [General] [Info]         D:\xampp\tmp
[18:41:24] [General] [Info]         D:\xampp\tmp\bin
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\bin
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\bin
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\Tools\Binn\bin
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\DTS\Binn\
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\DTS\Binn\bin
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\bin
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\bin
[18:41:24] [General] [Info]         D:\Dart\dart-sdk\bin
[18:41:24] [General] [Info]         C:\Users\lenovo\AppData\Local\atom\bin
[18:41:24] [General] [Info]         D:\Microsoft VS Code\bin
[18:41:24] [General] [Info]     Found at:
[18:41:24] [General] [Info]     Candidate paths to be post-filtered:
[18:41:24] [General] [Info]     Returning SDK path undefined for flutter.bat
[18:41:24] [General] [Info] Searching for dart.exe
[18:41:24] [General] [Info]     Looking for dart.exe in:
[18:41:24] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
[18:41:24] [General] [Info]         C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\bin
[18:41:24] [General] [Info]         C:\Program Files (x86)\Common Files\Oracle\Java\javapath
[18:41:24] [General] [Info]         C:\Program Files (x86)\Common Files\Oracle\Java\javapath\bin
[18:41:24] [General] [Info]         C:\Windows\system32
[18:41:24] [General] [Info]         C:\Windows\system32\bin
[18:41:24] [General] [Info]         C:\Windows
[18:41:24] [General] [Info]         C:\Windows\bin
[18:41:24] [General] [Info]         C:\Windows\System32\Wbem
[18:41:24] [General] [Info]         C:\Windows\System32\Wbem\bin
[18:41:24] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\
[18:41:24] [General] [Info]         C:\Windows\System32\WindowsPowerShell\v1.0\bin
[18:41:24] [General] [Info]         C:\Program Files\dotnet\
[18:41:24] [General] [Info]         C:\Program Files\dotnet\bin
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\130\Tools\Binn\bin
[18:41:24] [General] [Info]         C:\Opencv 3.4.1\opencv\build\x64\vc14\bin
[18:41:24] [General] [Info]         C:\Opencv 3.2\opencv\build\x64\vc14\bin
[18:41:24] [General] [Info]         D:\xampp\tmp
[18:41:24] [General] [Info]         D:\xampp\tmp\bin
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\bin
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\bin
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\Tools\Binn\bin
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\DTS\Binn\
[18:41:24] [General] [Info]         C:\Program Files\Microsoft SQL Server\120\DTS\Binn\bin
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\bin
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\
[18:41:24] [General] [Info]         C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\bin
[18:41:24] [General] [Info]         D:\Dart\dart-sdk\bin
[18:41:24] [General] [Info]         C:\Users\lenovo\AppData\Local\atom\bin
[18:41:24] [General] [Info]         D:\Microsoft VS Code\bin
[18:41:24] [General] [Info]     Found at:
[18:41:25] [General] [Info]         D:\Dart\dart-sdk\bin
[18:41:25] [General] [Info]     Candidate paths to be post-filtered:
[18:41:25] [General] [Info]         D:\Dart\dart-sdk
[18:41:25] [General] [Info]     Found at D:\Dart\dart-sdk
[18:41:25] [General] [Info]     Returning SDK path D:\Dart\dart-sdk for dart.exe
[18:41:25] [Analyzer] [Info] Spawning D:\Dart\dart-sdk\bin\dart.exe with args ["D:\\Dart\\dart-sdk\\bin\\snapshots\\analysis_server.dart.snapshot","--client-id=Dart-Code.dart-code","--client-version=3.8.1"]
[18:41:25] [Analyzer] [Info]     PID: 5816
[18:41:25] [Analyzer] [Info] ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1581003685008}
[18:41:25] [Analyzer] [Info] ==> {"id":"2","method":"analysis.setPriorityFiles","params":{"files":["D:\\Mobil\\Dart dersleri\\main.dart"]},"clientRequestTime":1581003685009}
[18:41:25] [Analyzer] [Info] ==> {"id":"3","method":"analysis.setSubscriptions","params":{"subscriptions":{"FOLDING":["D:\\Mobil\\Dart dersleri\\main.dart"],"OCCURRENCES":["D:\\Mobil\\Dart dersleri\\main.dart"],"OUTLINE":["D:\\Mobil\\Dart dersleri\\main.dart"]}},"clientRequestTime":1581003685009}
[18:41:25] [Analyzer] [Info] ==> {"id":"4","method":"analysis.updateContent","params":{"files":{"D:\\Mobil\\Dart dersleri\\main.dart":{"content":"main(List<String> args) {\r\n  print(\"merhaba dünya\");\r\n}","type":"add"}}},"clientRequestTime":1581003685018}
[18:41:25] [General] [Info] Extension:Startup timing: 47ms
[18:41:25] [Analyzer] [Info] <== Komut istemi, y�neticiniz taraf�ndan devre d��� b�rak�lm��.
[18:41:25] [Analyzer] [Info] Process terminated! 255, null
[18:41:25] [Analyzer] [Info] ==> {"id":"5","method":"edit.getFixes","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","offset":55},"clientRequestTime":1581003685109}
[18:41:25] [Analyzer] [Info] ==> {"id":"6","method":"edit.getAssists","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","length":0,"offset":55},"clientRequestTime":1581003685113}
[18:41:25] [Analyzer] [Info] ==> {"id":"7","method":"edit.getAvailableRefactorings","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","length":0,"offset":55},"clientRequestTime":1581003685116}
[18:41:25] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\Users…
[18:41:25] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\Users…
[18:44:07] [Analyzer] [Info] ==> {"id":"8","method":"analysis.setPriorityFiles","params":{"files":[]},"clientRequestTime":1581003847686}
[18:44:07] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\Users…
[18:46:42] [Analyzer] [Info] ==> {"id":"9","method":"edit.getFixes","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","offset":0},"clientRequestTime":1581004002842}
[18:46:42] [Analyzer] [Info] ==> {"id":"10","method":"edit.getAssists","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","length":0,"offset":0},"clientRequestTime":1581004002847}
[18:46:42] [Analyzer] [Info] ==> {"id":"11","method":"edit.getAvailableRefactorings","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","length":0,"offset":0},"clientRequestTime":1581004002851}
[18:46:42] [Analyzer] [Info] ==> {"id":"12","method":"analysis.setPriorityFiles","params":{"files":["D:\\Mobil\\Dart dersleri\\main.dart"]},"clientRequestTime":1581004002856}
[18:46:42] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\Users…
[18:46:42] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\Users…
[18:46:42] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:413:19)
	at writeOrBuffer (_stream_writable.js:401:5)
	at Socket.Writable.write (_stream_writable.js:301:11)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\lenovo\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\Users…
[18:46:43] [Analyzer] [Info] ==> {"id":"13","method":"edit.getFixes","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","offset":55},"clientRequestTime":1581004003039}
[18:46:43] [Analyzer] [Info] ==> {"id":"14","method":"edit.getAssists","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","length":0,"offset":55},"clientRequestTime":1581004003042}
[18:46:43] [Analyzer] [Info] ==> {"id":"15","method":"edit.getAvailableRefactorings","params":{"file":"D:\\Mobil\\Dart dersleri\\main.dart","length":0,"offset":55},"clientRequestTime":1581004003045}
```

**Comment by DanTup** [comment]
In the log I see this:

> Komut istemi, y�neticiniz taraf�ndan devre d��� b�rak�lm��.

Pasting this into Google Translate gives this:

> The command prompt has been disabled by your administrator.

So it seems like the command prompt is disabled on your machine (possibly [via the registry, or Group Policy](https://answers.microsoft.com/en-us/windows/forum/windows_xp-update/my-command-prompt-has-been-disabled-by/4585aff2-bdbb-4990-b976-5f272b58851c?auth=1)). In order to spawn some of the Flutter/Dart processes, we need to use the command prompt (shell) because some of them are [batch files](https://en.wikipedia.org/wiki/Batch_file) that can only be executed in a shell.

**Comment by DanTup** [comment]
Closing this as it doesn't seem like a VS Code extension issue, but some restrictions set up at the OS level. Please shout if you think that's not the case and continue to have issues though!
