### ISSUE TITLE
I faced this strange error while auto indenting my code. I attached a comment "Erroneous line" to the line which gave rise to it.

### ISSUE THREAD

**Issue by Akash98Sky** [Dart-Code/Dart-Code#2267]
### Request

Server was responding to request: `edit.format`

### Versions

- Visual Studio Code - Insiders v1.43.0-insider
- Dart Code v3.8.1
- Flutter SDK v1.14.6

### Analyzer Info

The analyzer was launched using the arguments:

- /home/akash/MobileSDK/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
- --client-id=Dart-Code.dart-code
- --client-version=3.8.1

### Exception

The formatter produced unexpected output. Input was:
```
part of 'tmdb-service.dart';

abstract class ConfigurationService {
  final String _configUrl = "https://api.themoviedb.org/3/configuration";

  Configuration _configuration;

  Configuration get configuration => _configuration;

  void set configuration(Configuration configuration) :
    assert(configuration != null), _configuration = configuration;     // Erroneous line

  Future<Configuration> _initConfiguration(String apiKey) async {
    Response response = await get("$_configUrl?api_key=$apiKey");
    Map<String, dynamic> map = json.decode(response.body);
    _configuration = Configuration.fromJson(map);

    return _configuration;
  }
}
```

Which formatted to:
```
part of 'tmdb-service.dart';

abstract class ConfigurationService {
  final String _configUrl = "https://api.themoviedb.org/3/configuration";

  Configuration _configuration;

  Configuration get configuration => _configuration;

  void set configuration(Configuration configuration);         // Erroneous line

  Future<Configuration> _initConfiguration(String apiKey) async {
    Response response = await get("$_configUrl?api_key=$apiKey");
    Map<String, dynamic> map = json.decode(response.body);
    _configuration = Configuration.fromJson(map);

    return _configuration;
  }
}
```

```
#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:158:7)
#1      EditDomainHandler.format (package:analysis_server/src/edit/edit_domain.dart:155:35)
#2      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:373:16)
#3      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:313:45)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#5      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:309:50)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1502:12)
#10     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:308:5)
#11     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:189:16)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#13     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:179:47)
#14     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:120:26)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#22     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#23     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#24     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#25     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#27     _rootRunUnary (dart:async/zone.dart:1134:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#35     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#36     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#37     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#38     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#40     _rootRunUnary (dart:async/zone.dart:1134:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#46     _StreamController._add (dart:async/stream_controller.dart:649:7)
#47     _StreamController.add (dart:async/stream_controller.dart:595:5)
#48     _Socket._onData (dart:io-patch/socket_patch.dart:1873:41)
#49     _rootRunUnary (dart:async/zone.dart:1138:13)
#50     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:773:19)
#55     _StreamController._add (dart:async/stream_controller.dart:649:7)
#56     _StreamController.add (dart:async/stream_controller.dart:595:5)
#57     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1415:33)
#58     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#61     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by DanTup** [comment]
Thanks for the report! I've moved this over to https://github.com/dart-lang/dart_style/issues/892 since that's where the formatting code lives. I'll close this one since once it's fixed in `dart_style` and rolled into the SDK, there's nothing to do in the VS Code extension.

Thanks!
