### ISSUE TITLE
Flutter Daemon Terminates Unexpectedly and Several Flutter Commands Don't Run

### ISSUE THREAD

**Issue by smolck** [Dart-Code/Dart-Code#2344]
See https://github.com/Dart-Code/Dart-Code/issues/2124#issuecomment-609898645 for logs and a description of the problem. The gist is that on opening VSCodium (in a Flutter project), I'll *sometimes* (not always) get a message saying `The Flutter daemon has terminated` and another one saying `cannot call write after a stream was destroyed`. The same sort of message tends to happen when trying to select a device.

In addition, all of the flutter commands (afaik) in the VSCodium commands don't work for various reasons relating to NixOS and its read-only filesystem and overall setup.

<details>
  <summary>`flutter doctor -v` command output from terminal</summary>

```
flutter doctor -v
[  +19 ms] executing: [/nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped/] git -c log.showSignature=false
log -n 1 --pretty=format:%H
[  +36 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped/] git describe --match v*.*.*
--first-parent --long --tags
[   +4 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[   +5 ms] executing: [/nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped/] git rev-parse --abbrev-ref HEAD
[   +3 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +34 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +10 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +36 ms] executing: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version
[ +110 ms] Exit code 0 from: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java
-version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[  +15 ms] executing: [/nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped/] git rev-parse --abbrev-ref
--symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +18 ms] executing: [/nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped/] git -c log.showSignature=false
log -n 1 --pretty=format:%ar
[   +5 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 2 months ago
[  +18 ms] executing: /home/smolck/.cache/flutter/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[  +11 ms] Exit code 255 from: /home/smolck/.cache/flutter/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot
[        ] At least one input is required
           Usage: gen_snapshot [<vm-flags>] [<options>] <dart-kernel-file>             

           Common options:                                                             
           --help                                                                      
             Display this message (add --verbose for information about all VM options).
           --version                                                                   
             Print the VM version.                                                     

           To create a core snapshot:                                                  
           --snapshot_kind=core                                                        
           --vm_snapshot_data=<output-file>                                            
           --isolate_snapshot_data=<output-file>                                       
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as assembly suitable for compilation  
           as a static or dynamic library:                                             
           --snapshot_kind=app-aot-assembly                                            
           --assembly=<output-file>                                                    
           [--strip]                                                                   
           [--obfuscate]                                                               
           [--save-debugging-info=<debug-filename>]                                    
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           To create an AOT application snapshot as an ELF shared library:             
           --snapshot_kind=app-aot-elf                                                 
           --elf=<output-file>                                                         
           [--strip]                                                                   
           [--obfuscate]                                                               
           [--save-debugging-info=<debug-filename>]                                    
           [--save-obfuscation-map=<map-filename>]                                     
           <dart-kernel-file>                                                          

           AOT snapshots can be obfuscated: that is all identifiers will be renamed    
           during compilation. This mode is enabled with --obfuscate flag. Mapping     
           between original and obfuscated names can be serialized as a JSON array     
           using --save-obfuscation-map=<filename> option. See dartbug.com/30524       
           for implementation details and limitations of the obfuscation pass.
[   +8 ms] executing: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version
[  +47 ms] Exit code 0 from: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java
-version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +6 ms] java -version
⣽[ +130 ms] executing: /home/smolck/Android/Sdk/platform-tools/adb devices -l
[ +414 ms] Exit code 0 from: /home/smolck/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
[        ] * daemon not running; starting now at tcp:5037
           * daemon started successfully
[   +5 ms] [✓] Flutter (Channel beta, v1.14.6, on Linux, locale en_US.UTF-8)
[        ]     • Flutter version 1.14.6 at /nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped
[        ]     • Framework revision fabeb2a16f (2 months ago), 2020-01-28 07:56:51 -0800
[        ]     • Engine revision c4229bfbba
[        ]     • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
⣽[  +93 ms] executing: /home/smolck/Android/Sdk/tools/bin/sdkmanager --licenses
 
[+2228 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[        ]     • Android SDK at /home/smolck/Android/Sdk
[        ]     • Android NDK location not configured (optional; useful for native profiling support)
[        ]     • Platform android-29, build-tools 29.0.3
[        ]     • Java binary at: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[        ]     • All Android licenses accepted.
[   +1 ms] [✓] Chrome - develop for the web
[        ]     • CHROME_EXECUTABLE = /home/smolck/.nix-profile/bin/google-chrome-stable
[   +1 ms] [✓] Android Studio (version 3.6)
[        ]     • Android Studio at /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped
[   +1 ms]     • Flutter plugin version 45.0.1
[        ]     • Dart plugin version 192.7761
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
[   +2 ms] [✓] Connected device (2 available)
[        ]     • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
[        ]     • Web Server • web-server • web-javascript • Flutter Tools
[        ] • No issues found!
[   +7 ms] "flutter doctor" took 3,285ms.
```

</details>

<details>
  <summary>`Flutter: Run Flutter Doctor` from within VSCodium</summary>

```

Oops; flutter has exited unexpectedly: "ProcessException: No such file or directory
  Command: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version".
A crash report has been written to /tmp/dart-code-cmd-run/flutter_05.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JvFVi

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/JvFVP

exit code 1
```

Here's also that crash log:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: No such file or directory
  Command: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#5      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:297:45)
#6      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:38:5)
#7      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:95:14)
#8      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:241:54)
#9      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:172:48)
#10     AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:20:55)
#11     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:66:33)
#12     Doctor.validators (package:flutter_tools/src/doctor.dart:144:46)
#13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:150:45)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:256:47)
#15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:58:39)
#16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:638:18)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#18     _rootRunUnary (dart:async/zone.dart:1134:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#24     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
encountered exception: ProcessException: No such file or directory
  Command: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version

#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#5      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:297:45)
#6      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:38:5)
#7      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:95:14)
#8      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:241:54)
#9      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:172:48)
#10     AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:20:55)
#11     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:66:33)
#12     Doctor.validators (package:flutter_tools/src/doctor.dart:144:46)
#13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:150:45)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:256:47)
#15     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:233:26)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#22     _doctorText (package:flutter_tools/runner.dart:232:19)
#23     _informUserOfCrash (package:flutter_tools/runner.dart:155:35)
#24     _handleToolError (package:flutter_tools/runner.dart:136:13)
<asynchronous suspension>
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:69:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1502:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1465:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#37     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#38     run (package:flutter_tools/runner.dart:51:10)
#39     main (package:flutter_tools/executable.dart:65:9)
#40     main (file:///build/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

</details>

<details>
  <summary>`Flutter: Get Packages` from VSCodium</summary>

```
[hacker_typer] flutter packages get
Running "flutter pub get" in hacker_typer...                    
Creation of temporary directory failed, path = '/nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped/.pub-cache/_temp/dir' (OS Error: Read-only file system, errno = 30)
pub get failed (66; Creation of temporary directory failed, path = '/nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped/.pub-cache/_temp/dir' (OS Error: Read-only file system, errno = 30))
exit code 66
```

</details>

<details>
   <summary>`Flutter: Update Packages` in VSCodium</summary>

```
Running "flutter pub upgrade" in hacker_typer...                
Creation of temporary directory failed, path = '/nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped/.pub-cache/_temp/dir' (OS Error: Read-only file system, errno = 30)
pub upgrade failed (66; Creation of temporary directory failed, path = '/nix/store/qkgvznqz5ms7rqb6k7q10m7f1dp93qlf-flutter-beta-1.14.6-unwrapped/.pub-cache/_temp/dir' (OS Error: Read-only file system, errno = 30))
exit code 66
```

</details>

I think a lot of these errors have to do with the Flutter sdk being installed in the read-only Nix store. I'm using `flutter-beta` from Nixpkgs:

```
$ flutter --version
Flutter 1.14.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision fabeb2a16f (2 months ago) • 2020-01-28 07:56:51 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
```

**Comment by DanTup** [comment]
In VS Code, this error occurs when running Doctor:

```
encountered exception: ProcessException: No such file or directory
  Command: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version
```

But that same path shows up in the Terminal's Doctor output and seems to work:

```
[  +36 ms] executing: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java -version
[ +110 ms] Exit code 0 from: /nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin/java
-version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
```

Can you think of any reason why that folder would be visible to the terminal but not VS Code? (eg. something in your terminal startup script that allows it to work, or something about NixOS that might prevent VS Code seeing it?)

**Comment by smolck** [comment]
No, I don’t think so; afaik there’s nothing in my .zshrc that would cause such a difference. Strange.

**Comment by DanTup** [comment]
If you open VS Code and click File -> Open, can you see/browse to `/nix/store/3b7qf6qz9wxn74fwzrs04srsi227m3hv-android-studio-stable-3.6.1.0-unwrapped/jre/bin` in the file dialog?

**Comment by smolck** [comment]
Unfortunately, I switched back to Arch Linux due to this and other issues, and can no longer debug this issue. I’ll leave it up to you whether you want to close this or not. Thanks for all the help, and I apologize for not sticking with NixOS longer to help debug this. (I was really frustrated with NixOS.)

**Comment by DanTup** [comment]
No worries! I'll close this for now, since I'm not sure it's worth me trying to get set up to repro if there might be nobody using it. If anyone comes across this because they're hitting the same issue though, please comment below and I can revisit. Thanks!
