### ISSUE TITLE
Illegal argument error in closing labels

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2439]
This code is generating errors because the `-1` is result is being added to `0` so `translate` is trying to construct a new `Range` with a negative character:

```ts
const lastChar = this.activeEditor.document.getText(new vs.Range(endPos.translate({ characterDelta: -1 }), endPos));
```

https://github.com/Dart-Code/Dart-Code/pull/2437/checks?check_run_id=653111320

```
flutter_icon_decorations
stack trace: Error: Illegal argument: character must be non-negative

    at Object.t.illegalArgument (/Users/runner/runners/2.169.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:784)
    at new e (/Users/runner/runners/2.169.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:426:473)
    at new e (/Users/runner/runners/2.169.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:424:44)
    at translate (/Users/runner/runners/2.169.1/work/Dart-Code/Dart-Code/.vscode-test/vscode-insiders/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:427:709)
    at ClosingLabelsDecorations.update (/Users/runner/runners/2.169.1/work/Dart-Code/Dart-Code/src/extension/decorations/closing_labels_decorations.ts:38:85)
    at /Users/runner/runners/2.169.1/work/Dart-Code/Dart-Code/src/extension/decorations/closing_labels_decorations.ts:21:22
    at map (/Users/runner/runners/2.169.1/work/Dart-Code/Dart-Code/src/shared/services/stdio_service.ts:196:56)
    at Array.map (<anonymous>)
    at DasAnalyzerClient.notify (/Users/runner/runners/2.169.1/work/Dart-Code/Dart-Code/src/shared/services/stdio_service.ts:196:43)
    at DasAnalyzerClient.handleNotification (/Users/runner/runners/2.169.1/work/Dart-Code/Dart-
```

**Comment by DanTup** [comment]
Fixed in 3731db95.
