### ISSUE TITLE
The getter 'apiSignature' was called on null.

### ISSUE THREAD

**Issue by sethladd** [Dart-Code/Dart-Code#246]
Please review the below report for any information you do not wish to share and report to
  https://github.com/dart-lang/sdk/issues/new

Exception from analysis server (running from VSCode / Dart Code)

### What I was doing

(please describe what you were doing when this exception occurred)

### Request

While responding to request: `analysis.setAnalysisRoots`

### Versions

- Dart SDK 1.22.0-dev.5.0
- Visual Studio Code 1.8.1
- Dart Code 0.14.9

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.14.9
```

### Exception

NoSuchMethodError: The getter 'apiSignature' was called on null.
Receiver: null
Tried calling: apiSignature

```text
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AnalysisDriver.AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:256)
#3      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1827)
#4      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1186)
#5      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1247)
#6      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:886)
#7      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:1211)
#8      AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:302)
#9      AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:241)
#10     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:876)
#11     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#12     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:872)
#13     _rootRun (dart:async/zone.dart:1150)
#14     _CustomZone.run (dart:async/zone.dart:1026)
#15     _CustomZone.runGuarded (dart:async/zone.dart:924)
#16     runZoned (dart:async/zone.dart:1501)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:871)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:170)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:189)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:110)
#22     _rootRunUnary (dart:async/zone.dart:1158)
#23     _CustomZone.runUnary (dart:async/zone.dart:1037)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:159)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:134)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:180)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#34     _rootRunUnary (dart:async/zone.dart:1158)
#35     _CustomZone.runUnary (dart:async/zone.dart:1037)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:14)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:256)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:260)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:336)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:329)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:92)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#47     _rootRunUnary (dart:async/zone.dart:1158)
#48     _CustomZone.runUnary (dart:async/zone.dart:1037)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#53     _StreamController._add (dart:async/stream_controller.dart:635)
#54     _StreamController.add (dart:async/stream_controller.dart:581)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1680)
#56     _rootRunUnary (dart:async/zone.dart:1162)
#57     _CustomZone.runUnary (dart:async/zone.dart:1037)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#62     _StreamController._add (dart:async/stream_controller.dart:635)
#63     _StreamController.add (dart:async/stream_controller.dart:581)
#64     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:781)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#68     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by sethladd** [comment]
![screen shot 2017-01-11 at 10 19 45 am](https://cloud.githubusercontent.com/assets/5479/21860919/a5aa8fb4-d7e7-11e6-81be-05fbf2b7bab6.png)

**Comment by DanTup** [comment]
This exception is from the Analyzer, it should be reported at https://github.com/dart-lang/sdk/issues/new

Unfortunately, I can't fix it here ;(

**Comment by sethladd** [comment]
Does this happen with you? Or is it just me?

**Comment by DanTup** [comment]
I haven't had chance to do any Dart lately, though looking at the analytics this error has occurred only 5 times in the last week. I have limited data on who it is but they're all from a Mac, so I'm guessing it's only you. That said, it looks like there have also only been 3 users using `1.22.0-dev.5.0` and later so far (one is me testing the previous bug) so that might not mean much.

I'll try and test it if I can get some time at a PC this weekend, though I think it's worth raising in the sdk repo; it looks like it's a bug in the new driver to me.

**Comment by sethladd** [comment]
OK, thanks. Opened https://github.com/dart-lang/sdk/issues/28399

**Comment by DanTup** [comment]
FWIW, I don't see this opening a small Dart project using SDK `1.22.0-dev.5.0` so it might be specific to something in your code (but still definitely an analyzer bug; it should never crash like that).
