### ISSUE TITLE
Exception on app start in debug

### ISSUE THREAD

**Issue by shashikantdurge** [Dart-Code/Dart-Code#2519]
Could not load source 'dart:core-patch/object_patch.dart': TypeError: Cannot read property 'data' of undefined
	at p.sourceRequest (/Users/shashikant/.vscode/extensions/dart-code.dart-code-3.11.0/out/dist/extension.js:1:249123)
	at p.dispatchRequest (/Users/shashikant/.vscode/extensions/dart-code.dart-code-3.11.0/out/dist/extension.js:1:276479)
	at p.handleMessage (/Users/shashikant/.vscode/extensions/dart-code.dart-code-3.11.0/out/dist/extension.js:1:548364)
	at p._handleData (/Users/shashikant/.vscode/extensions/dart-code.dart-code-3.11.0/out/dist/extension.js:1:550086)
	at Socket.<anonymous> (/Users/shashikant/.vscode/extensions/dart-code.dart-code-3.11.0/out/dist/extension.js:1:548696)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:166:17).

**Comment by DanTup** [comment]
Thanks for the report! Do you have steps to reproduce this?

**Comment by shashikantdurge** [comment]
Just running the app in vs code stops at this exception even if break on exception is unchecked.

I have to continue execution & wait for some seconds and hot restart the app.

It does not happen in android studio.

**Comment by shashikantdurge** [comment]
Is it because of socket events?

**Comment by DanTup** [comment]
So sorry for the delay - this got lost in my inbox. 

Does it happen with every app, such as one created with **Flutter: New Project**? Could you capture a log using the [Capture Logs command](https://dartcode.org/docs/logging/#capture-logs-command) (you can untick Analysis Server when starting the logging, but leave everything else ticked).
