### ISSUE TITLE
After updating Flutter to 1.20 project not started.

### ISSUE THREAD

**Issue by AleksandrKuprienko** [Dart-Code/Dart-Code#2706]
**Flutter doctor show this**:
[✓] Flutter (Channel stable, 1.20.0, on Mac OS X 10.15.6 19G73, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)

**Flutter run show next**:

```
Xcode's output:
↳
    Invalid depfile: /Users/akuper/Desktop/Flutter/bmi-calculator-flutter/.dart_tool/flutter_build/0abee2e3cc8db517db1d32477f3184ee/kernel_snapshot.d
    Invalid depfile: /Users/akuper/Desktop/Flutter/bmi-calculator-flutter/.dart_tool/flutter_build/0abee2e3cc8db517db1d32477f3184ee/kernel_snapshot.d
    Invalid depfile: /Users/akuper/Desktop/Flutter/bmi-calculator-flutter/.dart_tool/flutter_build/0abee2e3cc8db517db1d32477f3184ee/kernel_snapshot.d
    Invalid depfile: /Users/akuper/Desktop/Flutter/bmi-calculator-flutter/.dart_tool/flutter_build/0abee2e3cc8db517db1d32477f3184ee/kernel_snapshot.d
    Error: Could not resolve the package 'characters' in 'package:characters/characters.dart'.
    ../../../Developer/flutter/packages/flutter/lib/src/material/text_field.dart:9:8: Error: Not found: 'package:characters/characters.dart'
    import 'package:characters/characters.dart';
           ^
    ../../../Developer/flutter/packages/flutter/lib/widgets.dart:18:1: Error: Not found: 'package:characters/characters.dart'
    export 'package:characters/characters.dart';
    ^
    ../../../Developer/flutter/packages/flutter/lib/src/rendering/editable.dart:10:8: Error: Not found: 'package:characters/characters.dart'
    import 'package:characters/characters.dart';
           ^
    ../../../Developer/flutter/packages/flutter/lib/src/services/text_formatter.dart:9:8: Error: Not found: 'package:characters/characters.dart'
    import 'package:characters/characters.dart';
           ^
    ../../../Developer/flutter/packages/flutter/lib/src/material/text_field.dart:822:61: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
      int get _currentLength => _effectiveController.value.text.characters.length;
                                                                ^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/material/text_field.dart:824:118: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
      bool get _hasIntrinsicError => widget.maxLength != null && widget.maxLength > 0 && _effectiveController.value.text.characters.length > widget.maxLength;
                                                                                                                         ^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/rendering/editable.dart:244:64: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
           assert(obscuringCharacter != null && obscuringCharacter.characters.length == 1),
                                                                   ^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/rendering/editable.dart:361:35: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
        assert(value != null && value.characters.length == 1);
                                      ^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/rendering/editable.dart:567:11: Error: 'Characters' isn't a type.
        final Characters remaining = string.characters.skipWhile((String currentString) {
              ^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/rendering/editable.dart:567:41: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
        final Characters remaining = string.characters.skipWhile((String currentString) {
                                            ^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/rendering/editable.dart:600:47: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
        for (final String currentString in string.characters) {
                                                  ^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/rendering/editable.dart:602:40: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
              !_isWhitespace(currentString.characters.first.toString().codeUnitAt(0))) {
                                           ^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/services/text_formatter.dart:355:11: Error: 'CharacterRange' isn't a type.
        final CharacterRange iterator = CharacterRange(value.text);
              ^^^^^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/services/text_formatter.dart:355:37: Error: Method not found: 'CharacterRange'.
        final CharacterRange iterator = CharacterRange(value.text);
                                        ^^^^^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/services/text_formatter.dart:356:20: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
        if (value.text.characters.length > maxLength) {
                       ^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/services/text_formatter.dart:375:61: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
        if (maxLength != null && maxLength > 0 && newValue.text.characters.length > maxLength) {
                                                                ^^^^^^^^^^
    ../../../Developer/flutter/packages/flutter/lib/src/services/text_formatter.dart:378:25: Error: The getter 'characters' isn't defined for the class 'String'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'characters'.
          if (oldValue.text.characters.length == maxLength) {
                            ^^^^^^^^^^
    Unhandled exception:
    FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Acharacters%2Fcharacters.dart; message=StandardFileSystem only supports file:* and data:* URIs)
    #0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
    #1      asFileUri (package:vm/kernel_front_end.dart:659:37)
    #2      writeDepfile (package:vm/kernel_front_end.dart:853:21)
    <asynchronous suspension>
    #3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:574:15)
    <asynchronous suspension>
    #4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:43:22)
    #5      starter (package:flutter_frontend_server/server.dart:182:27)
    #6      main (file:///b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:9:30)
    #7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
    #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)


    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.
```

**Comment by DanTup** [comment]
This appears to be a Flutter issue:

https://github.com/flutter/flutter/issues/59645

Some people have reported fixing it by running `flutter clean` and/or `flutter pub get`. If neither of these fix it, please file an issue at https://github.com/flutter/flutter/issues and include a verbose log (from running `flutter run -v`). Thanks!

**Comment by BoevMaksim** [comment]
Had the same problem. Helped `flutter clean`.
