### ISSUE TITLE
Analyzer error when fetching fixes for an error in a file outside of workspace

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#2763]
Using LSP, open a file outside the workspace and generate an error in it, and this happens when fetching codeActions.

```
[Error - 10:14:12 AM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 10:14:12 AM] An error occurred while handling textDocument/codeAction request: NoSuchMethodError: The method 'packagesAvailableTo' was called on null.
Receiver: null
Tried calling: packagesAvailableTo("/Users/danny/Desktop/darttest/foo.dart")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      TransformSetManager.forLibrary (package:analysis_server/src/services/correction/fix/data_driven/transform_set_manager.dart:28:30)
#2      DataDriven._availableTransformSetsForLibrary (package:analysis_server/src/services/correction/dart/data_driven.dart:71:41)
#3      DataDriven.producers.<anonymous closure> (package:analysis_server/src/services/correction/dart/data_driven.dart:31:21)
#4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:165:25)
#5      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1136:46)
<asynchronous suspension>
#6      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1070:11)
#7      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:175:35)
#8      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:245:46)
#9      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:206:7)
#10     CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:74:18)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#12     CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:71:26)
#13     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#14     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:70:26)
#15     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:255:12)
#16     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:67:17)
#17     _rootRunUnary (dart:async/zone.dart:1198:47)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#25     Handler.requireResolvedUnit (package:analysis_server/src/lsp/handlers/handlers.dart)
#26     _rootRunUnary (dart:async/zone.dart:1198:47)
#27     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#32     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#33     _rootRun (dart:async/zone.dart:1190:13)
#34     _CustomZone.run (dart:async/zone.dart:1093:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Comment by DanTup** [comment]
Unable to reproduce this on latest SDK/code.
