### ISSUE TITLE
null ref in buildOccurences of highlight provider

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#277]
I spotted this in the debug window just after closing DC. I don't have a log of what the analyzer response nor can I reproduce it now (I had the Flutter repo open).

```text
Uncaught Exception:  TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at t.positionAt (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:21988)
    at Object.positionAt (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:13:20360)
    at DartDocumentHighlightProvider.buildOccurrences (m:\Coding\Applications\Dart-Code\out\src\providers\dart_highlighting_provider.js:44:61)
    at global.provideDocumentHighlights.disposable.analyzer.registerForAnalysisOccurrences.n (m:\Coding\Applications\Dart-Code\out\src\providers\dart_highlighting_provider.js:23:26)
    at analyzer_gen_1.AnalyzerGen.notify.subscriptions.slice.forEach.sub (m:\Coding\Applications\Dart-Code\out\src\analysis\analyzer.js:146:46)
    at Array.forEach (native)
    at Analyzer.notify (m:\Coding\Applications\Dart-Code\out\src\analysis\analyzer.js:146:31)
    at Analyzer.handleNotification (m:\Coding\Applications\Dart-Code\out\src\analysis\analyzer_gen.js:60:22)
    at Analyzer.handleMessage (m:\Coding\Applications\Dart-Code\out\src\analysis\analyzer.js:78:18)
    at analyzer_gen_1.AnalyzerGen.processMessageBuffer.fullBuffer.split.filter.forEach.m (m:\Coding\Applications\Dart-Code\out\src\analysis\analyzer.js:61:78)
```

**Comment by DanTup** [comment]
Assuming stale; the exception came from inside Code's positionAt method.
