### ISSUE TITLE
Extension fails to activate if there are permissions errors reading folders in the open workspace 

### ISSUE THREAD

**Issue by UditSharma123** [Dart-Code/Dart-Code#2917]
My flutter extension is not working...
All the features of flutter extension is not working in vscode

**Comment by DanTup** [comment]
Do you see syntax highlighting/coloring when you open `.dart` file, or is that missing too?

Can you try clicking Help -> Toggle Developer Tools in VS Code, then clicking Console and see if there are any errors reported there? Thanks!

**Comment by UditSharma123** [comment]
No, syntax highlighting/coloring of .dart file is working fine..
![Screenshot (110)](https://user-images.githubusercontent.com/63443176/97774363-190bd580-1b7d-11eb-9e4f-080d6daa166c.png)

**Comment by DanTup** [comment]
Could you try expanding the error that says Dart-Code failed to activate, to see if it has useful stack trace?

Thanks!

**Comment by UditSharma123** [comment]
it still showing that...

**Comment by DanTup** [comment]
@UditSharma123 can you click the small arrow to the left of "Activating extension Dart-Code.dart-code failed"? It should expand and show a little more detail.

Could you also try enabling the [general extension log](https://dartcode.org/docs/logging/#extension) and reproducing the issue, to see whether that includes anything useful? Thanks!

**Comment by UditSharma123** [comment]
**I got these error:**

[object Object]]Cannot read property 'getRuleStack' of undefined
$onExtensionRuntimeError @ terminalInstanceService.ts:31
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'getRuleStack' of undefined
	at DocumentDecoration.tokenizeLine (c:\Users\udits\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecoration.js:227:35)
	at DocumentDecoration.onDidChangeTextDocument (c:\Users\udits\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecoration.js:39:30)
	at DocumentDecorationManager.onDidChangeTextDocument (c:\Users\udits\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\documentDecorationManager.js:47:32)
	at c:\Users\udits\.vscode\extensions\coenraads.bracket-pair-colorizer-2-0.2.0\out\src\extension.js:30:39
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at t.ExtHostDocuments.$acceptModelChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:715:675)
	at m._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:870:464)
	at m._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:870:156)
	at m._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:868:817)
	at m._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:867:623)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:865:691
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1059:179
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at t.PersistentProtocol._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at p.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
	at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66

**Comment by DanTup** [comment]
That appears to be a different error (that's an error in the `coenraads.bracket-pair-colorizer-2-0` extension).

Could you try enabling the log file linked above to see if that captures the issue? Thanks!

**Comment by UditSharma123** [comment]
could you please tell me how to **"enable _the_ log file"** . Thanks!

**Comment by DanTup** [comment]
@UditSharma123 there are some instructions at the [link above](https://dartcode.org/docs/logging/#extension). You'll need to add it to your VS Code User Settings which you can access by running the **Preferences: Open User Settings** command in VS Code.

You should add something like this:

```js
"dart.extensionLogFile": "C:\\Users\\Danny\\Desktop\\Logs\\dart-code-extension.txt",
```

Replacing the path with one to a valid folder on your machine (be sure to escape the backslashes so they're in pairs).

Then restart VS Code and reproduce the error, and take a copy of that log file.

Thanks!

**Comment by UditSharma123** [comment]
**I did that and I got this in log file**

!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.16.0
Flutter extension: 3.16.0 (not activated)

App: Visual Studio Code
Version: 1.50.1
Platform: win

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General

Tue Nov 03 2020 [23:15:56 GMT+0530 (India Standard Time)] Log file started
[11:15:56 PM] [General] [Info] Searching for SDKs...
[11:15:56 PM] [General] [Info] Environment PATH:
[11:15:56 PM] [General] [Info]     C:\Program Files (x86)\VMware\VMware Player\bin\
[11:15:56 PM] [General] [Info]     C:\Program Files (x86)\Common Files\Oracle\Java\javapath
[11:15:56 PM] [General] [Info]     C:\Windows\system32
[11:15:56 PM] [General] [Info]     C:\Windows
[11:15:56 PM] [General] [Info]     C:\Windows\System32\Wbem
[11:15:56 PM] [General] [Info]     C:\Windows\System32\WindowsPowerShell\v1.0\
[11:15:56 PM] [General] [Info]     C:\Windows\System32\OpenSSH\
[11:15:56 PM] [General] [Info]     C:\Program Files\nodejs\
[11:15:56 PM] [General] [Info]     C:\ProgramData\chocolatey\bin
[11:15:56 PM] [General] [Info]     C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
[11:15:56 PM] [General] [Info]     C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\
[11:15:56 PM] [General] [Info]     C:\Program Files\Microsoft SQL Server\150\Tools\Binn\
[11:15:56 PM] [General] [Info]     C:\Program Files\Microsoft SQL Server\150\DTS\Binn\
[11:15:56 PM] [General] [Info]     C:\Program Files\Git\cmd
[11:15:56 PM] [General] [Info]     C:\Program Files\dotnet\
[11:15:56 PM] [General] [Info]     C:\Windows\Microsoft.NET\Framework64\v4.0.30319
[11:15:56 PM] [General] [Info]     C:\Program Files\Microsoft VS Code\bin
[11:15:56 PM] [General] [Info]     C:\Program Files\VSCodium\bin
[11:15:56 PM] [General] [Info]     C:\Users\udits\AppData\Local\Programs\Python\Python36\Scripts\
[11:15:56 PM] [General] [Info]     C:\Users\udits\AppData\Local\Programs\Python\Python36\
[11:15:56 PM] [General] [Info]     C:\Users\udits\AppData\Local\Microsoft\WindowsApps
[11:15:56 PM] [General] [Info]     C:\Users\udits\AppData\Roaming\npm
[11:15:56 PM] [General] [Info]     C:\Users\udits\AppData\Roaming\Pub\Cache\bin
[11:15:56 PM] [General] [Info]     C:\Users\udits\AppData\Local\Android\Sdk
[11:15:56 PM] [General] [Info]     C:\Users\udits\AppData\Local\Android\Sdk\platform-tools
[11:15:56 PM] [General] [Info]     C:\MinGW\bin
[11:15:56 PM] [General] [Info]     C:\tools\dart-sdk\bin
[11:15:56 PM] [General] [Info]     C:\Users\udits\.dotnet\tools
[11:15:56 PM] [General] [Info]     C:\tools\flutter\bin
[11:15:56 PM] [General] [Info]     C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3\bin




![Screenshot (113)](https://user-images.githubusercontent.com/63443176/98022619-d7548680-1e2b-11eb-9263-95b0d0c40240.png)


Thanks!

**Comment by DanTup** [comment]
@UditSharma123 do you happen to have the root of the drive (`E:\`) open in VS Code? I think that might explain this - we're assuming there are no folder permission issues scanning all of the folders in the open workspace.

As a workaround you could just open a subfolder (`E:\Apps`) or similar, and I'll handle this for the next release. Thanks!

**Comment by UditSharma123** [comment]
**Now it's working
Thanks!!**

**Comment by DanTup** [comment]
I'll keep this open as we should handle this better.
