### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema

### ISSUE THREAD

**Issue by Ahmer97** [Dart-Code/Dart-Code#2965]
when I run flutter doctor --android-licenses in terminal of VS code it showing me this exception 

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

**Comment by DanTup** [comment]
This seems like an Android SDK/Java compatibility issue. There are some possible solutions here:

https://stackoverflow.com/questions/55436585/fix-sdkmanager-java-lang-noclassdeffounderror-batchfile

There's no VS Code-extension code running here since you're just running `flutter` in the VS Code terminal (we have no real interaction with the terminal), so unfortunately there's nothing we could do to improve this from here.
