### ISSUE TITLE
Invalid file path error when conditional member access operator used in const constructor initializer list

### ISSUE THREAD

**Issue by Jjagg** [Dart-Code/Dart-Code#2981]
**Describe the bug**
Running the LSP version, the server consistently returns an 'Invalid file path' error when the active file has the very specific syntax of a conditional member access operator in the initializer list of a const constructor. This syntax is invalid since the initializer expression is not constant, but I did not expect the analyzer to error out and it caused me some grief earlier today. The same error occurs when the initializer expression is not syntactically valid, as long as it contains the conditional member access operator and the constructor is marked const.

**To Reproduce**
1. Create a new dart project with `dart create`
2. Enable NNBD by setting environment SDK version constraint `>= 2.12.0-0` and analyzer setting
```
analyzer:
  enable-experiment:
  - non-nullable
```
3. Replace the entry point file contents with the following:
```dart
class Bug {
  const Bug(int? a) : a = a?.bitLength ?? -1;
  final int a;
}
```
4. Analyzer will respond to every request with 
  > Message: Invalid file path
    Code: -32003

The same error occurs even with syntactically invalid code which makes this seem like a parsing bug. Even the following is enough to cause the error:
```
class Bug {
  const Bug() : ?.
```

**Expected behavior**
The analyzer highlights the initializer expression is not constant.

**Versions (please complete the following information):**
 - VS Code version: 1.51.1
 - Dart extension version: 3.16.0
 - Dart SDK version: 2.12.0-29.10.beta (shipped with newest flutter beta at the time of writing)

Not sure this is useful, but trying to open the element/ast page for the crashing file in the Analysis Server Diagnostics gives a stack trace. It only seems to go through `analyzer`, so I'm sorry if this is the wrong place to report this issue. 

<details>
  <summary>Stacktrace</summary>

```


NoSuchMethodError: The getter 'flow' was called on null. Receiver: null Tried calling: flow #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5) #1 ResolverVisitor.startNullAwarePropertyAccess (package:analyzer/src/generated/resolver.dart:756:23) #2 ResolverVisitor.visitPropertyAccess (package:analyzer/src/generated/resolver.dart:1727:5) #3 PropertyAccessImpl.accept (package:analyzer/src/dart/ast/ast.dart:8381:49) #4 ResolverVisitor.visitConstructorFieldInitializer (package:analyzer/src/generated/resolver.dart:1157:22) #5 ConstructorFieldInitializerImpl.accept (package:analyzer/src/dart/ast/ast.dart:2628:15) #6 AstResolver.resolve (package:analyzer/src/summary2/ast_resolver.dart:85:10) #7 ConstructorInitializerResolver._initializers (package:analyzer/src/summary2/constructor_initializer_resolver.dart:68:20) #8 ConstructorInitializerResolver._constructor (package:analyzer/src/summary2/constructor_initializer_resolver.dart:54:5) #9 ConstructorInitializerResolver.resolve (package:analyzer/src/summary2/constructor_initializer_resolver.dart:31:11) #10 LibraryBuilder.resolveConstructors (package:analyzer/src/summary2/library_builder.dart:240:53) #11 Linker._resolveConstructors (package:analyzer/src/summary2/link.dart:210:15) #12 Linker._buildOutlines (package:analyzer/src/summary2/link.dart:95:5) #13 Linker.link (package:analyzer/src/summary2/link.dart:76:5) #14 link (package:analyzer/src/summary2/link.dart:32:10) #15 LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:215:24) #16 LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:262:17) #17 PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) #18 LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:260:12) #19 new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:77:5) #20 AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1538:27) #21 _rootRun (dart:async/zone.dart:1190:13) #22 _CustomZone.run (dart:async/zone.dart:1093:19) #23 _runZoned (dart:async/zone.dart:1630:10) #24 runZoned (dart:async/zone.dart:1550:10) #25 NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12) #26 AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1536:33) #27 AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1305:30) #28 PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) #29 AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1294:20) #30 AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1247:14) #31 _rootRun (dart:async/zone.dart:1190:13) #32 _CustomZone.run (dart:async/zone.dart:1093:19) #33 _runZoned (dart:async/zone.dart:1630:10) #34 runZoned (dart:async/zone.dart:1550:10) #35 NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12) #36 AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1246:40) #37 AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:932:33) #38 AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24) <asynchronous suspension> #0 LibraryContext._throwLibraryCycleLinkException (package:analyzer/src/dart/analysis/library_context.dart:329:5) #1 LibraryContext.load2.loadBundle (package:analyzer/src/dart/analysis/library_context.dart:220:11) #2 LibraryContext.load2.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:262:17) #3 PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) #4 LibraryContext.load2 (package:analyzer/src/dart/analysis/library_context.dart:260:12) #5 new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:77:5) #6 AnalysisDriver._createLibraryContext.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1538:27) #7 _rootRun (dart:async/zone.dart:1190:13) #8 _CustomZone.run (dart:async/zone.dart:1093:19) #9 _runZoned (dart:async/zone.dart:1630:10) #10 runZoned (dart:async/zone.dart:1550:10) #11 NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12) #12 AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1536:33) #13 AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1305:30) #14 PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15) #15 AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1294:20) #16 AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1247:14) #17 _rootRun (dart:async/zone.dart:1190:13) #18 _CustomZone.run (dart:async/zone.dart:1093:19) #19 _runZoned (dart:async/zone.dart:1630:10) #20 runZoned (dart:async/zone.dart:1550:10) #21 NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12) #22 AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1246:40) #23 AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:932:33) #24 AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24) <asynchronous suspension>

#0      AnalysisDriver._computeAnalysisResult2.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1347:9)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:32:15)
#2      AnalysisDriver._computeAnalysisResult2 (package:analyzer/src/dart/analysis/driver.dart:1294:20)
#3      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1247:14)
#4      _rootRun (dart:async/zone.dart:1190:13)
#5      _CustomZone.run (dart:async/zone.dart:1093:19)
#6      _runZoned (dart:async/zone.dart:1630:10)
#7      runZoned (dart:async/zone.dart:1550:10)
#8      NullSafetyUnderstandingFlag.enableNullSafetyTypes (package:analyzer/dart/element/null_safety_understanding_flag.dart:42:12)
#9      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1246:40)
#10     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:932:33)
#11     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2013:24)
<asynchronous suspension>
```
</details>

**Comment by DanTup** [comment]
I can reproduce this in `2.12.0-29.10.beta` however I can't repro in the latest nightly (`2.12.0-edge.56cf16887c95620e1a9fefd6eb8658c1752402d8`) so I think this has already been fixed in the Dart SDK.

Let me know if you still see it in a more recent build (eg. master). Thanks!
