### ISSUE TITLE
Dart commands and quick fixes don't work in non-Flutter projects (1.5.0-beta)

### ISSUE THREAD

**Issue by pulyaevskiy** [Dart-Code/Dart-Code#321]
Dev tools contain some errors in the console log:

```
[Extension Host] Here is the error stack:  TypeError: Cannot read property 'deviceManager' of undefined
    at activate (/Users/anatoly/.vscode/extensions/DanTup.dart-code-1.5.0-beta.flutter/out/src/extension.js:157:80)
    at Function.t._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:418399)
    at Function.t._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:418184)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:417959
    at Object.m [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:39252)
    at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:42826)
    at n.Class.derive._oncancel._run (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:44654)
    at n.Class.derive._oncancel._completed (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:44095)
    at c (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:47606)
    at J.then.o.(anonymous function) (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:47823)
```

**Comment by Skylled** [comment]
What does your pubspec.yaml file and your project directory look like? Maybe something is going screwy with Flutter detection.

**Comment by DanTup** [comment]
I think it's just a bug from my refactoring... We [only create `flutterDaemon` for flutter projects](https://github.com/Dart-Code/Dart-Code/blob/068d23686aeebcf5b4ce07d755126b65856a4632/src/extension.ts#L106):

```ts
if (util.isFlutterProject) {
	// TODO: finish wiring this up so we can manage the selected device from the status bar (eventualy - use first for now)
	flutterDaemon = new FlutterDaemon(path.join(sdks.flutter, util.flutterPath), vs.workspace.rootPath);
	context.subscriptions.push(flutterDaemon);
}
```

However when creating `SdkCommands` [we assume it's non-null](https://github.com/Dart-Code/Dart-Code/blob/068d23686aeebcf5b4ce07d755126b65856a4632/src/extension.ts#L188):

```ts
let sdkCommands = new SdkCommands(sdks, flutterDaemon.deviceManager);
```

This means anything that relies on `SdkCommands`, or anything that comes after it (`EditCommands`, `TypeHierarchyCommand`, project upgrades, user config prompts, command visibility) will all be broken for non-flutter projects :(

I'll fix tonight and create a new beta that fixes this before I get back to the debugging issues. I don't want people to have to downgrade from the beta in order to use the original functionality!

**Comment by DanTup** [comment]
This is fixed in [the new build](https://github.com/Dart-Code/Dart-Code/releases/tag/v1.5.0-beta.flutter).
