### ISSUE TITLE
Error when typing incorrect setter syntax.

### ISSUE THREAD

**Issue by safield** [Dart-Code/Dart-Code#3314]
When I am typing a specific incorrect setter syntax, I am getting a repeated (one for every character I type) error dialog that says
"A request has failed, see output for more information".

This occurs when I typed out a setter with a missing parameter list...

`set myVar => _myVar;`

For every character typed in _myVar, the following error was output...

```
[Error - 8:07:05 p.m.] Request textDocument/completion failed.
  Message: An error occurred while handling textDocument/completion request
  Code: -32001 
[Error - 8:07:05 p.m.] An error occurred while handling textDocument/completion request: RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:399:7)
#1      getCompletionDetail (package:analysis_server/src/lsp/mapping.dart:520:49)
#2      toCompletionItem (package:analysis_server/src/lsp/mapping.dart:898:13)
#3      CompletionHandler._getServerDartItems.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:261:25)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
#6      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#7      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#8      new List.of (dart:core-patch/array_patch.dart:50:28)
#9      ListIterable.toList (dart:_internal/iterable.dart:211:44)
#10     CompletionHandler._getServerDartItems.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:280:14)
<asynchronous suspension>
#11     CompletionPerformance.runRequestOperation.<anonymous closure> (package:analysis_server/src/services/completion/completion_performance.dart:61:16)
<asynchronous suspension>
#12     OperationPerformanceImpl.runAsync (package:analyzer/src/util/performance/operation_performance.dart:157:14)
<asynchronous suspension>
#13     CompletionHandler._getServerDartItems (package:analysis_server/src/lsp/handlers/handler_completion.dart:225:12)
<asynchronous suspension>
#14     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#15     CompletionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_completion.dart:145:11)
<asynchronous suspension>
#16     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:183:22)
<asynchronous suspension>
#17     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:301:26)
<asynchronous suspension>

```

**Comment by DanTup** [comment]
@safield can you confirm the SDK version you're using, and exactly what code is required to trigger this (and where the cursor is when it occurs)? I've tried adding the code above (and a definition for `_myVar`) to a file using both stable and nightly SDKs, but I've not been able to trigger this. Thanks!
