### ISSUE TITLE
Error updating to newer flutter and dart extension

### ISSUE THREAD

**Issue by fidelisakilan** [Dart-Code/Dart-Code#3319]
**Describe the bug**
I cannot update flutter and dart extension. to version 3.22

**To Reproduce**
1. Go to extensions menu 
2. Click on try to update flutter and dart extension

**Log**
```
c:\Users\fidel\AppData\Roaming\Code\logs\20210504T183135\exthost1\exthost.log for writing: Permission denied: Error: Failed opening file c:\Users\fidel\AppData\Roaming\Code\logs\20210504T183135\exthost1\exthost.log for writing: Permission denied
    at createRotatingLogger (c:\Users\fidel\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:34:9)
    at c:\Users\fidel\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\spdlog\index.js:27:7
    at c:\Users\fidel\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\spdlog\node_modules\mkdirp\index.js:49:26
    at FSReqCallback.oncomplete (fs.js:173:5)
[2021-05-04 18:32:50.127] [renderer1] [error] XHR failed: downloading: XHR failed
    at H.downloadInstallableExtension (file:///C:/Users/fidel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217619)
    at async H.doInstallFromGallery (file:///C:/Users/fidel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)
[2021-05-04 18:42:05.537] [renderer1] [error] ["downloading: XHR failed","    at H.downloadInstallableExtension (file:///C:/Users/fidel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217619)","    at async H.doInstallFromGallery (file:///C:/Users/fidel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)"]
[2021-05-04 18:42:05.603] [renderer1] [error] XHR failed: downloading: XHR failed
    at H.downloadInstallableExtension (file:///C:/Users/fidel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217619)
    at async H.doInstallFromGallery (file:///C:/Users/fidel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)
[2021-05-04 18:42:20.167] [renderer1] [error] ["downloading: XHR failed","    at H.downloadInstallableExtension (file:///C:/Users/fidel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217619)","    at async H.doInstallFromGallery (file:///C:/Users/fidel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)"]
[2021-05-04 18:42:20.304] [renderer1] [error] XHR failed: downloading: XHR failed
    at H.downloadInstallableExtension (file:///C:/Users/fidel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217619)
    at async H.doInstallFromGallery (file:///C:/Users/fidel/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214986)

```
**Screenshots**
![image](https://user-images.githubusercontent.com/24905278/117009263-2ca12000-ad09-11eb-9d13-6329916133f1.png)

**Versions (please complete the following information):**
 - VS Code version: 1.55.2
 - Dart extension version: v3.21.1
 - Dart/Flutter SDK version: Flutter (Channel stable, 2.0.6)

**Comment by DanTup** [comment]
This error seems to be occurring before the extension has been installed, so I don't think it's something that can be caused (or fixed) by the extension. I would recommend filing an issue in VS Code at https://github.com/microsoft/vscode for assistance. Thanks!
