### ISSUE TITLE
Corrupt ZIP

### ISSUE THREAD

**Issue by Cutewarriorlover** [Dart-Code/Dart-Code#3370]
**Describe the bug**
VSCode gives a bug and Dart fails to install:
```
[2021-05-30 08:56:09.449] [renderer1] [error] ["validating: Corrupt ZIP: end of central directory record signature not found","    at H.downloadInstallableExtension (file:///tmp/.mount_VSCodibVDC3H/usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217098)","    at async H.doInstallFromGallery (file:///tmp/.mount_VSCodibVDC3H/usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214247)"]
[2021-05-30 08:56:09.452] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
    at H.downloadInstallableExtension (file:///tmp/.mount_VSCodibVDC3H/usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:217098)
    at async H.doInstallFromGallery (file:///tmp/.mount_VSCodibVDC3H/usr/share/codium/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:47:214247)
```

**To Reproduce**
1. Install the Dart extension
2. There's a bug

**Expected behavior**
VSCode to install the Dart extension

**Versions (please complete the following information):**
 - VS Code version: VSCodium 1.56.2
 - Dart extension version: 3.22.0
 - Dart/Flutter SDK version: 
```
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (3 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1
```

**Comment by DanTup** [comment]
Thanks for the report! This extension is not involved in the downloading and installation of itself, so the problem here must be elsewhere. The download/unzipping occurs before any extension code can run, so there's unfortunately nothing we can do that could resolve this.

If you can reproduce this, I would file it with VS Code or their marketplace if you're sure it's not a local issue and see what they advise.

Some issues that may be related:

- https://github.com/microsoft/vscode/issues/124466
- https://github.com/microsoft/vscode/issues/117169

Thanks!

**Comment by Cutewarriorlover** [comment]
From my tests, I've seen that both the Dart and Flutter plugins cause this issue, none else, and as far as I know, Flutter packs the Dart plugin, so I'm not too sure that this is VSCode specific.

**Comment by DanTup** [comment]
@Cutewarriorlover there are a lot of users (including myself) that have installed the plugins from the VS Code marketplace without any issues, so it doesn't seem like the source files are corrupt. It seems like something has gone wrong downloading the files, and that's entirely outside of the control of the extensions.

I don't think there's anything I can do here to solve this, but if you think that's not the case please provide more details so I can have a look. Thanks!
