### ISSUE TITLE
Stack trace outside the display area.

### ISSUE THREAD

**Issue by tbm98** [Dart-Code/Dart-Code#3411]
Same error but
android studio
```
Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
Running Xcode build...
Xcode build done.                                           37.1s
Debug service listening on ws://127.0.0.1:60657/WVsPD7HD02A=/ws
Syncing files to device iPhone SE (2nd generation)...

======== Exception caught by rendering library =====================================================
The following _CastError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was: 
  SliverPersistentHeader file:///Users/minhtb2/dev/projects/design-module/example/lib/pages/ds_components/appBar/sliver_app_bar_select_page.dart:161:19
When the exception was thrown, this was the stack: 
#0      DSSliverAppBar.build (package:design_module/src/viewComponents/ds_sliver_app_bar.dart:157:15)
#1      _SliverPersistentHeaderElement._build.<anonymous closure> (package:flutter/src/widgets/sliver_persistent_header.dart:232:25)
#2      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2535:19)
#3      _SliverPersistentHeaderElement._build (package:flutter/src/widgets/sliver_persistent_header.dart:229:12)
#4      _RenderSliverPersistentHeaderForWidgetsMixin.updateChild (package:flutter/src/widgets/sliver_persistent_header.dart:311:15)
...
The following RenderObject was being processed when the exception was fired: _RenderSliverPinnedPersistentHeaderForWidgets#4592b relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
...  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 667.0, crossAxisExtent: 375.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 667.0, remainingCacheExtent: 917.0, cacheOrigin: 0.0)
...  geometry: null
...  maxExtent: 124.0
...  child position: EXCEPTION (_CastError)
RenderObject: _RenderSliverPinnedPersistentHeaderForWidgets#4592b relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
  parentData: paintOffset=Offset(0.0, 0.0) (can use size)
  constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 667.0, crossAxisExtent: 375.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 667.0, remainingCacheExtent: 917.0, cacheOrigin: 0.0)
  geometry: null
  maxExtent: 124.0
  child position: EXCEPTION (_CastError)
====================================================================================================

======== Exception caught by rendering library =====================================================
The following _CastError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was: 
  CustomScrollView file:///Users/minhtb2/dev/projects/design-module/example/lib/pages/ds_components/appBar/sliver_app_bar_select_page.dart:158:22
When the exception was thrown, this was the stack: 
#0      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:525:64)
#1      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1574:12)
#2      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1483:20)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1779:7)
#4      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
...
The following RenderObject was being processed when the exception was fired: RenderViewport#00850 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, h=667.0)
...  size: Size(375.0, 667.0)
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#2f613(offset: 0.0, range: null..null, viewport: 667.0, ScrollableState, ClampingScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#ce4e0, ScrollDirection.idle)
...  anchor: 0.0
RenderObject: RenderViewport#00850 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=375.0, h=667.0)
  size: Size(375.0, 667.0)
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#2f613(offset: 0.0, range: null..null, viewport: 667.0, ScrollableState, ClampingScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#ce4e0, ScrollDirection.idle)
  anchor: 0.0
...  center child: _RenderSliverPinnedPersistentHeaderForWidgets#4592b relayoutBoundary=up1 NEEDS-PAINT
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 667.0, crossAxisExtent: 375.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 667.0, remainingCacheExtent: 917.0, cacheOrigin: 0.0)
...    geometry: null
...    maxExtent: 124.0
...    child position: EXCEPTION (_CastError)
...  child 1: RenderSliverToBoxAdapter#c52ab NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: paintOffset=Offset(0.0, 0.0)
...    constraints: MISSING
...    geometry: null
...    child: _RenderColoredBox#87229 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: paintOffset=Offset(0.0, 0.0)
...      constraints: MISSING
...      size: MISSING
...      behavior: opaque
...      child: RenderFlex#02f02 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderConstrainedBox#ba353 NEEDS-LAYOUT NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          size: MISSING
...          additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=100.0)
...        child 2: RenderSemanticsAnnotations#6f6bf NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          semantic boundary
...          size: MISSING
...        child 3: RenderConstrainedBox#bcc77 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          size: MISSING
...          additionalConstraints: BoxConstraints(w=Infinity, h=1000.0)
====================================================================================================

======== Exception caught by rendering library =====================================================
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was: 
  CustomScrollView file:///Users/minhtb2/dev/projects/design-module/example/lib/pages/ds_components/appBar/sliver_app_bar_select_page.dart:158:22
When the exception was thrown, this was the stack: 
#0      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:653:25)
#1      RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:645:7)
#2      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#3      PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:139:11)
#4      PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
...
The following RenderObject was being processed when the exception was fired: RenderViewport#00850
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=375.0, h=667.0)
...  layer: OffsetLayer#e9095 DETACHED
...    engine layer: Null#007db
...    offset: Offset(0.0, 0.0)
...  size: Size(375.0, 667.0)
...  axisDirection: down
...  crossAxisDirection: right
...  offset: ScrollPositionWithSingleContext#2f613(offset: 0.0, range: null..null, viewport: 667.0, ScrollableState, ClampingScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#ce4e0, ScrollDirection.idle)
...  anchor: 0.0
RenderObject: RenderViewport#00850
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=375.0, h=667.0)
  layer: OffsetLayer#e9095 DETACHED
    engine layer: Null#007db
    offset: Offset(0.0, 0.0)
  size: Size(375.0, 667.0)
  axisDirection: down
  crossAxisDirection: right
  offset: ScrollPositionWithSingleContext#2f613(offset: 0.0, range: null..null, viewport: 667.0, ScrollableState, ClampingScrollPhysics -> ClampingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#ce4e0, ScrollDirection.idle)
  anchor: 0.0
...  center child: _RenderSliverPinnedPersistentHeaderForWidgets#4592b relayoutBoundary=up1 NEEDS-PAINT
...    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
...    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 667.0, crossAxisExtent: 375.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 667.0, remainingCacheExtent: 917.0, cacheOrigin: 0.0)
...    geometry: null
...    maxExtent: 124.0
...    child position: EXCEPTION (_CastError)
...  child 1: RenderSliverToBoxAdapter#c52ab NEEDS-LAYOUT NEEDS-PAINT
...    needs compositing
...    parentData: paintOffset=Offset(0.0, 0.0)
...    constraints: MISSING
...    geometry: null
...    child: _RenderColoredBox#87229 NEEDS-LAYOUT NEEDS-PAINT
...      needs compositing
...      parentData: paintOffset=Offset(0.0, 0.0)
...      constraints: MISSING
...      size: MISSING
...      behavior: opaque
...      child: RenderFlex#02f02 NEEDS-LAYOUT NEEDS-PAINT
...        needs compositing
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: max
...        crossAxisAlignment: center
...        verticalDirection: down
...        child 1: RenderConstrainedBox#ba353 NEEDS-LAYOUT NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          size: MISSING
...          additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=100.0)
...        child 2: RenderSemanticsAnnotations#6f6bf NEEDS-LAYOUT NEEDS-PAINT
...          needs compositing
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          semantic boundary
...          size: MISSING
...        child 3: RenderConstrainedBox#bcc77 NEEDS-LAYOUT NEEDS-PAINT
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          size: MISSING
...          additionalConstraints: BoxConstraints(w=Infinity, h=1000.0)
====================================================================================================

======== Exception caught by scheduler library =====================================================
The following _CastError was thrown during a scheduler callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      RenderViewportBase.visitChildrenForSemantics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:221:56)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:437:13)
#2      Iterable.forEach (dart:core/iterable.dart:257:23)
#3      RenderViewportBase.visitChildrenForSemantics (package:flutter/src/rendering/viewport.dart:222:10)
#4      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2670:5)
...
====================================================================================================
```

vscode
```
════════ Exception caught by rendering library ═════════════════════════════════
The following _CastError was thrown during performLayout():
Null check operator used on a null value

The relevant error-causing widget was
SliverPersistentHeader
lib/…/appBar/sliver_app_bar_select_page.dart:161
When the exception was thrown, this was the stack
#0      DSSliverAppBar.build
package:design_module/…/viewComponents/ds_sliver_app_bar.dart:157
#1      _SliverPersistentHeaderElement._build.<anonymous closure>
package:flutter/…/widgets/sliver_persistent_header.dart:232
#2      BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2535
#3      _SliverPersistentHeaderElement._build
package:flutter/…/widgets/sliver_persistent_header.dart:229
#4      _RenderSliverPersistentHeaderForWidgetsMixin.updateChild
package:flutter/…/widgets/sliver_persistent_header.dart:311
...
The following RenderObject was being processed when the exception was fired: _RenderSliverPinnedPersistentHeaderForWidgets#6bd35 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
RenderObject: _RenderSliverPinnedPersistentHeaderForWidgets#6bd35 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
    parentData: paintOffset=Offset(0.0, 0.0) (can use size)
    constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle, scrollOffset: 0.0, remainingPaintExtent: 667.0, crossAxisExtent: 375.0, crossAxisDirection: AxisDirection.right, viewportMainAxisExtent: 667.0, remainingCacheExtent: 917.0, cacheOrigin: 0.0)
    geometry: null
    maxExtent: 124.0
    child position: EXCEPTION (_CastError)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was
CustomScrollView
lib/…/appBar/sliver_app_bar_select_page.dart:158
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Null check operator used on a null value
The relevant error-causing widget was
CustomScrollView
lib/…/appBar/sliver_app_bar_select_page.dart:158
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════
Application finished.

```

**Comment by tbm98** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/52562340/122325544-ff28d280-cf54-11eb-8c80-347bf70fa801.gif)
I think it is UI bug

**Comment by DanTup** [comment]
@tbm98 do you have a code sample I can use to reproduce this? I tried causing an error like this in a build method, but it was only reported once so I guess there's something specific about where it occurs that affects this:

<img width="1419" alt="Screenshot 2021-06-17 at 11 54 43" src="https://user-images.githubusercontent.com/1078012/122383533-d3144e00-cf62-11eb-99f0-243ce4fa1e97.png">

**Comment by tbm98** [comment]
@DanTup my example repo.
it's `vscode console error`. I think because the links of stack trace were aligned to the right and if console content is too long it will be off-screen
<img width="398" alt="Screen Shot 2021-06-17 at 23 11 59" src="https://user-images.githubusercontent.com/52562340/122434798-9d528200-cfc1-11eb-8a1f-9332972b8542.png">
<img width="1012" alt="Screen Shot 2021-06-17 at 23 17 20" src="https://user-images.githubusercontent.com/52562340/122435446-35e90200-cfc2-11eb-9b73-659f39194d1a.png">
<img width="1036" alt="Screen Shot 2021-06-17 at 23 17 08" src="https://user-images.githubusercontent.com/52562340/122435463-38e3f280-cfc2-11eb-8eeb-36da95a33a85.png">

**Comment by DanTup** [comment]
@tbm98 do you have VS Code's Debug Console line wrap disabled?

<img width="664" alt="Screenshot 2021-06-18 at 16 08 20" src="https://user-images.githubusercontent.com/1078012/122581890-717ddd80-d04f-11eb-8f13-eee59a30c7b2.png">

**Comment by tbm98** [comment]
yes

**Comment by tbm98** [comment]
it worked correctly when I enable it. :D
