### ISSUE TITLE
Exception: Expected endLine at params.errors[0].location

### ISSUE THREAD

**Issue by evanweible-wf** [Dart-Code/Dart-Code#3471]
**Describe the bug**

When using Dart 2.13.4 in some of our larger projects, I get repeated error notifications in the bottom right that say only this:

```
Socket error: Exception: Expected endLine at params.errors[0].location
```

I'm not sure how to get more information from this error (like which file/context was being analyzed or what the rest of the `params` object looks like), so I'm not sure how to reproduce this. The only thing I have to go on right now is that I do not see this issue if I switch my Dart version back to 2.7.2.

**Expected behavior**
No errors (analysis seems to work correctly when run manually).

**Versions (please complete the following information):**
 - VS Code version: 1.59.0-insider (a9070718ebb793eef4e94e34307eee15c09a0cd4)
 - Dart extension version: 3.24.2
 - Dart/Flutter SDK version: 2.13.4

**Comment by DanTup** [comment]
Are you able to provide a screenshot of exactly where this error appears? And is there any additional info in the VS Code/Chromium developer tools (Help -> Toggle Developer Tools -> console)?

If you enable the [analysis server log](https://dartcode.org/docs/logging/#analyzer) that file might have a little more information about what's going wrong.

Thanks!

**Comment by evanweible-wf** [comment]
![Screen Shot 2021-07-13 at 11 14 12 AM](https://user-images.githubusercontent.com/1738457/125496585-ac840da0-e3d5-4341-aa29-7b45fcf90068.png)

The error in the dev console only provides one extra stack trace line:
```
Socket error: Exception: Expected endLine at params.errors[0].location
onDidChangeNotification @ notificationsAlerts.ts:40
```

There is another error in the console, but I'm not sure if it's related:
```
ERR unknown handler: Error: unknown handler
    at l.$unregisterCommentController (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2571:52158)
    at o._doInvokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1690:11989)
    at o._invokeHandler (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1690:11673)
    at o._receiveRequest (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1690:10335)
    at o._receiveOneMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1690:9122)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1690:7218
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at s.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:16496)
    at h._receiveMessage (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:21762)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:18640
    at a.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1712)
    at b.acceptChunk (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13857)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13205
    at Socket.D (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2829:153820)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Here's an excerpt from the analysis server log with that `endLine` error:
```
[6:22:41 PM] [Analyzer] [Info] <== {"method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/evanweible/dev/evanweible-wf/wdesk_sdk/app/lib/src/more_examples_extension/constants.dart","diagnostics":[]},"jsonrpc":"2.0"}
[6:22:41 PM] [Analyzer] [Info] <== Content-Length: 150
Content-Type: application/vscode-jsonrpc; charset=utf-8
[6:22:41 PM] [Analyzer] [Info] <== {"method":"window/showMessage","params":{"type":1,"message":"Socket error: Exception: Expected endLine at params.errors[0].location"},"jsonrpc":"2.0"}
[6:22:41 PM] [Analyzer] [Info] <== Content-Length: 1894
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"window/logMessage","params":{"type":1,"message":"Socket error: Exception: Expected endLine at params.errors[0].location: Exception: Expected endLine at params.errors[0].location\n#0      new Location.fromJson (package:analyzer_plugin/protocol/protocol_common.dart:2955:9)\n#1      new AnalysisError.fromJson (package:analyzer_plugin/protocol/protocol_common.dart:156:29)\n#2      new AnalysisErrorsParams.fromJson.<anonymous closure> (package:analyzer_plugin/protocol/protocol_generated.dart:125:31)\n#3      JsonDecoder.decodeList (package:analyzer_plugin/src/protocol/protocol_internal.dart:315:27)\n#4      new AnalysisErrorsParams.fromJson (package:analyzer_plugin/protocol/protocol_generated.dart:121:30)\n#5      new AnalysisErrorsParams.fromNotification (package:analyzer_plugin/protocol/protocol_generated.dart:136:33)\n#6      AbstractNotificationManager.handlePluginNotification (package:analysis_server/src/plugin/notification_manager.dart:84:50)\n#7      PluginSession.handleNotification (package:analysis_server/src/plugin/plugin_manager.dart:844:10)\n#8      ServerIsolateChannel.listen.<anonymous closure> (package:analyzer_plugin/src/channel/isolate_channel.dart:234:25)\n#9      _rootRunUnary (dart:async/zone.dart:1370:13)\n#10     _CustomZone.runUnary (dart:async/zone.dart:1265:19)\n#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)\n#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)\n#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)\n#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)\n#15     _StreamController._add (dart:async/stream_controller.dart:607:7)\n#16     _StreamController.add (dart:async/stream_controller.dart:554:5)\n#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)\n"},"jsonrpc":"2.0"}
```

Even here, the error doesn't reference a file. And although there are `textDocument/publishDiagnostics` logs around these errors that reference files, I think they're independent and not very helpful.. but I'm not sure. ¯\_(ツ)_/¯

**Comment by DanTup** [comment]
@bwilkerson I think this could be related to https://github.com/dart-lang/sdk/commit/d00ef8611a79b44f18f854bb4e73b35bee1176f3 - eg. a plugin generating errors that don't include these new fields?

```
Socket error:

Exception: Expected endLine at params.errors[0].location: Exception: Expected endLine at params.errors[0].location
#0      new Location.fromJson (package:analyzer_plugin/protocol/protocol_common.dart:2955:9)
#1      new AnalysisError.fromJson (package:analyzer_plugin/protocol/protocol_common.dart:156:29)
#2      new AnalysisErrorsParams.fromJson.<anonymous closure> (package:analyzer_plugin/protocol/protocol_generated.dart:125:31)
#3      JsonDecoder.decodeList (package:analyzer_plugin/src/protocol/protocol_internal.dart:315:27)
#4      new AnalysisErrorsParams.fromJson (package:analyzer_plugin/protocol/protocol_generated.dart:121:30)
#5      new AnalysisErrorsParams.fromNotification (package:analyzer_plugin/protocol/protocol_generated.dart:136:33)
#6      AbstractNotificationManager.handlePluginNotification (package:analysis_server/src/plugin/notification_manager.dart:84:50)
#7      PluginSession.handleNotification (package:analysis_server/src/plugin/plugin_manager.dart:844:10)
#8      ServerIsolateChannel.listen.<anonymous closure> (package:analyzer_plugin/src/channel/isolate_channel.dart:234:25)
#9      _rootRunUnary (dart:async/zone.dart:1370:13)
#10     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#15     _StreamController._add (dart:async/stream_controller.dart:607:7)
#16     _StreamController.add (dart:async/stream_controller.dart:554:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by bwilkerson** [comment]
Yes, it looks like it. I think we should have make those fields optional in order to be backward compatible. Do you want to look into that or would you like me to?

**Comment by DanTup** [comment]
I'm not entirely sure of the implications of it being optional (I presume there is some consuming code that needs these values) so you may be better placed than me, but I don't mind having a look if you don't get to it (won't be before tomorrow though).

Would the goal be for them to just optional entirely, or optional for plugins and added in by the server before being exposed (based on the modified files, I'm guessing it's `dart fix` using them?).

**Comment by bwilkerson** [comment]
Yes, `dart fix` was the reason we added them. We're currently sharing the definition of `Location` across both protocols, and I think there's value in that, so I'd guess that we'd just make them optional everywhere. Plugins can't currently contribute to `dart fix` (I'm not entirely sure how that would work, but that's a different discussion), so making them optional won't impact it.

I'm not sure what the right default value is when plugins don't provide that data, but we might be able to add it on the server side when plugins don't provide it, as you suggested. It's definitely worth looking into more.

I'll see whether I can take a look at it fairly soon.

**Comment by bwilkerson** [comment]
I started looking at this, and it appears that I was misremembering. The `dart fix` command isn't using these fields. They're being used for the `--format=json` option in `dart analyze`. In any case, I hope to have a CL out for review later this evening.

**Comment by bwilkerson** [comment]
I think this should have been fixed by https://dart-review.googlesource.com/c/sdk/+/206942.

**Comment by DanTup** [comment]
@evanweible-wf closing this as fixed by the change above, but if you still see issues using an SDK that includes that change, please let us know. Thanks!

**Comment by evanweible-wf** [comment]
Thank you for the quick fix!
