### ISSUE TITLE
Very slow on saving Dart files

### ISSUE THREAD

**Issue by pd4d10** [Dart-Code/Dart-Code#3484]
**Describe the bug**
Very slow on saving Dart files, when set ` "editor.formatOnSave": true,`

**To Reproduce**
Just save any Dart files with changes, in a Flutter project

**Expected behavior**
Got lots of errors in `Log (Extension Host)`, not quite sure if related to this issue.

```
[2021-07-21 12:05:56.323] [exthost] [error] [Dart-Code.dart-code] provider FAILED
[2021-07-21 12:05:56.324] [exthost] [error] Canceled: Canceled
    at LanguageClient.makeCancelError (/Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:31591:24)
    at LanguageClient.handleFailedRequest (/Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:31581:28)
    at /Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:30156:39
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)
[2021-07-21 12:05:56.324] [exthost] [error] [Dart-Code.dart-code] provider FAILED
[2021-07-21 12:05:56.324] [exthost] [error] Canceled: Canceled
    at LanguageClient.makeCancelError (/Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:31591:24)
    at LanguageClient.handleFailedRequest (/Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:31581:28)
    at /Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:30156:39
[2021-07-21 12:05:56.324] [exthost] [error] [Dart-Code.dart-code] provider FAILED
[2021-07-21 12:05:56.324] [exthost] [error] Canceled: Canceled
    at LanguageClient.makeCancelError (/Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:31591:24)
    at LanguageClient.handleFailedRequest (/Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:31581:28)
    at /Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:30156:39
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:434:9)
[2021-07-21 12:05:56.324] [exthost] [error] [Dart-Code.dart-code] provider FAILED
[2021-07-21 12:05:56.324] [exthost] [error] Canceled: Canceled
    at LanguageClient.makeCancelError (/Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:31591:24)
    at LanguageClient.handleFailedRequest (/Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:31581:28)
    at /Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:30156:39
[2021-07-21 12:05:56.395] [exthost] [error] [Dart-Code.dart-code] provider FAILED
[2021-07-21 12:05:56.395] [exthost] [error] Canceled: Canceled
    at LanguageClient.makeCancelError (/Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:31591:24)
    at LanguageClient.handleFailedRequest (/Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:31581:28)
    at /Users/z/.vscode/extensions/dart-code.dart-code-3.24.2/out/dist/extension.js:30156:39
```

**Screenshots**

![image](https://user-images.githubusercontent.com/9524411/126429795-7d5c1d54-21b0-4a02-8599-c2ad637c3e19.png)

**Versions (please complete the following information):**
 - VS Code version: 1.58.2
 - Dart extension version: 3.24.2
 - Dart/Flutter SDK version:  2.2.3

**Comment by DanTup** [comment]
I suspect those errors might just be due to VS Code cancelling the requests (and the server responding with cancelled errors).

Does this occur only in one specific project, or also if you create a brand new project?

Could you try capturing a log while reproducing this?

- Run the [**Dart: Capture Analysis Server Logs** command](https://dartcode.org/docs/logging/#capture-analysis-server-logs)
- Modify the file slightly
- Click Save to reproduce the issue
- Wait for 30 seconds to ensure the log includes as much as possible
- Click **Cancel** on the logging notification to stop logging and open the log
- Remove anything sensitive from the log
- Attach the log here (or in a gist)

Thanks!

**Comment by pd4d10** [comment]
It seems that the `textDocument/documentSymbol` method costs most of the time.

Sorry that I can't post the full log here because of the sensitive stuff.

```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.24.2
Flutter extension: 3.24.0 (activated)

App: Visual Studio Code
Version: 1.58.2
Platform: mac

Workspace type: Dart, Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /Users/z/github/flutter/bin/cache/dart-sdk
    Ver: 2.13.4
Flutter SDK:
    Loc: /Users/z/github/flutter
    Ver: 2.2.3

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, Analyzer, CommandProcesses


{"method":"dart/textDocument/publishClosingLabels","params":{"uri":"file:///Users/z/project/lib/biz/home/balance.dart","labels":[{"range":{"start":{"line":15,"character":11},"end":{"line":54,"character":5}},"label":"Column"},{"range":{"start":{"line":17,"character":8},"end":{"line":38,"character":9}},"label":"Container"},{"range":{"start":{"line":19,"character":17},"end":{"line":37,"character":11}},"label":"Column"},{"range":{"start":{"line":21,"character":14},"end":{"line":24,"character":15}},"label":"Text"},{"range":{"start":{"line":25,"character":14},"end":{"line":28,"character":15}},"label":"Text"},{"range":{"start":{"line":29,"character":14},"end":{"line":35,"character":15}},"label":"ElevatedButton"},{"range":{"start":{"line":39,"character":8},"end":{"line":45,"character":9}},"label":"ListTile"},{"range":{"start":{"line":46,"character":8},"end":{"line":52,"character":9}},"label":"ListTile"}]},"jsonrpc":"2.0"}Content-Length: 6412
Content-Type: application/vscode-jsonrpc; charset=utf-8
[上午11:08:56] [Analyzer] [Info] <== {"method":"dart/textDocument/publishOutline","params":{"uri":"file:///Users/z/project/lib/biz/home/balance.dart","outline":{"element":{"range":{"start":{"line":0,"character":0},"end":{"line":57,"character":0}},"name":"<unit>","kind":"COMPILATION_UNIT"},"range":{"start":{"line":0,"character":0},"end":{"line":57,"character":0}},"codeRange":{"start":{"line":0,"character":0},"end":{"line":57,"character":0}},"children":[{"element":{"range":{"start":{"line":3,"character":6},"end":{"line":3,"character":17}},"name":"BalancePage","kind":"CLASS"},"range":{"start":{"line":3,"character":0},"end":{"line":8,"character":1}},"codeRange":{"start":{"line":3,"character":0},"end":{"line":8,"character":1}},"children":[{"element":{"range":{"start":{"line":4,"character":8},"end":{"line":4,"character":19}},"name":"BalancePage","kind":"CONSTRUCTOR","parameters":"({Key? key})"},"range":{"start":{"line":4,"character":2},"end":{"line":4,"character":50}},"codeRange":{"start":{"line":4,"character":2},"end":{"line":4,"character":50}}},{"element":{"range":{"start":{"line":7,"character":20},"end":{"line":7,"character":31}},"name":"createState","kind":"METHOD","parameters":"()","returnType":"_BalancePageState"},"range":{"start":{"line":6,"character":2},"end":{"line":7,"character":57}},"codeRange":{"start":{"line":7,"character":2},"end":{"line":7,"character":57}}}]},{"element":{"range":{"start":{"line":10,"character":6},"end":{"line":10,"character":23}},"name":"_BalancePageState","kind":"CLASS"},"range":{"start":{"line":10,"character":0},"end":{"line":56,"character":1}},"codeRange":{"start":{"line":10,"character":0},"end":{"line":56,"character":1}},"children":[{"element":{"range":{"start":{"line":11,"character":8},"end":{"line":11,"character":13}},"name":"count","kind":"FIELD","returnType":""},"range":{"start":{"line":11,"character":2},"end":{"line":11,"character":20}},"codeRange":{"start":{"line":11,"character":8},"end":{"line":11,"character":19}}},{"element":{"range":{"start":{"line":14,"cha…
[上午11:08:56] [Analyzer] [Info] <== {"method":"dart/textDocument/publishFlutterOutline","params":{"uri":"file:///Users/z/project/lib/biz/home/balance.dart","outline":{"kind":"DART_ELEMENT","dartElement":{"range":{"start":{"line":0,"character":0},"end":{"line":57,"character":0}},"name":"<unit>","kind":"COMPILATION_UNIT"},"range":{"start":{"line":0,"character":0},"end":{"line":57,"character":0}},"codeRange":{"start":{"line":0,"character":0},"end":{"line":57,"character":0}},"children":[{"kind":"DART_ELEMENT","dartElement":{"range":{"start":{"line":3,"character":6},"end":{"line":3,"character":17}},"name":"BalancePage","kind":"CLASS"},"range":{"start":{"line":3,"character":0},"end":{"line":8,"character":1}},"codeRange":{"start":{"line":3,"character":0},"end":{"line":8,"character":1}},"children":[{"kind":"DART_ELEMENT","dartElement":{"range":{"start":{"line":4,"character":8},"end":{"line":4,"character":19}},"name":"BalancePage","kind":"CONSTRUCTOR","parameters":"({Key? key})"},"range":{"start":{"line":4,"character":2},"end":{"line":4,"character":50}},"codeRange":{"start":{"line":4,"character":2},"end":{"line":4,"character":50}}},{"kind":"DART_ELEMENT","dartElement":{"range":{"start":{"line":7,"character":20},"end":{"line":7,"character":31}},"name":"createState","kind":"METHOD","parameters":"()","returnType":"_BalancePageState"},"range":{"start":{"line":6,"character":2},"end":{"line":7,"character":57}},"codeRange":{"start":{"line":7,"character":2},"end":{"line":7,"character":57}}}]},{"kind":"DART_ELEMENT","dartElement":{"range":{"start":{"line":10,"character":6},"end":{"line":10,"character":23}},"name":"_BalancePageState","kind":"CLASS"},"range":{"start":{"line":10,"character":0},"end":{"line":56,"character":1}},"codeRange":{"start":{"line":10,"character":0},"end":{"line":56,"character":1}},"children":[{"kind":"DART_ELEMENT","dartElement":{"range":{"start":{"line":11,"character":8},"end":{"line":11,"character":13}},"name":"count","kind":"FIELD","returnType":""},"range":{"start":{"line":11,"character":…
[上午11:08:56] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[上午11:08:56] [Analyzer] [Info] <== {"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}},"jsonrpc":"2.0"}
[上午11:08:56] [Analyzer] [Info] ==> Content-Length: 18555
[上午11:08:56] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":190,"method":"textDocument/formatting","params":{"textDocument":{"uri":"file:///Users/z/project/lib/biz/home/balance.dart"},"options":{"tabSize":2,"insertSpaces":true}}}
[上午11:08:56] [Analyzer] [Info] ==> Content-Length: 152
[上午11:08:56] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":191,"method":"textDocument/foldingRange","params":{"textDocument":{"uri":"file:///Users/z/project/lib/biz/home/balance.dart"}}}
[上午11:08:56] [Analyzer] [Info] ==> Content-Length: 255
[上午11:08:56] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":192,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///Users/z/project/lib/biz/home/balance.dart"},"range":{"start":{"line":18,"character":0},"end":{"line":18,"character":0}},"context":{"diagnostics":[]}}}
[上午11:08:56] [Analyzer] [Info] ==> Content-Length: 159
[上午11:08:56] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":193,"method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///Users/z/project/lib/biz/home/balance.dart"}}}
[上午11:08:58] [Analyzer] [Info] ==> Content-Length: 154
[上午11:08:58] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":194,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///Users/z/project/lib/biz/home/balance.dart"}}}
[上午11:09:12] [Analyzer] [Info] <== Content-Length: 98
Content-Type: application/vscode-jsonrpc; charset=utf-8
[上午11:09:12] [Analyzer] [Info] <== {"id":49,"method":"window/workDoneProgress/create","params":{"token":"ANALYZING"},"jsonrpc":"2.0"}
[上午11:09:12] [Analyzer] [Info] <== Content-Length: 141
Content-Type: application/vscode-jsonrpc; charset=utf-8
```

**Comment by DanTup** [comment]
I don't think there's enough information in the log to tell what's happening. It shows the client making a lot of requests (formatting, foldingRange, codeAction, etc.) none of which are responded to.

Can you reliably reproduce this? Could you you try enabling the analyzer log (see https://dartcode.org/docs/logging/#analyzer) and emailing a larger log to me at logs@dartcode.org? (note: the log will contain parts of your source code - be sure to remove anything sensitive before sending).

Thanks!

**Comment by pd4d10** [comment]
Hi, I'm trying to build this extension on my local machine. Following [this guide](https://github.com/Dart-Code/Dart-Code/blob/master/CONTRIBUTING.md#cloning-and-running-dart-code), I got stuck here:

> You may see a warning in the top of the screen telling you the extension has been overwritten - this is normal

I didn't see the warning, and instead:

![image](https://user-images.githubusercontent.com/9524411/127862860-8c3f6580-c674-4a41-8ad3-da3f6c9cf56a.png)

Has this happened before?

**Comment by DanTup** [comment]
@pd4d10 that's normal to see - VS Code gets a little confused when the version of the extension it is running (in this case, from your Dart-Code checkout) is not the one from the marketplace (it assumes it's because you've updated it and it needs to restart).

You can ignore that, and it should be running from your source version. I'm not sure I've seen the other warning recently, perhaps VS Code no longer shows it because it was a little pointless.

**Comment by pd4d10** [comment]
OK. Thanks for the guidance.

I guess I've found the issue reason. It's caused by the Dart LSP itself, which responses very slow. After switching to the latest Dart version (by hardcode in the extension code base), it works fine.

But there seems no configuration for normal users to override the LSP Dart version. In Flutter projects, Dart included in the Fuchsia and Flutter SDK will always have the highest priority:

https://github.com/Dart-Code/Dart-Code/blob/a8eb442294f66d7919af176e5618f3ab4d9cf551/src/extension/sdk/utils.ts#L297-L305

**Comment by pd4d10** [comment]
I moved line 304 `config.sdkPath` up to the first, and then specify it to the correct Dart path in the settings to solve this issue.

**Comment by DanTup** [comment]
> In Flutter projects, Dart included in the Fuchsia and Flutter SDK will always have the highest priority:

This is deliberate. The code needs to be analyzed using the same version of the SDK as will be used to run the code, otherwise there will be a mismatch between what the editor shows and what's available during compilation. We used to allow this, but it caused a lot of confusion.

If you need to get a later Dart SDK for Flutter development, you should use a more recent Flutter branch.

I'm not sure exactly what has fixed this, though there should be many improvements in the latest versions. I presume if you try with a newer Flutter branch (and don't override the Dart SDK location) the issue remains solved (and is therefore likely fixed in the SDK)?

**Comment by pd4d10** [comment]
> if you try with a newer Flutter branch 

Yeah, it should be the correct way, but the thing is that I'm using a customized Flutter version by our infra team, which may cost lots of work to upgrade

It makes sense that Fuchsia/Flutter SDK goes first. Closing
