### ISSUE TITLE
Exception while "Extract Widget"

### ISSUE THREAD

**Issue by kika** [Dart-Code/Dart-Code#3520]
Received exception from dartcode while trying to extract widget from build method.

I was trying to extract `Padding(...)` as a separate widget from the following code:

```dart
  Widget build(BuildContext ctx) {
    final doc = documents[currentPage];
    return Dialog(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 8.0),
            child: Text(
              'Review document ${currentPage+1} of $numPages'
              ' ${documentTypeToString(doc.type)}'
              ' "${doc.description}"',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
          ),
          // Many many more widgets
        ]
      ),
    );
  }
```

Selected the `Padding(...)` call, opened context menu, selected `Extract Widget`, gave new widget a name and received the following in the Output tab

<details>
  <summary>Exception</summary>

```[Error - 2:21:45 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 2:21:45 PM] An error occurred while handling textDocument/codeAction request: type 'ArgumentListImpl' is not a subtype of type 'Expression'
#0      AddNullCheck.compute (package:analysis_server/src/services/correction/dart/add_null_check.dart:43:7)
#1      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1767:24)
#2      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1762:25)
#3      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1789:24)
#4      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1724:11)
#5      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:185:35)
#6      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:311:44)
#7      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:268:7)
#8      CodeActionHandler.handle.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:95:18)
#9      ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:257:12)
#10     CodeActionHandler.handle.<anonymous closure>.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:92:26)
#11     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:257:12)
#12     CodeActionHandler.handle.<anonymous closure> (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:91:26)
#13     ErrorOr.mapResult (package:analysis_server/lsp_protocol/protocol_special.dart:257:12)
#14     CodeActionHandler.handle (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:88:17)
<asynchronous suspension>
#15     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:187:22)
<asynchronous suspension>
#16     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:302:26)
<asynchronous suspension>

[Error - 3:36:26 PM] Request workspace/executeCommand failed.
  Message: Reference to an enclosing class method cannot be extracted.
  Code: -32011
``` 
</details>

In vscode 1.59 I don't see the stack only the last error is shown.

**Expected behavior**
No exceptions, and extracted widget

**Versions (please complete the following information):**
 - VS Code version: 1.58.2 and 1.59
 - Dart extension version: 3.25.1
 - Dart/Flutter SDK version: 2.13.4/2.2.3

**Comment by DanTup** [comment]
I've not been able to reproduce it with the code above - are you able to reproduce it and share the exact full file and exact steps you took?

@bwilkerson I checked v2.13.4 of this file https://github.com/dart-lang/sdk/blob/2.13.4/pkg/analysis_server/lib/src/services/correction/dart/add_null_check.dart but I'm not sure how line 43 could cause this (as far as I can tell, an `ArgumentListImpl` would not satisfy `is FunctionExpressionInvocation`) - any ideas?

**Comment by bwilkerson** [comment]
The test on line 42 is for `coveredNodeParent`, not `coveredNode`, so it's perfectly possible for the parent to be a function expression invocation and for the covered node to be the argument list for that expression. The good news is that this has already been fixed on master, so it will likely be fixed in the next release.

**Comment by DanTup** [comment]
> The test on line 42 is for `coveredNodeParent`, not `coveredNode`

Aha, I missed that - thanks! Yep, looks fixed (`coveredNode is Expression` was added [in this change](https://github.com/dart-lang/sdk/commit/bbbe5bfc87b4346eba815ba7898ec0bfb5ddf66c#diff-96a116f6f2ebdcd69d582ecf020ff7830b8b4a136d1ffdcb618b55c4b38aa911R42)), so closing this as fixed. Thanks!
