### ISSUE TITLE
LateInitializationError: Local 'result' has not been initialized.

### ISSUE THREAD

**Issue by 6N5tr** [Dart-Code/Dart-Code#3548]
This error is happaning to me on VsCode when install apk on release mode on a physical device. On simulation i dont have problems.

Notification:

Showing M2003J15SC logs:
I/flutter (10118): LateInitializationError: Local 'result' has not been initialized.
I/flutter (10118): #0      LateError._throwLocalNotInitialized (dart:_internal-patch/internal_patch.dart:203)
I/flutter (10118): #1      StateNotifier.debugState (package:state_notifier/state_notifier.dart:189)
I/flutter (10118): #2      _IntroViewState.build.<anonymous closure> (package:riverpoderror/src/intro_view.dart:121)
I/flutter (10118): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989)
I/flutter (10118): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198)
I/flutter (10118): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608)
I/flutter (10118): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296)
I/flutter (10118): #7      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:230)
I/flutter (10118): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563)
I/flutter (10118): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94)
I/flutter (10118): #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139)
I/flutter (10118): #11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400)
I/flutter (10118): #12     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137)
I/flutter (10118): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123)
I/flutter (10118): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:440)
I/flutter (10118): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420)
I/flutter (10118): #16     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278)
I/flutter (10118): #17     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374)
I/flutter (10118): #18     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338)
I/flutter (10118): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296)
I/flutter (10118): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279)
I/flutter (10118): #24     _invoke1 (dart:ui/hooks.dart:185)
I/flutter (10118): #25     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293)
I/flutter (10118): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:98)

**Comment by DanTup** [comment]
It appears your code is trying to access `debugState` in `package:state_notifier`. The [dartdoc on `debugState`](https://github.com/rrousselGit/state_notifier/blob/4822bc5bb274acc1b0ba73995f2716ba4233f7be/packages/state_notifier/lib/state_notifier.dart#L183) says:

```
  /// A development-only way to access [state] outside of [StateNotifier].
  ///
  /// The only difference with [state] is that [debugState] is not "protected".\
  /// Will not work in release mode.
  ///
  /// This is useful for tests.
```

So I believe this is working as intended. If you believe it should work, it would need to be filed at https://github.com/rrousselGit/state_notifier since it's not related to the VS Code extension.

Hope this makes sense!

**Comment by 6N5tr** [comment]
> It appears your code is trying to access `debugState` in `package:state_notifier`. The [dartdoc on `debugState`](https://github.com/rrousselGit/state_notifier/blob/4822bc5bb274acc1b0ba73995f2716ba4233f7be/packages/state_notifier/lib/state_notifier.dart#L183) says "Will not work in release mode":
> 
> ```
>   /// A development-only way to access [state] outside of [StateNotifier].
>   ///
>   /// The only difference with [state] is that [debugState] is not "protected".\
>   /// Will not work in release mode.
>   ///
>   /// This is useful for tests.
> ```
> 
> So I believe this is working as intended. If you believe it should work, it would need to be filed at https://github.com/rrousselGit/state_notifier since it's not related to the VS Code extension.
> 
> Hope this makes sense!

Thanks. A lot! It has a lot of sense!

**Comment by etekumoses** [comment]
i am getting this error still what is the way forwards works fine on my simulator and debug mode but on release doesnt

**Comment by DanTup** [comment]
@etekumoses it's difficult to advise without any stack trace and code. You should review any variables where you are using `late` and see if it's possible you are trying to read them before they are set. When you add `late` to a variable, you are promising to set the variable before anything tries to access it and this error occurs if that's not true.
