### ISSUE TITLE
[LSP] Error while trying to define InputDecoration properties

### ISSUE THREAD

**Issue by mo-ah-dawood** [Dart-Code/Dart-Code#3557]
**Describe the bug**
Error while trying to define InputDecoration properties

the code i trying to write

```dart
   TextFormField(
         decoration: InputDecoration(
               prefixIcon: Icon(Icons.title_rounded),
               border: InputBorder.none,
         ),
   ),
```

```
[Error - 4:51:51 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 4:51:51 PM] An error occurred while handling textDocument/codeAction request: Bad state: Cannot access an invalid result
#0      InvalidResult.result (package:analysis_server/src/services/correction/fix/data_driven/accessor.dart:83:24)
#1      CodeFragment.writeOn (package:analysis_server/src/services/correction/fix/data_driven/value_generator.dart:62:42)
#2      TemplateVariable.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:154:15)
#3      CodeTemplate.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:41:17)
#4      ModifyParameters.apply.writeArgument (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:108:23)
#5      ModifyParameters.apply.writeInsertionRange (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:131:13)
#6      ModifyParameters.apply.<anonymous closure> (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:202:13)
#7      DartFileEditBuilderImpl.addInsertion.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1295:41)
#8      FileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:431:16)
#9      DartFileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1294:13)
#10     ModifyParameters.apply (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:201:19)
#11     DataDrivenFix.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/data_driven.dart:103:20)
#12     ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:118:20)
<asynchronous suspension>
#13     DataDrivenFix.compute (package:analysis_server/src/services/correction/dart/data_driven.dart:101:5)
<asynchronous suspension>
#14     FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1290:9)
<asynchronous suspension>
#15     FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1316:13)
<asynchronous suspension>
#16     FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1245:5)
<asynchronous suspension>
#17     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:191:19)
<asynchronous suspension>
#18     CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:357:23)
<asynchronous suspension>
#19     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#20     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:306:21)
<asynchronous suspension>
#21     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:189:22)
<asynchronous suspension>
#22     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:330:26)
<asynchronous suspension>

[Error - 4:51:52 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 4:51:52 PM] An error occurred while handling textDocument/codeAction request: Bad state: Cannot access an invalid result
#0      InvalidResult.result (package:analysis_server/src/services/correction/fix/data_driven/accessor.dart:83:24)
#1      CodeFragment.writeOn (package:analysis_server/src/services/correction/fix/data_driven/value_generator.dart:62:42)
#2      TemplateVariable.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:154:15)
#3      CodeTemplate.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:41:17)
#4      ModifyParameters.apply.writeArgument (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:108:23)
#5      ModifyParameters.apply.writeInsertionRange (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:131:13)
#6      ModifyParameters.apply.<anonymous closure> (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:202:13)
#7      DartFileEditBuilderImpl.addInsertion.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1295:41)
#8      FileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:431:16)
#9      DartFileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1294:13)
#10     ModifyParameters.apply (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:201:19)
#11     DataDrivenFix.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/data_driven.dart:103:20)
#12     ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:118:20)
<asynchronous suspension>
#13     DataDrivenFix.compute (package:analysis_server/src/services/correction/dart/data_driven.dart:101:5)
<asynchronous suspension>
#14     FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1290:9)
<asynchronous suspension>
#15     FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1316:13)
<asynchronous suspension>
#16     FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1245:5)
<asynchronous suspension>
#17     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:191:19)
<asynchronous suspension>
#18     CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:357:23)
<asynchronous suspension>
#19     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#20     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:306:21)
<asynchronous suspension>
#21     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:189:22)
<asynchronous suspension>
#22     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:330:26)
<asynchronous suspension>

[Error - 4:53:15 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 4:53:15 PM] An error occurred while handling textDocument/codeAction request: Bad state: Cannot access an invalid result
#0      InvalidResult.result (package:analysis_server/src/services/correction/fix/data_driven/accessor.dart:83:24)
#1      CodeFragment.writeOn (package:analysis_server/src/services/correction/fix/data_driven/value_generator.dart:62:42)
#2      TemplateVariable.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:154:15)
#3      CodeTemplate.writeOn (package:analysis_server/src/services/correction/fix/data_driven/code_template.dart:41:17)
#4      ModifyParameters.apply.writeArgument (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:108:23)
#5      ModifyParameters.apply.writeInsertionRange (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:131:13)
#6      ModifyParameters.apply.<anonymous closure> (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:202:13)
#7      DartFileEditBuilderImpl.addInsertion.<anonymous closure> (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1295:41)
#8      FileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:431:16)
#9      DartFileEditBuilderImpl.addInsertion (package:analyzer_plugin/src/utilities/change_builder/change_builder_dart.dart:1294:13)
#10     ModifyParameters.apply (package:analysis_server/src/services/correction/fix/data_driven/modify_parameters.dart:201:19)
#11     DataDrivenFix.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/data_driven.dart:103:20)
#12     ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:118:20)
<asynchronous suspension>
#13     DataDrivenFix.compute (package:analysis_server/src/services/correction/dart/data_driven.dart:101:5)
<asynchronous suspension>
#14     FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1290:9)
<asynchronous suspension>
#15     FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1316:13)
<asynchronous suspension>
#16     FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1245:5)
<asynchronous suspension>
#17     DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:191:19)
<asynchronous suspension>
#18     CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:357:23)
<asynchronous suspension>
#19     Future.wait.<anonymous closure> (dart:async/future.dart)
<asynchronous suspension>
#20     CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:306:21)
<asynchronous suspension>
#21     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:189:22)
<asynchronous suspension>
#22     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:330:26)
<asynchronous suspension>
```

**Versions (please complete the following information):**
 - VS Code version: 1.60.0
 - Operating system : MacOs big sur 11.5.2
 - Dart extension version: 3.26.0
 - Dart/Flutter SDK version:  2.14.0 / 2.5.0

**Comment by DanTup** [comment]
@mo-ah-dawood can you provide a complete code sample that reproduce this? I tried adding that code to a Flutter app but wasn't able to trigger it myself (also using 2.5.0).

It does look like an analysis server issue though, so it would be best raised with a repro at https://github.com/dart-lang/sdk/issues (please post a link back here so anyone else that hits this can find the related SDK issue). Thanks!

**Comment by mo-ah-dawood** [comment]
#https://github.com/dart-lang/sdk/issues/47203

**Comment by DanTup** [comment]
Thanks!
