### ISSUE TITLE
Request textDocument/codeAction failed.

### ISSUE THREAD

**Issue by ashokavarthanan** [Dart-Code/Dart-Code#3781]
Issue Type: <b>Bug</b>

[Error - 10:42:46 am] Request textDocument/codeAction failed.
  Message: Invalid file path
  Code: -32003 
k:\getxdemo\lib\main.dart
[Error - 10:42:46 am] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
k:\getxdemo\lib\main.dart
[Error - 10:44:40 am] Request textDocument/hover failed.
  Message: Invalid file path
  Code: -32003 
k:\getxdemo\lib\main.dart
[Error - 10:44:41 am] Request textDocument/documentHighlight failed.
  Message: Invalid file path
  Code: -32003 
k:\getxdemo\lib\main.dart
\\********************************\\
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19041.329], locale
    en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2017 15.9.36)
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default      components
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.2)
[√] Connected device (3 available)

Extension version: 3.32.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.30GB free)|
|Process Argv|K:\\getxdemo --crash-reporter-id bf14e4a0-385d-429e-b1fa-6fbf398f59e9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30422343
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dsc:30421290
pythonvs932:30410667
vscop804:30404766
vscop453:30404998
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by ashokavarthanan** [comment]
I tried ..
Fully uninstall and remove all extension folder and caches...
Fresh install VS code and install only "Dart" extension.. Still error occur.
Note : The first error occur @ 14.01.2022 -: 19:00:00 GMT.+5.30 (when I worked Suddenly Showed this Error). 
           Before No Error I seen..

**Comment by ashokavarthanan** [comment]
//**   Developer Console  **//
log.ts:313   
ERR Invalid file path: Error: Invalid file path
    at handleResponse (c:\Users\user\.vscode\extensions\dart-code.dart-code-3.32.0\out\dist\extension.js:27951:48)
    at processMessageQueue (c:\Users\user\.vscode\extensions\dart-code.dart-code-3.32.0\out\dist\extension.js:27766:17)
    at Immediate.<anonymous> (c:\Users\user\.vscode\extensions\dart-code.dart-code-3.32.0\out\dist\extension.js:27750:13)
    at processImmediate (internal/timers.js:461:21)

**Comment by ashokavarthanan** [comment]
This is *** Major Problem ***  
I cannot work this problem.... 
Because..  All related Flies, Classes, Functions, Variables and Everything ***not working Click to Go***

**Comment by ashokavarthanan** [comment]
***Log***
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.32.0
Flutter extension: 3.32.0 (activated)

App: Visual Studio Code
Version: 1.63.2
Platform: win

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: C:\flutter\bin\cache\dart-sdk
    Ver: 2.15.1
Flutter SDK:
    Loc: C:\flutter
    Ver: 2.8.1

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General, Analyzer, CommandProcesses, DartTest, DAP, VmService, DevTools, FlutterDaemon, FlutterRun, FlutterTest, WebDaemon

Sat Jan 15 2022 [11:55:17 GMT+0530 (India Standard Time)] Log file started
[11:55:24 am] [Analyzer] [Info] ==> Content-Length: 164
[11:55:24 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":6,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///k%3A/getxdemo/lib/main.dart"},"position":{"line":16,"character":13}}}
[11:55:24 am] [Analyzer] [Info] ==> Content-Length: 62
[11:55:24 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":6}}
[11:55:24 am] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:24 am] [Analyzer] [Info] <== {"id":5,"method":"window/workDoneProgress/create","params":{"token":"ANALYZING"},"jsonrpc":"2.0"}
[11:55:24 am] [Analyzer] [Info] ==> Content-Length: 38
[11:55:24 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":5,"result":null}
[11:55:24 am] [Analyzer] [Info] <== Content-Length: 116
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:24 am] [Analyzer] [Info] <== {"id":6,"jsonrpc":"2.0","error":{"code":-32003,"message":"Invalid file path","data":"k:\\getxdemo\\lib\\main.dart"}}
[11:55:24 am] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}},"jsonrpc":"2.0"}Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}},"jsonrpc":"2.0"}
[11:55:24 am] [Analyzer] [Info] ==> Content-Length: 176
[11:55:24 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":7,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///k%3A/getxdemo/lib/main.dart"},"position":{"line":16,"character":12}}}
[11:55:25 am] [Analyzer] [Info] ==> Content-Length: 238
[11:55:25 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":8,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///k%3A/getxdemo/lib/main.dart"},"range":{"start":{"line":16,"character":12},"end":{"line":16,"character":12}},"context":{"diagnostics":[]}}}
[11:55:25 am] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:25 am] [Analyzer] [Info] <== {"id":6,"method":"window/workDoneProgress/create","params":{"token":"ANALYZING"},"jsonrpc":"2.0"}
[11:55:25 am] [Analyzer] [Info] <== Content-Length: 116
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:25 am] [Analyzer] [Info] ==> Content-Length: 38
[11:55:25 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":6,"result":null}
[11:55:25 am] [Analyzer] [Info] <== {"id":7,"jsonrpc":"2.0","error":{"code":-32003,"message":"Invalid file path","data":"k:\\getxdemo\\lib\\main.dart"}}
[11:55:25 am] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}},"jsonrpc":"2.0"}
[11:55:25 am] [Analyzer] [Info] <== Content-Length: 116
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:25 am] [Analyzer] [Info] <== {"id":8,"jsonrpc":"2.0","error":{"code":-32003,"message":"Invalid file path","data":"k:\\getxdemo\\lib\\main.dart"}}
[11:55:25 am] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}},"jsonrpc":"2.0"}
[11:55:27 am] [Analyzer] [Info] ==> Content-Length: 164
[11:55:27 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":9,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///k%3A/getxdemo/lib/main.dart"},"position":{"line":16,"character":12}}}
[11:55:27 am] [Analyzer] [Info] ==> Content-Length: 62
[11:55:27 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":9}}
[11:55:27 am] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:27 am] [Analyzer] [Info] <== {"id":7,"method":"window/workDoneProgress/create","params":{"token":"ANALYZING"},"jsonrpc":"2.0"}
[11:55:27 am] [Analyzer] [Info] ==> Content-Length: 38
[11:55:27 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":7,"result":null}
[11:55:27 am] [Analyzer] [Info] <== Content-Length: 116
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:27 am] [Analyzer] [Info] <== {"id":9,"jsonrpc":"2.0","error":{"code":-32003,"message":"Invalid file path","data":"k:\\getxdemo\\lib\\main.dart"}}
[11:55:27 am] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}},"jsonrpc":"2.0"}Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}},"jsonrpc":"2.0"}
[11:55:28 am] [Analyzer] [Info] ==> Content-Length: 165
[11:55:28 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":10,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///k%3A/getxdemo/lib/main.dart"},"position":{"line":18,"character":23}}}
[11:55:28 am] [Analyzer] [Info] ==> Content-Length: 63
[11:55:28 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":10}}
[11:55:28 am] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:28 am] [Analyzer] [Info] <== {"id":8,"method":"window/workDoneProgress/create","params":{"token":"ANALYZING"},"jsonrpc":"2.0"}
[11:55:28 am] [Analyzer] [Info] ==> Content-Length: 38
[11:55:28 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":8,"result":null}
[11:55:28 am] [Analyzer] [Info] <== Content-Length: 117
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:28 am] [Analyzer] [Info] <== {"id":10,"jsonrpc":"2.0","error":{"code":-32003,"message":"Invalid file path","data":"k:\\getxdemo\\lib\\main.dart"}}
[11:55:28 am] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}},"jsonrpc":"2.0"}Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}},"jsonrpc":"2.0"}
[11:55:28 am] [Analyzer] [Info] ==> Content-Length: 165
[11:55:28 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":11,"method":"textDocument/hover","params":{"textDocument":{"uri":"file:///k%3A/getxdemo/lib/main.dart"},"position":{"line":18,"character":24}}}
[11:55:28 am] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:28 am] [Analyzer] [Info] <== {"id":9,"method":"window/workDoneProgress/create","params":{"token":"ANALYZING"},"jsonrpc":"2.0"}Content-Length: 117
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:28 am] [Analyzer] [Info] <== {"id":11,"jsonrpc":"2.0","error":{"code":-32003,"message":"Invalid file path","data":"k:\\getxdemo\\lib\\main.dart"}}
[11:55:28 am] [Analyzer] [Info] ==> Content-Length: 38
[11:55:28 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":9,"result":null}
[11:55:28 am] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}},"jsonrpc":"2.0"}Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:28 am] [Analyzer] [Info] <== {"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}},"jsonrpc":"2.0"}
[11:55:28 am] [Analyzer] [Info] ==> Content-Length: 170
[11:55:28 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":12,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///k%3A/getxdemo/lib/main.dart"},"position":{"line":18,"character":25}}}
[11:55:29 am] [Analyzer] [Info] <== Content-Length: 98
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:29 am] [Analyzer] [Info] <== {"id":10,"method":"window/workDoneProgress/create","params":{"token":"ANALYZING"},"jsonrpc":"2.0"}
[11:55:29 am] [Analyzer] [Info] <== Content-Length: 37
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":12,"jsonrpc":"2.0","result":[]}
[11:55:29 am] [Analyzer] [Info] ==> Content-Length: 39
[11:55:29 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":10,"result":null}
[11:55:29 am] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:29 am] [Analyzer] [Info] <== {"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}},"jsonrpc":"2.0"}
[11:55:29 am] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}},"jsonrpc":"2.0"}
[11:55:29 am] [Analyzer] [Info] ==> Content-Length: 177
[11:55:29 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":13,"method":"textDocument/documentHighlight","params":{"textDocument":{"uri":"file:///k%3A/getxdemo/lib/main.dart"},"position":{"line":18,"character":25}}}
[11:55:29 am] [Analyzer] [Info] ==> Content-Length: 170
[11:55:29 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":14,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///k%3A/getxdemo/lib/main.dart"},"position":{"line":18,"character":25}}}
[11:55:29 am] [Analyzer] [Info] <== Content-Length: 98
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:29 am] [Analyzer] [Info] <== {"id":11,"method":"window/workDoneProgress/create","params":{"token":"ANALYZING"},"jsonrpc":"2.0"}
[11:55:29 am] [Analyzer] [Info] ==> Content-Length: 39
[11:55:29 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":11,"result":null}
[11:55:29 am] [Analyzer] [Info] <== Content-Length: 117
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":13,"jsonrpc":"2.0","error":{"code":-32003,"message":"Invalid file path","data":"k:\\getxdemo\\lib\\main.dart"}}
[11:55:29 am] [Analyzer] [Info] ==> Content-Length: 239
[11:55:29 am] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":15,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///k%3A/getxdemo/lib/main.dart"},"range":{"start":{"line":18,"character":25},"end":{"line":18,"character":25}},"context":{"diagnostics":[]}}}
[11:55:30 am] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:30 am] [Analyzer] [Info] <== {"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}},"jsonrpc":"2.0"}
[11:55:30 am] [Analyzer] [Info] <== Content-Length: 93
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"end"}},"jsonrpc":"2.0"}Content-Length: 37
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":14,"jsonrpc":"2.0","result":[]}
[11:55:30 am] [Analyzer] [Info] <== Content-Length: 117
Content-Type: application/vscode-jsonrpc; charset=utf-8
[11:55:30 am] [Analyzer] [Info] <== {"id":15,"jsonrpc":"2.0","error":{"code":-32003,"message":"Invalid file path","data":"k:\\getxdemo\\lib\\main.dart"}}
Sat Jan 15 2022 [11:55:37 GMT+0530 (India Standard Time)] Log file ended

**Comment by ashokavarthanan** [comment]
Finally Flutter Downgrade to Version  
Flutter 2.5.3
Dart 2.14.4
Errors gone.

**Comment by DanTup** [comment]
Sorry for the delay. Is it possible you could try enabling the [analysis server instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) and reproduce the issue? It may include a detailed exception that helps understand what the problem is.

Thanks!

**Comment by kaciula** [comment]
@DanTup I'm also seeing this starting today and there is nothing I can do to make it work again. 

I moved fileA to a different folder by drag and drop in VS Code. I have fileB that has a reference to fileA. When I open fileB, I get the "Request textDocument/codeAction failed. Message: Invalid file path Code: -32003" message. fileB is device.dart in the logs.

If I revert the file move, things work ok. But it's frustrating because I cannot do any refactoring AT ALL because the issue pops up again and again on every file move.

Is there something I can do to work around this bug?

[Dart-Code-Log-2022-01-02 19-00-31.txt](https://github.com/Dart-Code/Dart-Code/files/7980474/Dart-Code-Log-2022-01-02.19-00-31.txt)

**Comment by DanTup** [comment]
@kaciula can you enable the instrumentation log noted in the comment above yours, restart VS Code and then try to reproduce to se whether there's a more detailed error in there?

The "invalid file path" message can sometimes mean "the parser throw an error parsing this file", and usually that will be recorded in the instrumentation log.

**Comment by kaciula** [comment]
@DanTup I don't understand. I've already attached the log to my previous comment. I don't know how to generate even more detailed logs. Please explain.

Playing around with this issue, it seems it happens after I drag&drop multiple files/folders. The analysis server thinks some of the files/folders still exist in the previous location but also in the new one. 

On the other hand, if I drag&drop each file one by one, I don't have this problem.

**Comment by DanTup** [comment]
@kaciula the log you attached is collected on the client, but the server log contains a little more. The server log is collected using the `dart.analyzerInstrumentationLogFile` setting - see the link above for more info.

> it seems it happens after I drag&drop multiple files/folders

Ah, that's interesting to know. Do you have some exact steps to trigger it on a clean project that I can try? Thanks!

**Comment by KhalillHussein** [comment]
For everyone, who stuck on the error. I find a solution. For me, the error related to this piece of code: `[].twn<double>`. I used an extension method `twn` on the list in one of the project files. After that I've seen the error for every .dart files in my project folder. I think, that the specific code constructions is the source of that problem.

**Comment by DanTup** [comment]
@KhalillHussein are you able to share some code that reproduces this? It sounds like an error during parsing, but I was unable to reproduce it with this:

```dart
extension ListExtension<T> on List<T> {
  twn<T>() => null;
}

final a = [].twn<double>();

```

**Comment by DanTup** [comment]
@KhalillHussein thanks! I've filed https://github.com/dart-lang/sdk/issues/48396 in the SDK about that one.

**Comment by DanTup** [comment]
This was fixed in the Dart SDK in the issue above, and the fix will be in an upcoming Dart SDK release. Thanks!

**Comment by KhalillHussein** [comment]
@DanTup excellent! I'm glad to hear that.

**Comment by DanTup** [comment]
Oops, that last issue was not related to the original issue here.

@ashokavarthanan @kaciula are you still seeing this? If so, are you able to capture [analyzer instrumentation logs](https://dartcode.org/docs/logging/#analyzer-instrumentation) when reproducing the issue?

**Comment by ashokavarthanan** [comment]
> Oops, that last issue was not related to the original issue here.
> 
> @ashokavarthanan @kaciula are you still seeing this? If so, are you able to capture [analyzer instrumentation logs](https://dartcode.org/docs/logging/#analyzer-instrumentation) when reproducing the issue?

Sorry!! about this issue.  i already put all logs, currently i cannot do at this time.

**Comment by DanTup** [comment]
Understood. If you get time, the required logs are the [analyzer instrumentation logs](https://dartcode.org/docs/logging/#analyzer-instrumentation) - this is slightly different to the logs that have been included above.

In an upcoming update to the Dart SDK, the error message ("invalid file path") should be a little more specific which should also help track down these kinds of issue.

**Comment by OmarShawky1** [comment]
This program pertains until this day.

**Comment by DanTup** [comment]
@OmarShawky1 please file a new issue with more details about when you're seeing this, and include the versions of your Dart/Flutter SDKs and the Dart extension. Thanks!
