### ISSUE TITLE
"Invalid file path" on Windows after paths are printed to the terminal

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3794]
See https://github.com/Dart-Code/Dart-Code/issues/3065#issuecomment-1016492148 and the following comment from @thanh-mel.

VS Code may be triggering didOpen even without clicking the link in the terminal?

**Comment by DanTup** [comment]
@thanh-mel I'm actually unable to reproduce this on Windows. I made a widget that throws in its `build` method so I got the same output as you, which included a `file:///` URI to the file. VS Code did not trigger an open event for it, even if I hovered over it or held down Ctrl (so that it was underlined).

Could you possibly:

- test if it occurs with all other extensions disabled (if so, please let me know which you have that might be triggering it)
- check whether your active terminal is PowerShell or CMD (and test the other one to see if it matters)
- check whether it reproduces in a simple new project created with **Flutter: New Project** if you just ad `throw 'a';` at the top of the `build()` method?

Thanks!

**Comment by thanh-mel** [comment]
@DanTup ok will do it and get back to you shortly.

**Comment by thanh-mel** [comment]
Hi @DanTup, I managed to reproduce the error with a brand new simple project. Below are the steps I follow:

- Create new flutter app using this command line `flutter create myapp -t skeleton`. This will scaffold a simple app for me.
- Go edit this file `sample_item_list_view.dart` by adding this line `final String? title = null;` just before the `build()` method then update this `title: Text(title!),` for the AppBar's title. Below is the full source:

```
import 'package:flutter/material.dart';

import '../settings/settings_view.dart';
import 'sample_item.dart';
import 'sample_item_details_view.dart';

/// Displays a list of SampleItems.
class SampleItemListView extends StatelessWidget {
  const SampleItemListView({
    Key? key,
    this.items = const [SampleItem(1), SampleItem(2), SampleItem(3)],
  }) : super(key: key);

  static const routeName = '/';

  final List<SampleItem> items;

  final String? title = null;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title!),
        actions: [
          IconButton(
            icon: const Icon(Icons.settings),
            onPressed: () {
              // Navigate to the settings page. If the user leaves and returns
              // to the app after it has been killed while running in the
              // background, the navigation stack is restored.
              Navigator.restorablePushNamed(context, SettingsView.routeName);
            },
          ),
        ],
      ),

      // To work with lists that may contain a large number of items, it’s best
      // to use the ListView.builder constructor.
      //
      // In contrast to the default ListView constructor, which requires
      // building all Widgets up front, the ListView.builder constructor lazily
      // builds Widgets as they’re scrolled into view.
      body: ListView.builder(
        // Providing a restorationId allows the ListView to restore the
        // scroll position when a user leaves and returns to the app after it
        // has been killed while running in the background.
        restorationId: 'sampleItemListView',
        itemCount: items.length,
        itemBuilder: (BuildContext context, int index) {
          final item = items[index];

          return ListTile(
              title: Text('SampleItem ${item.id}'),
              leading: const CircleAvatar(
                // Display the Flutter Logo image asset.
                foregroundImage: AssetImage('assets/images/flutter_logo.png'),
              ),
              onTap: () {
                // Navigate to the details page. If the user leaves and returns to
                // the app after it has been killed while running in the
                // background, the navigation stack is restored.
                Navigator.restorablePushNamed(
                  context,
                  SampleItemDetailsView.routeName,
                );
              });
        },
      ),
    );
  }
}
```

- Run `flutter run` and null exception would show on the real device.
- Check the Terminal panel, you would see the following output as below:
```

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building SampleItemListView(dirty):
Null check operator used on a null value

The relevant error-causing widget was:
  SampleItemListView SampleItemListView:file:///C:/src/apps/exercises/myapp/lib/src/app.dart:76:34

When the exception was thrown, this was the stack:
#0      SampleItemListView.build (package:myapp/src/sample_feature/sample_item_list_view.dart:24:26)
#1      StatelessElement.build (package:flutter/src/widgets/framework.dart:4662:28)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566:5)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
...     Normal element mounting (169 frames)
#174    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#175    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#176    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (338 frames)
#514    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#515    Element.updateChild (package:flutter/src/widgets/framework.dart:3380:20)
#516    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#517    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763:11)
#518    Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
#519    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578:33)
#520    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#521    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#522    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#523    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#524    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

- Hover this line `file:///C:/src/apps/exercises/myapp/lib/src/app.dart:76:34` and press Ctrl-Click, the error will happen in the Output panel as below:
```
[Error - 11:56:12 pm] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
\src\apps\exercises\myapp\lib\src\app.dart
[Error - 11:56:54 pm] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
\src\apps\exercises\myapp\lib\src\app.dart
[Error - 11:56:56 pm] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
\src\apps\exercises\myapp\lib\src\app.dart
[Error - 11:57:14 pm] Request textDocument/documentSymbol failed.
  Message: Invalid file path
  Code: -32003 
```

- I ran `flutter run` in both PowerShell and CMD but they produced the same error, no difference.

- I also disabled all extensions but the error still happened regardless unfortunately :(.
- Below is the output of `flutter doctor`:
```
PS C:\src\apps\exercises\myapp> flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1466], locale en-AU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.2)
[√] VS Code, 64-bit edition (version 1.62.0)
[√] Connected device (3 available)

• No issues found!
PS C:\src\apps\exercises\myapp> 
```
Let me know if you need anything else.

Thanks.

**Comment by CalebQ42** [comment]
I just ran into this same issue on Arch Linux. I made some large changes by removing a custom widget and creating a replacement (EditableContents to EditContents). Now whenever I import the file I changed (`ui/editable_common.dart`) then the file I'm trying to import it into has this issue.

[Here](https://github.com/CalebQ42/SWAssistant/tree/ab672395391b242995da3e6ce7ae5d6dfa638932) is my project at the commit where I'm having the problem. In particular opening `ui/items/morality.dart` and `ui/items/obligations.dart` causes the error.

And here is my log: [dartLog.log](https://github.com/Dart-Code/Dart-Code/files/7925549/dartLog.log)

**Comment by DanTup** [comment]
@CalebQ42 I think yours has a different cause. In your logs I see this:

```
1643027061620:Ex:Analysis failed:: /home/belac/Projects/SWAssistant/lib/ui/items/characters/obligations.dart context:: exception_20220124_062421_256
Invalid argument(s):: Tried to format an error using NamedTypeImpl
#0      ErrorReporter._convertElements (package::analyzer/error/listener.dart::158::9)
#1      ErrorReporter.reportErrorForOffset (package::analyzer/error/listener.dart::105::5)
#2      ErrorReporter.reportErrorForToken (package::analyzer/error/listener.dart::123::5)
#3      ErrorVerifier._checkMixinInference (package::analyzer/src/generated/error_verifier.dart::4714::31)
#4      ErrorVerifier._checkClassInheritance (package::analyzer/src/generated/error_verifier.dart::1291::7)
#5      ErrorVerifier.visitClassDeclaration (package::analyzer/src/generated/error_verifier.dart::447::9)
#6      ClassDeclarationImpl.accept (package::analyzer/src/dart/ast/ast.dart::1494::50)
#7      NodeListImpl.accept (package::analyzer/src/dart/ast/ast.dart::7813::20)
#8      CompilationUnitImpl.visitChildren (package::analyzer/src/dart/ast/ast.dart::2105::21)
#9      RecursiveAstVisitor.visitCompilationUnit (package::analyzer/dart/ast/visitor.dart::765::10)
#10     ErrorVerifier.visitCompilationUnit (package::analyzer/src/generated/error_verifier.dart::496::11)
#11     CompilationUnitImpl.accept (package::analyzer/src/dart/ast/ast.dart::2098::50)
#12     LibraryAnalyzer._computeVerifyErrors (package::analyzer/src/dart/analysis/library_analyzer.dart::485::10)
#13     LibraryAnalyzer.analyze.<anonymous closure> (package::analyzer/src/dart/analysis/library_analyzer.dart::149::7)
#14     _LinkedHashMapMixin.forEach (dart::collection-patch/compact_hash.dart::539::8)
#15     LibraryAnalyzer.analyze (package::analyzer/src/dart/analysis/library_analyzer.dart::148::11)
#16     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package::analyzer/src/dart/analysis/driver.dart::1455::63)
#17     PerformanceLog.run (package::analyzer/src/dart/analysis/performance_logger.dart::32::15)
#18     AnalysisDriver._computeAnalysisResult (package::analyzer/src/dart/analysis/driver.dart::1431::20)
#19     AnalysisDriver.performWork (package::analyzer/src/dart/analysis/driver.dart::1055::22)
#20     AnalysisDriverScheduler._run (package::analyzer/src/dart/analysis/driver.dart::2137::24)
```

This looks like a bug in the analyzer. Could you file an issue at https://github.com/dart-lang/sdk and include the log from above (or at least the error I included here) and link to the repo/commit? Thanks!

**Comment by DanTup** [comment]
@thanh-mel 

> Hover this line `file:///C:/src/apps/exercises/myapp/lib/src/app.dart:76:34` and press Ctrl-Click, the error will happen in the Output panel as below:

Ah, thanks for confirming you're clicking on the link. I thought from your previous comment it was just happening without a click. In that case, this is https://github.com/microsoft/vscode/issues/108660. The issue is that VS Code is opening the file with a bad path (missing a drive letter) and passing it to the extension. Working around this is tricky because it gets sent to the LSP server. It will really need fixing in VS Code.

However, you may be able to avoid this by running your Flutter app using the built-in functionality rather than the terminal (the `Run` menu). This should avoid the issue because paths are handled differently in the Debug Console output, and it'll also let you use breakpoints and other debugging functionality (and let you change device using the status bar).

**Comment by DanTup** [comment]
I think this was been fixed in the latest version of VS Code (see https://github.com/dart-lang/sdk/issues/47534#issuecomment-1038867784).
