### ISSUE TITLE
Dart Analysis crashed - Null check operator used on a Null value

### ISSUE THREAD

**Issue by TiffaaMC** [Dart-Code/Dart-Code#4023]
**Describe the bug**
Everytime I restart the analysis server or even VSCode, it crashes because of `Request textDocument/codeAction failed`.

**To Reproduce**
No idea, probably by having a bad super key parameter constructor + not sorted above other variables, then trying to Quick Fix it?

**Expected behavior**
No crash.

**Error Message**
```
[Error - 10:47:08] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 10:47:08] An error occurred while handling textDocument/codeAction request: Null check operator used on a null value
#0      SortConstructorFirst.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/sort_constructor_first.dart:35:40)
#1      ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:144:20)
<asynchronous suspension>
#2      SortConstructorFirst.compute (package:analysis_server/src/services/correction/dart/sort_constructor_first.dart:33:5)
<asynchronous suspension>
#3      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1416:9)
<asynchronous suspension>
#4      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1429:9)
<asynchronous suspension>
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1371:5)
<asynchronous suspension>
#6      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:215:19)
<asynchronous suspension>
#7      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:356:23)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
<asynchronous suspension>
#9      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:310:21)
<asynchronous suspension>
#10     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:196:22)
<asynchronous suspension>
#11     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:342:26)
<asynchronous suspension>
```

**Please complete the following information:**
 - Operating System and version: Windows 10
 - VS Code version: 1.61.1
 - Dart extension version: 3.42.1
 - Dart/Flutter SDK version: 3.0.2

**Comment by TiffaaMC** [comment]
### Temporary fix

Commenting `sort_constructors_first` in `analysis_server.yaml`

**Comment by DanTup** [comment]
Thanks for the report! Looks like this was found and fixed in https://github.com/dart-lang/sdk/issues/48966 already, so should be included in a future Dart/Flutter SDK release.
