### ISSUE TITLE
Extract Method shows up on import prefix

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#4029]
<img width="763" alt="Screenshot 2022-06-23 at 10 23 10" src="https://user-images.githubusercontent.com/1078012/175265392-54f3fd69-6e1d-4f12-b88f-4647b8172f36.png">

**Comment by DanTup** [comment]
Same occurs without the prefix if it's nullable:

```dart
import 'dart:io';

File? a;
```

It also fails if invoked:

```
[Error - 11:20:19 AM] An error occurred while handling workspace/executeCommand request: Bad state: No type: File
#0      ExpressionExtension.typeOrThrow (package:analyzer/src/dart/ast/extensions.dart:121:7)
#1      ExtractMethodRefactoringImpl._initializeParameters (package:analysis_server/src/services/refactoring/extract_method.dart:724:41)
#2      ExtractMethodRefactoringImpl.checkInitialConditions (package:analysis_server/src/services/refactoring/extract_method.dart:199:24)
#3      AbstractRefactorCommandHandler.getRefactoring (package:analysis_server/src/lsp/handlers/commands/abstract_refactor.dart:56:26)
#4      ValidateRefactorCommandHandler.execute.<anonymous closure> (package:analysis_server/src/lsp/handlers/commands/validate_refactor.dart:42:33)
```

**Comment by DanTup** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/23f1c542e43387fc312a0a11944f816f6e910a38.
