### ISSUE TITLE
Request textDocument/codeAction failed error from sort_constructors_first warning

### ISSUE THREAD

**Issue by Ruzo** [Dart-Code/Dart-Code#4038]
**Describe the bug**
Seems to be an error that happens when the extension tries to generate the Code Action to fix a `sort_constructors_first` warning.

**To Reproduce**
1. Create a class with its constructor placed after other members.
2. Make sure the linter includes a `sort_constructors_first` warning.
3. Hover over the warning.

**Expected behavior**
A quick fix to place the constructor before other members included in the code actions list.

**Screenshots**
![sort_constructors_first_action](https://user-images.githubusercontent.com/1992115/176491499-d6883b3b-6789-4723-807c-faa5016bae20.jpg)
---------------------------------------------------------

---------------------------------------------------------
![sort_constructors_first_action2](https://user-images.githubusercontent.com/1992115/176491508-99c279a4-cdb5-4b34-91e6-5baa64a71db1.jpg)

**Please complete the following information:**
 - Operating System and version: macOS Monterey 12.4
 - VS Code version: Version: 1.69.0-insider and 1.68.1 (Universal)
 - Dart extension version: v3.42.1
 - Dart/Flutter SDK version: Flutter 3.0.3 • channel stable / Tools • Dart 2.17.5 • DevTools 2.12.2
 - Target device (if the issue relates to Flutter debugging): N/A

**Comment by Ruzo** [comment]
Output error message:
```
[Error - 12:45:16 PM] Request textDocument/codeAction failed.
  Message: An error occurred while handling textDocument/codeAction request
  Code: -32001 
[Error - 12:45:16 PM] An error occurred while handling textDocument/codeAction request: Null check operator used on a null value
#0      SortConstructorFirst.compute.<anonymous closure> (package:analysis_server/src/services/correction/dart/sort_constructor_first.dart:35:40)
#1      ChangeBuilderImpl.addDartFileEdit (package:analyzer_plugin/src/utilities/change_builder/change_builder_core.dart:144:20)
<asynchronous suspension>
#2      SortConstructorFirst.compute (package:analysis_server/src/services/correction/dart/sort_constructor_first.dart:33:5)
<asynchronous suspension>
#3      FixProcessor._addFromProducers.compute (package:analysis_server/src/services/correction/fix_internal.dart:1416:9)
<asynchronous suspension>
#4      FixProcessor._addFromProducers (package:analysis_server/src/services/correction/fix_internal.dart:1429:9)
<asynchronous suspension>
#5      FixProcessor.compute (package:analysis_server/src/services/correction/fix_internal.dart:1371:5)
<asynchronous suspension>
#6      DartFixContributor.computeFixes (package:analysis_server/src/services/correction/fix_internal.dart:215:19)
<asynchronous suspension>
#7      CodeActionHandler._getFixActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:356:23)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:521:21)
<asynchronous suspension>
#9      CodeActionHandler._getCodeActions (package:analysis_server/src/lsp/handlers/handler_code_actions.dart:310:21)
<asynchronous suspension>
#10     ServerStateMessageHandler.handleMessage (package:analysis_server/src/lsp/handlers/handlers.dart:196:22)
<asynchronous suspension>
#11     LspAnalysisServer.handleMessage.<anonymous closure> (package:analysis_server/src/lsp/lsp_analysis_server.dart:342:26)
<asynchronous suspension>
```
