### ISSUE TITLE
VSCode Dart extension issue

### ISSUE THREAD

**Issue by mateominato** [Dart-Code/Dart-Code#4115]
This begun immediately after the most recent OSX 12.5.1 update. Another member on my team is seeing the same issue on a different machine. The dart analyzer plugin no longer functions at all -- files will attempt to save forever, it will not analyze the files, makes it prohibitive to write dart in vscode.

debugging attempts:
- re-grant VScode full disk permissions
- restart computer
- reinstall vscode
- change dart/flutter plugin versions (both downgrade and pre-release)
- re-install dart/flutter

Details

- Issue Type: `Bug`
- Extension Name: `dart-code`
- Extension Version: `3.44.0`
- OS Version: `Darwin arm64 21.6.0`
- VS Code version: `1.70.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 40,
		"activateCallTime": 5,
		"activateResolvedTime": 157,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "Dart-Code.dart-code",
				"_lower": "dart-code.dart-code"
			},
			"activationEvent": "workspaceContains:*/pubspec.yaml,*/*/pubspec.yaml,*.dart,*/*.dart,*/*/*.dart"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Header must provide a Content-Length property."
		}
	],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

occasionally this output is visible:
```
[Error - 11:30:42 AM] Stopping server failed
Error: Stopping the server timed out
	at ~/.vscode/extensions/dart-code.dart-code-3.46.1/out/dist/extension.js:32350:23
```

**Comment by DanTup** [comment]
Can you try running the **Dart: Open Extension Log** command and see if there's anything interesting in there when this happens? Also check Help -> Toggle Developer Tools -> console to see if there is anything more detailed reported there.

Apparently I'm only on macOS 12.4, but I'll start an upgrade shortly to see if I can reproduce there.

**Comment by mateominato** [comment]
@DanTup I don't see anything interesting looking in the extension log. The last few lines of input are pasted below; the rest of the log seems to just be the extension successfully locating the flutter and dart SDKs.
```
[10:33:34 AM] [General] [Info] Caching Pub package names from pub.dev...
[10:33:34 AM] [General] [Info] Analyzer:Startup timing: 295ms
[10:33:39 AM] [General] [Info] Returning cached results for project search
[10:33:39 AM] [General] [Info] Checking 11 projects for supported platforms
[10:33:39 AM] [General] [Info] Supported platforms for the workspace are ios, android, web
[10:33:39 AM] [General] [Info] Returning cached promise for getSupportedPlatforms()
```

As for the developer tools console, I see a bit more information:
```
mainThreadExtensionService.ts:79 [[object Object]]Header must provide a Content-Length property.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79

mainThreadExtensionService.ts:80 Error: Header must provide a Content-Length property.
	at StreamMessageReader.onData (vscode-file://vscode-app/Users/mateo/.vscode/extensions/dart-code.dart-code-3.44.0/out/dist/extension.js:30224:27)
	at LoggingTransform.<anonymous> (vscode-file://vscode-app/Users/mateo/.vscode/extensions/dart-code.dart-code-3.44.0/out/dist/extension.js:30208:18)
	at LoggingTransform.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at LoggingTransform.Readable.push (node:internal/streams/readable:228:10)
	at LoggingTransform._transform (vscode-file://vscode-app/Users/mateo/.vscode/extensions/dart-code.dart-code-3.44.0/out/dist/extension.js:5762:14)
	at LoggingTransform.Transform._write (node:internal/streams/transform:184:23)
	at writeOrBuffer (node:internal/streams/writable:389:12)
	at _write (node:internal/streams/writable:330:10)
	at LoggingTransform.Writable.write (node:internal/streams/writable:334:10)
	at Socket.ondata (node:internal/streams/readable:754:22)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Stopping the server timed out
I @ console.ts:137

console.ts:137 [Extension Host] stack trace: Error: Stopping the server timed out
	at /Users/mateo/.vscode/extensions/dart-code.dart-code-3.44.0/out/dist/extension.js:32253:23

mainThreadExtensionService.ts:79 [[object Object]]Stopping the server timed out
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79

mainThreadExtensionService.ts:80 Error: Stopping the server timed out
	at vscode-file://vscode-app/Users/mateo/.vscode/extensions/dart-code.dart-code-3.44.0/out/dist/extension.js:32253:23
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80

```

**Comment by DanTup** [comment]
> mainThreadExtensionService.ts:79 [[object Object]]Header must provide a Content-Length property.

This sounds like the analysis server might be outputting something that isn't valid LSP. Can you try enabling the [analysis server log](https://dartcode.org/docs/logging/#analyzer) in your workspace settings and see what's logged? (note: this log could include parts of your source files, so it's best to test on a new sample project or review the log before attaching).

**Comment by mateominato** [comment]
@DanTup I tried this in a new project and was unable to reproduce the error. We're using a monorepo with a number of distinct flutter packages contained, and when I opened the projects individually, I also did not see the error.

Anything specific I should look for in this log file? it's enormous, and I'm not sure how to remove the massive quantity of sensitive data without also eliminating anything that would be helpful.

**Comment by DanTup** [comment]
> Anything specific I should look for in this log file? it's enormous

How soon after opening does the issue occur? I assumed it was crashing at startup and expected a fairly small log, but now I'm not sure if that's the case. Do you see any references to "shutdown" in there or any lines containing "error"?

One of the first few lines probably includes `"initialized"`.. everything up until that point might be helpful to see the server startup (and hopefully isn't too much to ensure doesn't contain anything sensitive). You may need to increase the [log line length](https://dartcode.org/docs/settings/#dartmaxloglinelength) to avoid them being truncated though.

Some other things that may be worth trying:

- check whether you have anything in `.vscode/` folder (or `.code-workspace` files if you're using them) that might explain the difference between this project and the sample project
- clone your project into a new folder (so that it has no `.dart_tool`, `build`, etc. folders) and see if it reproduces there (if not, it might be caused by something in one of those folders)
- try to reduce a copy of your main project to the smallest cast that still reproduces it (presumably at some point after deleting code it would stop occurring, because you'd end up with essentially the same as the new sample project)

**Comment by mateominato** [comment]
@DanTup Here is everything up until "initialized":
```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.44.0
Flutter extension: 3.46.0 (activated)

App: Visual Studio Code
Version: 1.70.2
Platform: mac

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    Analyzer

Tue Aug 23 2022 [13:08:59 GMT-0700 (Pacific Daylight Time)] Log file started
[1:08:59 PM] [Analyzer] [Info] Spawning /Users/mateo/flutter/bin/cache/dart-sdk/bin/dart with args ["language-server","--protocol=lsp","--client-id=VS-Code","--client-version=3.44.0"]
[1:08:59 PM] [Analyzer] [Info]     PID: 57606
[1:08:59 PM] [Analyzer] [Info] ==> Content-Length: 6227
[1:08:59 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":57435,"clientInfo":{"name":"Visual Studio Code","version":"1.70.2"},"locale":"en-us","rootPath":"/Users/mateo/point-of-sale","rootUri":"file:///Users/mateo/point-of-sale","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional","normalizesLineEndings":true,"changeAnnotationSupport":{"groupsOnLabel":true}},"configuration":true,"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"tagSupport":{"valueSet":[1]},"resolveSupport":{"properties":["location.range"]}},"codeLens":{"refreshSupport":true},"executeCommand":{"dynamicRegistration":true},"didChangeConfiguration":{"dynamicRegistration":true},"workspaceFolders":true,"semanticTokens":{"refreshSupport":true},"fileOperations":{"dynamicRegistration":true,"didCreate":true,"didRename":true,"didDelete":true,"willCreate":true,"willRename":true,"willDelete":true},"inlineValue":{"refreshSupport":true},"inlayHint":{"refreshSupport":true},"diagnostics":{"refreshSupport":true}},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]},"codeDescriptionSupport":true,"dataSupport":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]},"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"insertTextModeSupport":{"valueSet":[1,2]},"labelDetailsSupport":true},"ins…
[1:08:59 PM] [Analyzer] [Info] <== {"method":"textDocument/publishDiagnostics","params":{"uri":*REMOVED*,"diagnostics":[]},"jsonrpc":"2.0"}
[1:08:59 PM] [Analyzer] [Info] <== Content-Length: 214
Content-Type: application/vscode-jsonrpc; charset=utf-8
[1:08:59 PM] [Analyzer] [Info] <== {"method":"textDocument/publishDiagnostics","params":{"uri":*REMOVED*,"diagnostics":[]},"jsonrpc":"2.0"}
[1:08:59 PM] [Analyzer] [Info] <== Content-Length: 202
Content-Type: application/vscode-jsonrpc; charset=utf-8
[1:08:59 PM] [Analyzer] [Info] <== {"method":"textDocument/publishDiagnostics","params":{"uri":*REMOVED*,"diagnostics":[]},"jsonrpc":"2.0"}
[1:08:59 PM] [Analyzer] [Info] <== Content-Length: 228
Content-Type: application/vscode-jsonrpc; charset=utf-8
[1:08:59 PM] [Analyzer] [Info] <== {"method":"textDocument/publishDiagnostics","params":{"uri":*REMOVED*,"diagnostics":[]},"jsonrpc":"2.0"}
[1:08:59 PM] [Analyzer] [Info] <== Content-Length: 38
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"id":1,"jsonrpc":"2.0","result":null}
[1:08:59 PM] [Analyzer] [Info] <== Content-Length: 248
Content-Type: application/vscode-jsonrpc; charset=utf-8
[1:08:59 PM] [Analyzer] [Info] ==> Content-Length: 67
[1:08:59 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"exit","clientRequestTime":1661285339694}
[1:08:59 PM] [Analyzer] [Info] <== {"method":"textDocument/publishDiagnostics","params":{"uri":*REMOVED*,"diagnostics":[]},"jsonrpc":"2.0"}
[1:08:59 PM] [Analyzer] [Info] <== Content-Length: 230
Content-Type: application/vscode-jsonrpc; charset=utf-8
[1:08:59 PM] [Analyzer] [Info] <== {"method":"textDocument/publishDiagnostics","params":{"uri":"*REMOVED*","diagnostics":[]},"jsonrpc":"2.0"}
[1:08:59 PM] [Analyzer] [Info] <== Content-Length: 398
Content-Type: application/vscode-jsonrpc; charset=utf-8
[1:08:59 PM] [Analyzer] [Info] <== {"id":0,"jsonrpc":"2.0","result":{"capabilities":{"executeCommandProvider":{"commands":["edit.sortMembers","edit.organizeImports","edit.fixAll","edit.sendWorkspaceEdit","refactor.perform"],"workDoneProgress":true},"workspaceSymbolProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":true}}},"serverInfo":{"name":"Dart SDK LSP Analysis Server","version":"2.17.5"}}}
[1:08:59 PM] [Analyzer] [Info] ==> Content-Length: 86
[1:08:59 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","method":"initialized","params":{},"clientRequestTime":1661285339780}
```

I'll try those other suggestions and get back to you. thank you!

**Comment by DanTup** [comment]
Thanks - I can't see anything obviously wrong there, although I can see VS Code asking the server to exit (it's not clear why):

It may be worth enabling the [general extension log](https://dartcode.org/docs/logging/#extension) and reproducing the issue too, and seeing whether it looks like the extension is trying to restart (this is one thing that would cause the analysis server to be shutdown and restarted, although it should only occur in some specific cases, and usually only after some sort of prompt or something).

**Comment by mateominato** [comment]
Experimenting, I was able to see some pretty inconsistent behavior -- it doesn't seem like one specific project or folder within the mono is causing the error, but if I delete a bunch of stuff and restart the analysis server, everything seems to once again work as expected.

I enabled the general extension log while I was testing, but was never able to get any output that looked very interesting. I've attached it anyway.

```
!! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.44.0
Flutter extension: 3.46.0 (activated)

App: Visual Studio Code
Version: 1.70.2
Platform: mac

HTTP_PROXY: undefined
NO_PROXY: undefined

Logging Categories:
    General

Tue Aug 23 2022 [13:46:23 GMT-0700 (Pacific Daylight Time)] Log file started
[1:46:23 PM] [General] [Info] Searching for SDKs...
[1:46:23 PM] [General] [Info] Environment PATH:
[1:46:23 PM] [General] [Info]     /Users/mateo/.rbenv/shims
[1:46:23 PM] [General] [Info]     /Users/mateo/bin
[1:46:23 PM] [General] [Info]     /usr/local/bin
[1:46:23 PM] [General] [Info]     /opt/homebrew/bin
[1:46:23 PM] [General] [Info]     /opt/homebrew/sbin
[1:46:23 PM] [General] [Info]     /usr/local/bin
[1:46:23 PM] [General] [Info]     /usr/bin
[1:46:23 PM] [General] [Info]     /bin
[1:46:23 PM] [General] [Info]     /usr/sbin
[1:46:23 PM] [General] [Info]     /sbin
[1:46:23 PM] [General] [Info]     /Library/Apple/usr/bin
[1:46:23 PM] [General] [Info]     /Users/mateo/.banjo/bin
[1:46:23 PM] [General] [Info]     /Users/mateo/flutter/bin
[1:46:23 PM] [General] [Info]     /Users/mateo/.banjo/bin
[1:46:23 PM] [General] [Info] Returning cached results for project search
[1:46:23 PM] [General] [Info] Found Flutter project at *REMOVED*:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[1:46:23 PM] [General] [Info] Searching for flutter
[1:46:23 PM] [General] [Info]     Looking for flutter in:
[1:46:23 PM] [General] [Info]         *REMOVED*
[1:46:23 PM] [General] [Info]         *REMOVED*r/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin/
[1:46:23 PM] [General] [Info]        *REMOVED*/.flutter
[1:46:23 PM] [General] [Info]         *REMOVED*/.flutter/bin
[1:46:23 PM] [General] [Info]         *REMOVED*/vendor/flutter
[1:46:23 PM] [General] [Info]         *REMOVED*/vendor/flutter/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter-sdk
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter-sdk/bin
[1:46:23 PM] [General] [Info]         /google/flutter
[1:46:23 PM] [General] [Info]         /google/flutter/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/.rbenv/shims
[1:46:23 PM] [General] [Info]         /Users/mateo/.rbenv/shims/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/bin
[1:46:23 PM] [General] [Info]         /usr/local/bin
[1:46:23 PM] [General] [Info]         /opt/homebrew/bin
[1:46:23 PM] [General] [Info]         /opt/homebrew/sbin
[1:46:23 PM] [General] [Info]         /usr/local/bin
[1:46:23 PM] [General] [Info]         /usr/bin
[1:46:23 PM] [General] [Info]         /bin
[1:46:23 PM] [General] [Info]         /usr/sbin
[1:46:23 PM] [General] [Info]         /sbin
[1:46:23 PM] [General] [Info]         /Library/Apple/usr/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/.banjo/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/.banjo/bin
[1:46:23 PM] [General] [Info]     Found at:
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin/
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin
[1:46:23 PM] [General] [Info]     Candidate paths to be post-filtered:
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter
[1:46:23 PM] [General] [Info]     Found at /Users/mateo/flutter
[1:46:23 PM] [General] [Info]     Returning SDK path /Users/mateo/flutter for flutter
[1:46:23 PM] [General] [Info] Searching for dart
[1:46:23 PM] [General] [Info]     Looking for dart in:
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin/cache/dart-sdk
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin/cache/dart-sdk/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/.rbenv/shims
[1:46:23 PM] [General] [Info]         /Users/mateo/.rbenv/shims/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/bin
[1:46:23 PM] [General] [Info]         /usr/local/bin
[1:46:23 PM] [General] [Info]         /opt/homebrew/bin
[1:46:23 PM] [General] [Info]         /opt/homebrew/sbin
[1:46:23 PM] [General] [Info]         /usr/local/bin
[1:46:23 PM] [General] [Info]         /usr/bin
[1:46:23 PM] [General] [Info]         /bin
[1:46:23 PM] [General] [Info]         /usr/sbin
[1:46:23 PM] [General] [Info]         /sbin
[1:46:23 PM] [General] [Info]         /Library/Apple/usr/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/.banjo/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/.banjo/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin/cache/dart-sdk
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin/cache/dart-sdk/bin
[1:46:23 PM] [General] [Info]     Found at:
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin/cache/dart-sdk/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin/cache/dart-sdk/bin
[1:46:23 PM] [General] [Info]     Candidate paths to be post-filtered:
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin/cache/dart-sdk
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter
[1:46:23 PM] [General] [Info]         /Users/mateo/flutter/bin/cache/dart-sdk
[1:46:23 PM] [General] [Info]     Found at /Users/mateo/flutter/bin/cache/dart-sdk
[1:46:23 PM] [General] [Info]     Returning SDK path /Users/mateo/flutter/bin/cache/dart-sdk for dart
[1:46:23 PM] [General] [Info] !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.44.0
Flutter extension: 3.46.0 (activated)

App: Visual Studio Code
Version: 1.70.2
Platform: mac

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /Users/mateo/flutter/bin/cache/dart-sdk
    Ver: 2.17.5
Flutter SDK:
    Loc: /Users/mateo/flutter
    Ver: 3.0.4

HTTP_PROXY: undefined
NO_PROXY: undefined
[1:46:23 PM] [General] [Info] Returning cached results for project search
[1:46:23 PM] [General] [Info] Activating Flutter extension for Flutter project...
[1:46:23 PM] [General] [Info] Extension:Startup timing: 15ms
[1:46:23 PM] [General] [Info] Found 0 folders requiring "pub get":
[1:46:23 PM] [General] [Info] Done!
[1:46:23 PM] [General] [Info] !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.44.0
Flutter extension: 3.46.0 (activated)

App: Visual Studio Code
Version: 1.70.2
Platform: mac

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /Users/mateo/flutter/bin/cache/dart-sdk
    Ver: 2.17.5
Flutter SDK:
    Loc: /Users/mateo/flutter
    Ver: 3.0.4

HTTP_PROXY: undefined
NO_PROXY: undefined
[1:46:23 PM] [General] [Info] Caching Pub package names from pub.dev...
[1:46:23 PM] [General] [Info] Analyzer:Startup timing: 283ms
[1:46:28 PM] [General] [Info] Returning cached results for project search
[1:46:28 PM] [General] [Info] Checking 10 projects for supported platforms
[1:46:28 PM] [General] [Info] Supported platforms for the workspace are ios, android
[1:46:29 PM] [General] [Info] Analyzer:FirstAnalysis timing: 5590ms
[1:47:28 PM] [General] [Info] Pubspec *REMOVED*/pubspec.yaml was modified
[1:47:28 PM] [General] [Info] Pubspec *REMOVED*/pubspec.yaml was modified
[1:47:28 PM] [General] [Info] Pubspec *REMOVED*/pubspec.yaml was modified
[1:47:28 PM] [General] [Info] Pubspec *REMOVED*/pubspec.yaml was modified
[1:47:28 PM] [General] [Info] Pubspec *REMOVED*/pubspec.yaml was modified
[1:47:28 PM] [General] [Info] Pubspec *REMOVED*/pubspec.yaml was modified
[1:47:29 PM] [General] [Info] Pubspec *REMOVED*/peripheral_flutter/pubspec.yaml was modified
[1:47:29 PM] [General] [Info] Pubspec *REMOVED*/pubspec.yaml was modified
[1:47:29 PM] [General] [Info] Pubspec *REMOVED*/pubspec.yaml was modified
[1:47:29 PM] [General] [Info] Pubspec *REMOVED*/pubspec.yaml was modified
[1:47:30 PM] [General] [Info] Returning cached results for project search
[1:47:30 PM] [General] [Info] Found 10 folders requiring "pub get":
    *REMOVED DIRECTORIES*

**Comment by DanTup** [comment]
@mateominato was that log file taken when the issue was occurring? (if so, do you know what time the error occurred?).

And out of interest, did you modify all those `pubspec.yaml` files at 1:47:28? I doubt it's related to the issue, but if looks odd.

**Comment by mateominato** [comment]
@DanTup yes, i looked at the file right after i saw the content length error pop up in developer tools. this was right after i restored a bunch of directories i had temporarily deleted to see if I could root cause, thus all the modified pubspecs.

**Comment by DanTup** [comment]
@mateominato could you try increasing the [log line length](https://dartcode.org/docs/settings/#dartmaxloglinelength) can capture a log again the next time it occurs. Then provide anything that comes before the line that looks like:

```
{"jsonrpc":"2.0","method":"exit","clientRequestTime":1661285339694}
```

In the original log above this was only a small number of lines, but some of them are truncated so it's hard for me to match up the lengths with what's being sent. If you need to remove anything (like file paths), can you replace them with an equivalent number of placeholder characters, so the lengths will still remain in-tact (in case there is a difference between the header and the content).

Thanks!

**Comment by CoderUni** [comment]
I'm also experiencing the same issue. Here is the last few logs I got from the extension:
```
Dart Code extension: 3.48.4
Flutter extension: 3.48.0 (not activated)

App: Visual Studio Code
Version: 1.71.2
Platform: linux

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /home/randomUser/flutter/bin/cache/dart-sdk
    Ver: 2.18.1
Flutter SDK:
    Loc: /home/randomUser/flutter
    Ver: 3.3.2

HTTP_PROXY: undefined
NO_PROXY: undefined
[12:38:45 PM] [General] [Info] Returning cached results for project search
[12:38:45 PM] [General] [Info] Activating Flutter extension for Flutter project...
[12:38:45 PM] [General] [Info] Extension:Startup timing: 356ms
[12:38:45 PM] [General] [Info] Found 0 folders requiring "pub get":
[12:38:45 PM] [General] [Info] Caching Pub package nPMes from pub.dev...
[12:38:45 PM] [General] [Info] !! PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING !!

Dart Code extension: 3.48.4
Flutter extension: 3.48.0 (activated)

App: Visual Studio Code
Version: 1.71.2
Platform: linux

Workspace type: Flutter
Analyzer type: LSP
Multi-root?: false

Dart SDK:
    Loc: /home/randomUser/flutter/bin/cache/dart-sdk
    Ver: 2.18.1
Flutter SDK:
    Loc: /home/randomUser/flutter
    Ver: 3.3.2

HTTP_PROXY: undefined
NO_PROXY: undefined
[12:38:45 PM] [General] [Info] Analyzer:Startup timing: 448ms
[12:38:49 PM] [General] [Info] Returning cached results for project search
[12:38:49 PM] [General] [Info] Checking 1 projects for supported platforms
[12:38:49 PM] [General] [Info] Supported platforms for the workspace are windows, ios, android, web
[12:38:49 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()

```

**Comment by CoderUni** [comment]
Looks like the analysis will work after 6 minutes of waiting. I got an extra log from the dart extension.
```
[12:44:42 PM] [General] [Info] Analyzer:FirstAnalysis timing: 139489ms
```

**Comment by DanTup** [comment]
@CoderUni can you try enabling the [instrumentation log](https://dartcode.org/docs/logging/#analyzer-instrumentation) and see what's being logged before/during that period?

**Comment by CoderUni** [comment]
Thanks @DanTup. I emailed the logs to `logs@dartcode.org`

**Comment by DanTup** [comment]
@CoderUni thanks, I got the log - and I can see around 6 minutes between the server initializing and it started to report results, and then around another 5 minutes for the first analysis to complete. Unfortunately there's not much logged that indicates why.

Can you confirm how big the workspace is you have open, and what sort of disk/filesystem it's on (for example is it a mechanical hdd, or a remote workspace, or something?). The results seem like what would occur if the file system was very slow, or the project was very large (although I'm not sure if either are the case).

Could you also confirm this wasn't just after you'd upgraded Flutter/Dart (since the first time after an upgrade, things will be slower than usual - although certainly not normally this slow).

And finally, could you send me the output of running `code --status` _while you have this project open_ after analysis has completed?

Thanks!

**Comment by CoderUni** [comment]
Thanks, Danny.

This workspace is really small. I'm not sure why but I only have an issue
with this particular project. It might be because I'm using aws amplify
though. I'm just not sure. The project is on a local ssd storage (Same as
my other projects that are much bigger). The issue existed even before I
updated dart. I'm currently on the latest version and the analyzer works on
other bigger projects right now.

Before the analyzer started bugging out like this, I think my computer
froze while I was using vscode. I had to force my computer to shutdown that
time.

Here is the output of code --status after analysis has completed:
[46059:0925/014001.523746:WARNING:bluez_dbus_manager.cc(248)] Floss manager
not present, cannot set Floss enable/disable.
Version:          Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7,
2022-09-14T21:12:14.256Z)
OS Version:       Linux x64 5.15.69-1-lts
CPUs:             AMD Ryzen 5 3600 6-Core Processor (12 x 3600)
Memory (System):  15.55GB (10.29GB free)
Load (avg):       1, 1, 1
VM:               0%
Screen Reader:    no
Process Argv:     --crash-reporter-id cb9f934d-c029-4604-bd06-70d3eb4d4637
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               disabled_off
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  skia_renderer:                          enabled_on
                  video_decode:                           disabled_software
                  video_encode:                           disabled_software
                  vulkan:                                 disabled_off
                  webgl:                                  enabled
                  webgl2:                                 enabled
                  webgpu:                                 disabled_off

CPU % Mem MB   PID Process
    0   143 38067 code main
    0    32 38070   zygote
    0   127 44140     gpu-process
    0    16 44201       broker
    0    32 38071   zygote
    0     0 38073     zygote
    0    48 38115   utility-network-service
    0   223 38131   window (settings_page.dart - qstaff - Visual Studio
Code)
    0   127 38167   shared-process
    0    64 38197     ptyHost
    0     0 38429       /usr/bin/bash --init-file
/opt/visual-studio-code/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0   478 39462     fileWatcher
    0   143 39448   extensionHost
    0    64 39520     /opt/visual-studio-code/code
--ms-enable-electron-run-as-node
/home/quantum/.vscode/extensions/formulahendry.auto-rename-tag-0.1.10/packages/server/dist/serverMain.js
--node-ipc --clientProcessId=39448
    0   143 39542     electron_node config.js
    0    32 39543     /home/quantum/flutter/bin/cache/dart-sdk/bin/dart
devtools --machine --try-ports 10 --allow-embedding
    0  1162 39545     /home/quantum/flutter/bin/cache/dart-sdk/bin/dart
language-server --protocol=lsp --client-id=VS-Code --client-version=3.48.4
--instrumentation-log-file=/home/quantum/dartLogs.txt

Workspace Stats:
|  Window (settings_page.dart - qstaff - Visual Studio Code)
|    Folder (qstaff): more than 20068 files
|      File types: env(3021) json(35) log(10) bin(7) dart(6) yaml(6) lock(6)
|                  properties(6) stamp(4) md(4)
|      Conf files: github-actions(1) launch.json(1)
|      Launch Configs: dart(3)

**Comment by CoderUni** [comment]
Thanks @DanTup, I sent the `code --status` logs to `logs@dartcode.org`

**Comment by DanTup** [comment]
@CoderUni I don't seem to have your email, although I got the output from a notification of your original message.

I think this is a different issue to the originally reported issue above here (which includes "Header must provide a Content-Length property.") so I've opened https://github.com/Dart-Code/Dart-Code/issues/4180 where we can continue to debug this.
