### ISSUE TITLE
Error: spawn EPERM

### ISSUE THREAD

**Issue by khg0343** [Dart-Code/Dart-Code#4211]
**Describe the bug**
Suddenly Flutter & Dart extension for vscode stopped working.
The extensions just won't start. I reinstalled whole vscode several times, but it keeps happening.
Even the dart and flutter commands are not found on command pallet

**To Reproduce**

**Expected behavior**

**Screenshots**
```
[2022-10-09 22:26:59.923] [exthost] [info] ExtensionService#_doActivateExtension Dart-Code.dart-code, startup: false, activationEvent: 'onLanguage:dart'
[2022-10-09 22:26:59.923] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2022-10-09 22:26:59.924] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2022-10-09 22:26:59.930] [exthost] [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
[2022-10-09 22:26:59.930] [exthost] [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: true, activationEvent: '*'
[2022-10-09 22:26:59.931] [exthost] [info] ExtensionService#_doActivateExtension mhutchie.git-graph, startup: true, activationEvent: '*'
[2022-10-09 22:27:04.790] [exthost] [error] Activating extension Dart-Code.dart-code failed due to an error:
[2022-10-09 22:27:04.794] [exthost] [error] Error: spawn EPERM
	at ChildProcess.spawn (node:internal/child_process:413:11)
	at Object.spawn (node:child_process:720:9)
	at safeSpawn (c:\Users\SAMSUNG\.vscode\extensions\dart-code.dart-code-3.50.0\out\dist\extension.js:23248:26)
	at FlutterDaemon.createProcess (c:\Users\SAMSUNG\.vscode\extensions\dart-code.dart-code-3.50.0\out\dist\extension.js:23731:50)
	at new FlutterDaemon (c:\Users\SAMSUNG\.vscode\extensions\dart-code.dart-code-3.50.0\out\dist\extension.js:13282:18)
	at c:\Users\SAMSUNG\.vscode\extensions\dart-code.dart-code-3.50.0\out\dist\extension.js:12591:29
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\SAMSUNG\.vscode\extensions\dart-code.dart-code-3.50.0\out\dist\extension.js:12320:58)
```

**Please complete the following information:**
 - Operating System and version: windows 10
 - VS Code version: 1.72.0
 - Dart extension version: 3.50.0
 - Dart/Flutter SDK version: flutter 3.3.4
 - Target device (if the issue relates to Flutter debugging):

**Comment by DanTup** [comment]
Can you try enabling the extension log by adding the following to your VS Code user settings:

```
"dart.extensionLogFile": "C:\\Users\\SAMSUNG\\Desktop\\dart_log.txt", // Put a full path to where you want to log here
```

Then reproduce the issue, and attach the log file (after removing anything sensitive) here.

Thanks!

**Comment by khg0343** [comment]
[dart_log.txt](https://github.com/Dart-Code/Dart-Code/files/9751906/dart_log.txt)

**Comment by DanTup** [comment]
@khg0343 can you try running `flutter doctor` from the terminal built inside VS Code?
