### ISSUE TITLE
Rename Symbol not working

### ISSUE THREAD

**Issue by CodingSoot** [Dart-Code/Dart-Code#4297]
**Describe the bug**
When using the "Rename Symbol" command on a symbol that is used across multiple files (a class name, a method name, a function name...), I get this error : `Rename failed to apply edits`. The output window shows this error : 

```console
2022-12-03 18:56:37.531 [error] Error: Overlapping ranges are not allowed!
    at S.applyEdits (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:579:547)
    at An._doApplyEdits (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:754:1577)
    at An.applyEdits (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:754:1391)
    at f.pushEditOperation (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:598:909)
    at An._pushEditOperations (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:754:305)
    at An.pushEditOperations (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:752:848)
    at i.apply (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:915:13027)
    at c.apply (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:915:16342)
    at async v._performTextEdits (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2785:28523)
    at async v.perform (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2785:27906)
    at async m.apply (vscode-file://vscode-app/c:/Users/omar-/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2785:30271)
```

**Please complete the following information:**
 - Operating System and version: Windows 10
 - VS Code version: 1.73.1
 - Dart extension version: 3.54.1
 - Dart/Flutter SDK version: Dart sdk v 2.18.3 (The latest version 2.18.3 is not available yet on Chocolatey)

**Comment by DanTup** [comment]
@CodingSoot are you able to prodive a small code sample that reproduces this? My guess is that there's something specific about your project that's causing the server to generate conflicting edits while you perform this rename. Thanks!

**Comment by CodingSoot** [comment]
@DanTup You are right, I couldn't reproduce this in a new dart project.

**Comment by DanTup** [comment]
@CodingSoot to be clear, I still think there's a bug here that needs to be fixed. But it will be difficult to fix without a repro so I can review the edits that the server is trying to produce.

If you're able to reproduce it in something you can share, please let me know! :)
