### ISSUE TITLE
Add Realm to rely on Dart to run Android Studio, and VSCode runs with an error

### ISSUE THREAD

**Issue by josercc** [Dart-Code/Dart-Code#4301]
The following demos can be tested run `bin/realm_dart_example.dart`

[realm_dart_example.zip](https://github.com/Dart-Code/Dart-Code/files/10181252/realm_dart_example.zip)

```
Connecting to VM Service at http://127.0.0.1:55822/SISzPpN96Oc=/
Null check operator used on a null value
#0      BinaryPrinter._getVariableIndex (package:kernel/binary/ast_to_binary.dart:83:17)
#1      BinaryPrinter.visitVariableGet (package:kernel/binary/ast_to_binary.dart:1497:17)
#2      VariableGet.accept (package:kernel/ast.dart:4137:44)
#3      BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#4      BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:340:7)
#5      BinaryPrinter.visitArguments (package:kernel/binary/ast_to_binary.dart:1751:5)
#6      Arguments.accept (package:kernel/ast.dart:5119:38)
#7      BinaryPrinter.writeArgumentsNode (package:kernel/binary/ast_to_binary.dart:444:10)
#8      BinaryPrinter.visitStaticInvocation (package:kernel/binary/ast_to_binary.dart:1734:5)
#9      StaticInvocation.accept (package:kernel/ast.dart:6289:44)
#10     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#11     BinaryPrinter.visitExpressionStatement (package:kernel/binary/ast_to_binary.dart:2052:5)
#12     ExpressionStatement.accept (package:kernel/ast.dart:8829:43)
#13     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#14     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:340:7)
#15     BinaryPrinter.visitBlockExpression (package:kernel/binary/ast_to_binary.dart:2017:5)
#16     BlockExpression.accept (package:kernel/ast.dart:8461:44)
#17     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#18     BinaryPrinter.writeNodeList (package:kernel/binary/ast_to_binary.dart:340:7)
#19     BinaryPrinter.visitArguments (package:kernel/binary/ast_to_binary.dart:1751:5)
#20     Arguments.accept (package:kernel/ast.dart:5119:38)
#21     BinaryPrinter.writeArgumentsNode (package:kernel/binary/ast_to_binary.dart:444:10)
#22     BinaryPrinter.visitStaticInvocation (package:kernel/binary/ast_to_binary.dart:1734:5)
#23     StaticInvocation.accept (package:kernel/ast.dart:6289:44)
#24     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#25     BinaryPrinter.writeOptionalNode (package:kernel/binary/ast_to_binary.dart:522:7)
#26     BinaryPrinter.writeVariableDeclaration (package:kernel/binary/ast_to_binary.dart:2266:5)
#27     BinaryPrinter.visitLet (package:kernel/binary/ast_to_binary.dart:2006:5)
#28     Let.accept (package:kernel/ast.dart:8390:44)
#29     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
#30     BinaryPrinter.visitYieldStatement (package:kernel/binary/ast_to_binary.dart:2246:5)
#31     YieldStatement.accept (package:kernel/ast.dart:10180:43)
#32     BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:430:10)
```

**Comment by josercc** [comment]
@DanTup 

I found a problem that the VSCode kept reminding me that the current Dart version was 2.17.1. I saw that the corresponding Flutter version was 3.0.1, but I never installed Flutter 3.0.1. I have installed versions 2.10.5 and 3.3.2 through FVM. Later, I thought that the first time I installed Dart, I installed version 2.17.1 through Brew install Dart In zshrc, the configuration is read from the last set Brew. The configuration has been modified and can be run.

**Comment by DanTup** [comment]
@josercc it appears that this issue has already been fixed in the Dart SDK. Your project was using 2.17.1 and I can repro there, but using 2.18.0 the issue does not occur.

So if you upgrade to the latest stable SDK, I believe the problem will go away :)

2.17:

<img width="764" alt="Screenshot 2022-12-12 at 12 56 25" src="https://user-images.githubusercontent.com/1078012/207050564-b3dee961-ae95-4905-ba03-52e26e3ecd4a.png">

2.18:

<img width="587" alt="Screenshot 2022-12-12 at 12 56 54" src="https://user-images.githubusercontent.com/1078012/207050643-c400fed9-470a-436d-9903-d156902ed130.png">

If this isn't the case, please let me know.
