### ISSUE TITLE
Dart Analysis Server crashes

### ISSUE THREAD

**Issue by kbaylosis** [Dart-Code/Dart-Code#4338]
**Describe the bug**
Visual Studio code shows ```The Dart Analysis Server server crashed 5 times in the last 3 minutes.``` error

**To Reproduce**
1. Open a flutter project in Visual Studio code
2. After a few seconds the error shows up. Restarting the analysis server doesn't fix the problem.

NOTES:
1. Tried creating a new flutter project with the same results.
2. Tried creating a new dart project and the problem doesn't show up.

**Dart Analysis Server Output Logs**
```
[8:54:52 PM] [Analyzer] [Info] <== Content-Length: 97
Content-Type: application/vscode-jsonrpc; charset=utf-8
[8:54:52 PM] [Analyzer] [Info] <== {"id":2,"jsonrpc":"2.0","method":"window/workDoneProgress/create","params":{"token":"ANALYZING"}}
[8:54:52 PM] [Analyzer] [Info] ==> Content-Length: 72
[8:54:52 PM] [Analyzer] [Info] ==> {"jsonrpc":"2.0","id":2,"result":null,"clientRequestTime":1673268892514}
[8:54:52 PM] [Analyzer] [Info] <== Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf-8
[8:54:52 PM] [Analyzer] [Info] <== {"jsonrpc":"2.0","method":"$/progress","params":{"token":"ANALYZING","value":{"kind":"begin","title":"Analyzing…"}}}
[8:54:52 PM] [Analyzer] [Error] Unhandled exception:
Bad state: Suspected cycle. [(uri: package:flutter_test/flutter_test.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/packages/flutter_test/lib/flutter_test.dart), (uri: package:flutter_test/src/test_text_input.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/packages/flutter_test/lib/src/test_text_input.dart), (uri: package:flutter/services.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/packages/flutter/lib/services.dart), (uri: package:flutter/src/servi…
[8:54:52 PM] [Analyzer] [Error] /auth/auth/auth/auth/api_client.dart), (uri: dart:_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_helper.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/bin/cache/pkg/sky_engine/lib/_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_helper.dart), (uri: dart:_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_exception.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/bin/cache/pkg/sky_engine/lib/_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_exception.dart), (ur…
[8:54:52 PM] [Analyzer] [Error] is/fvm/versions/3.3.10/bin/cache/pkg/sky_engine/lib/_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/authentication.dart), (uri: dart:_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_client.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/bin/cache/pkg/sky_engine/lib/_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_client.dart), (uri: dart:_http/auth/auth/au…
[8:54:52 PM] [Analyzer] [Error] uth/auth/auth/auth/auth/auth/auth/auth/authentication.dart), (uri: dart:_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_client.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/bin/cache/pkg/sky_engine/lib/_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_client.dart), (uri: dart:_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/a…
[8:54:52 PM] [Analyzer] [Error] h/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_client.dart), (uri: dart:_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_helper.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/bin/cache/pkg/sky_engine/lib/_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/au…
[8:54:52 PM] [Analyzer] [Error] auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/authentication.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/bin/cache/pkg/sky_engine/lib/_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/authentication.dart), (uri: dart:_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/a…
[8:54:52 PM] [Analyzer] [Error] uth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_client.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/bin/cache/pkg/sky_engine/lib/_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_client.dart), (uri: dart:_http/auth/auth/auth/auth/…
[8:54:52 PM] [Analyzer] [Error] auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/authentication.dart), (uri: dart:_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_client.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/bin/cache/pkg/s…
[8:54:52 PM] [Analyzer] [Error] th/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_exception.dart, path: /Users/kennethbaylosis/fvm/versions/3.3.10/bin/cache/pkg/sky_engine/lib/_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth/api_exception.dart), (uri: dart:_http/…
[8:54:52 PM] [Analyzer] [Error] )
#5      _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#6      _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#7      DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#8      _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#9      _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#10  …
[8:54:52 PM] [Analyzer] [Error] s/available_declarations.dart:1822:20)
#87     _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#88     DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#89     _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#90     _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#91     DeclarationsTracker._getFileByUri (package:analyzer/src/servic…
[8:54:52 PM] [Analyzer] [Error] kage:analyzer/src/services/available_declarations.dart:1281:19)
#169    DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#170    _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#171    _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#172    DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#173    _File._fileForRela…
[8:54:52 PM] [Analyzer] [Error] 250    DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#251    _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#252    _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#253    DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#254    _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dar…
[8:54:52 PM] [Analyzer] [Error] rvices/available_declarations.dart:758:10)
#332    _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#333    _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#334    DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#335    _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#336    _File.refresh (package:analyzer/src/services/a…
[8:54:52 PM] [Analyzer] [Error] RelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#414    _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#415    DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#416    _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#417    _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#418    DeclarationsTracker._…
[8:54:52 PM] [Analyzer] [Error] .dart:1822:20)
#495    _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#496    DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#497    _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#498    _File.refresh (package:analyzer/src/services/available_declarations.dart:1281:19)
#499    DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declaration…
[8:54:52 PM] [Analyzer] [Error] es/available_declarations.dart:1281:19)
#577    DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#578    _File._fileForRelativeUri (package:analyzer/src/services/available_declarations.dart:1822:20)
#579    _File.refresh (package:analyzer/src/services/available_declarations.dart:1278:21)
#580    DeclarationsTracker._getFileByUri (package:analyzer/src/services/available_declarations.dart:758:10)
#581    _File._fileForRelativeUri (package:analyze…
```

***Flutter Doctor Output***
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.5.1 21G83 darwin-arm, locale en-PH)
    • Flutter version 3.3.10 on channel stable at /Users/kennethbaylosis/fvm/versions/3.3.10
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc3)
    • Android SDK at /Users/kennethbaylosis/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • macOS (desktop)           • macos                     • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)              • chrome                    • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Please complete the following information:**
 - Operating System and version: MacOS Monterey 12.5.1
 - VS Code version: 1.74.2
 - Dart extension version: v3.56.0
 - Dart/Flutter SDK version: Dart 2.18.6 / Flutter 3.3.10

**Comment by DanTup** [comment]
This error "Bad state: Suspected cycle." along with a repeating path `pkg/sky_engine/lib/_http/auth/auth/auth/auth/auth/auth/auth/auth/auth/auth` looks similar to #4037 (which had `pkg/sky_engine/lib/functions/functions/functions/functions/functions`).

There are steps the author if that issue took to resolve the issue here: https://github.com/Dart-Code/Dart-Code/issues/4037#issuecomment-1179464816

I suspect it may have been deleting the `~/.dartServer` folder that fixed the issue, although I'm not sure what leads to this error. You could try renaming the folder instead (so if it does fix it, we have a copy of the folder that leads to this error), although I don't know how easy it will be to share (it may be very large, and I don't know if it may contain sensitive information - @scheglov may be able to confirm exactly what's stored in there?).

**Comment by kbaylosis** [comment]
> 

Deleting the ```~/.dartServer``` fixed my issue. Thanks!

**Comment by DanTup** [comment]
@kbaylosis did you happen to rename/keep a copy of the folder? Based on @scheglov's comment above, it may be reasonable for you to share that folder (minus the `ex` sub-folder) if there's nothing sensitive in the names of files/classes/fields. That might help us reproduce and get to the bottom of the issue. It could get quite large though, so it might not be easy to share.

If you didn't keep it, but you see this issue again in future, it's something to consider. Thanks!

**Comment by kbaylosis** [comment]
yep I managed to keep a copy of the folder... let me take a review of the files and i'll post it here after

**Comment by DanTup** [comment]
You can also share with me at logs@dartcode.org if that's easier (although that address won't accept huge attachments). Be sure not to send anything that may be sensitive/confidential though (such as the `ex` folder noted above).

**Comment by kbaylosis** [comment]
sure... i'll be sending a link
