### ISSUE TITLE
Dart developer's log() optional parameters not working

### ISSUE THREAD

**Issue by TiffApps** [Dart-Code/Dart-Code#4479]
**Describe the bug**
Hi! I've tried using the optional parameters of the `log` function for the first time, and it doesn't seem like the `time` one works? Maybe also the `level` one, unless it simply changes the color or prefix of the log, i don't know.

**To Reproduce**
Here is how I called it:
```dart
          try {
            // ...
          } on CommandsException catch (e) {
            // ...
            log(
              'Timeout reached - Record cancelled.',
              time: DateTime.now(),
              level: 408,
              stackTrace: e.stackTrace,
            );
            // ...
          }
```
And here is what I got in my console:
```bash
[log] Timeout reached - Record cancelled.
[log] #0      EventManager._nextComponentEvent.<anonymous closure>
event_manager.dart:47
#1      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#2      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#3      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
```

**Expected behavior**
As you noticed, the `time` (and `level` too? Don't know the intended behavior of this one very due to the lack of informations about it) is/are missing in the console.

**Please complete the following information:**
 - Operating System and version: **W10**
 - VS Code version: **1.77.0**
 - Dart extension version: **3.60.1**
 - Dart SDK version: **2.19.6**

cc @DanTup

**Comment by DanTup** [comment]
Looks like there are quite a few fields we might not be handling in the DAP here:

https://api.dart.dev/stable/2.19.6/dart-developer/log.html

@bkonyi do you know if these logs are being printed anywhere else that I could try to align the DAP outputs with?

**Comment by bkonyi** [comment]
The output from `log(...)` should also be visible in the Logging tab in DevTools.

**Comment by DanTup** [comment]
Thanks - though it looks like DevTools isn't showing the extra info either:

<img width="500" alt="Screenshot 2023-04-04 at 10 46 23" src="https://user-images.githubusercontent.com/1078012/229754122-654888f7-71c9-437b-9b6b-ec46959a713e.png">

![Screenshot 2023-04-04 at 10 46 05](https://user-images.githubusercontent.com/1078012/229754152-e593e9ab-27f9-47f3-98bf-ca54379124b4.png)

I'll just add an extra line with the extra info if there's nothing obvious to copy from.

**Comment by bkonyi** [comment]
Yeah, I don't think that we're actually using most of that data anywhere, even in Observatory. Observatory only seems to display `level`, `message`, and `time`.
