### ISSUE TITLE
Flutter app/Dart compiler crashing when hovering a variable in a debugger breakpoint

### ISSUE THREAD

**Issue by JCKodel** [Dart-Code/Dart-Code#4776]
**Describe the bug**

After reaching a breakpoint, hovering on a variable crashes Flutter application with this error:

```console
Unhandled exception:
FormatException: Invalid radix-10 number (at character 1)
dart:core
^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:126:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:137:16)
#2      int._parse (dart:core-patch/integers_patch.dart:98:12)
#3      int.parse (dart:core-patch/integers_patch.dart:60:12)
#4      parseDefinitionTypes (package:front_end/src/api_prototype/expression_compilation_tools.dart:113:36)
#5      createDefinitionsWithTypes (package:front_end/src/api_prototype/expression_compilation_tools.dart:32:7)
#6      IncrementalCompiler.compileExpression (package:vm/incremental_compiler.dart:219:50)
#7      FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:981:45)
#8      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1452:26)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#12     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#13     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#14     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#15     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:164:13)
#16     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131:7)
#17     StringConversionSink.add (dart:convert/string_conversion.dart:39:5)
#18     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#19     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#22     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#23     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#24     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#25     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#26     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#27     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#28     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#29     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#34     _StreamController._add (dart:async/stream_controller.dart:658:7)
#35     _StreamController.add (dart:async/stream_controller.dart:606:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
#37     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#41     _StreamController._add (dart:async/stream_controller.dart:658:7)
#42     _StreamController.add (dart:async/stream_controller.dart:606:5)
#43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#48     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.


Exited (1).

```

**To Reproduce**
Don't know exactly. I'm just breaking on a breakpoint and hovering a `Type` variable.

That variable come from a `Map<Type, dynamic Function(TDependency Function<TDependency>() get)>`.

**Expected behavior**

To show the `type` variable information.

**Screenshots**

https://github.com/Dart-Code/Dart-Code/assets/379339/a851ebea-ed88-4001-8e89-1ecfeeafc4a9

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.74.0
Flutter extension: 3.74.0 (activated)

App: Visual Studio Code
App Host: desktop
Version: win 1.83.0

Workspace type: Flutter (LSP)

Dart (3.1.3): C:\Users\root\fvm\versions\3.13.6\bin\cache\dart-sdk
Flutter (3.13.6): C:\Users\root\fvm\versions\3.13.6

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`C:\Users\root\fvm\versions\3.13.6\bin\cache\dart-sdk\bin\dart.exe info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.1.3 (stable) (Tue Sep 26 14:25:13 2023 +0000) on "windows_x64"
- on windows / "Windows 10 Pro" 10.0 (Build 22621)
- locale is pt-BR

#### Project info

- sdk constraint: '>=3.1.2 <4.0.0'
- dependencies: crypto, cupertino_icons, dart_mappable, firebase_analytics, firebase_auth, firebase_core, firebase_crashlytics, flutter, google_sign_in, isar, isar_flutter_libs, path_provider, rxdart, sign_in_with_apple
- dev_dependencies: build_runner, dart_mappable_builder, flutter_lints

#### Process info

| Memory | CPU | Elapsed time | Command line |
| -----: | --: | -----------: | ------------ |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |
|   0 MB |  -- |              | dart.exe     |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`C:\Users\root\fvm\versions\3.13.6\bin\flutter.bat doctor -v`

```text
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22621.2361], locale pt-BR)
    • Flutter version 3.13.6 on channel stable at C:\Users\root\fvm\versions\3.13.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ead455963c (9 days ago), 2023-09-26 18:28:17 -0700
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at C:\Users\root\AppData\Local\Android\sdk
    • Platform android-34, build-tools 33.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.4)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34031.279
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] VS Code (version 1.83.0)
    • VS Code at C:\Users\root\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 14 (API 34) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.2361]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 117.0.5938.134
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 117.0.2045.47

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>

**Comment by JCKodel** [comment]
There is another error as well (same function, different line):

```console
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:56362/1VjtncPNhzI=/ws
Unhandled exception:
invalid input
#0      parseDefinitionTypes (package:front_end/src/api_prototype/expression_compilation_tools.dart:110:43)
#1      createDefinitionsWithTypes (package:front_end/src/api_prototype/expression_compilation_tools.dart:32:7)
#2      IncrementalCompiler.compileExpression (package:vm/incremental_compiler.dart:219:50)
#3      FrontendCompiler.compileExpression (package:frontend_server/frontend_server.dart:981:45)
#4      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1452:26)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#9      _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#10     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#11     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:164:13)
#12     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131:7)
#13     StringConversionSink.add (dart:convert/string_conversion.dart:39:5)
#14     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#20     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#21     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#22     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#23     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#24     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#25     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#26     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#29     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#30     _StreamController._add (dart:async/stream_controller.dart:658:7)
#31     _StreamController.add (dart:async/stream_controller.dart:606:5)
#32     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
#33     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#37     _StreamController._add (dart:async/stream_controller.dart:658:7)
#38     _StreamController.add (dart:async/stream_controller.dart:606:5)
#39     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1936:33)
#40     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1379:14)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#44     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.


Exited (1).
```

**Comment by amoyastudio** [comment]
i have this error also, all was ok before the update, but now i'm having this:

#36     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#37     _StreamController._add (dart:async/stream_controller.dart:658:7)
#38     _StreamController.add (dart:async/stream_controller.dart:606:5)
#39     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1934:33)
#40     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1377:14)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#44     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)

3
the Dart compiler exited unexpectedly.
Exited (1)

**Comment by DanTup** [comment]
Is anyone able to share a sample project that triggers this? I've tried hovering over types in code like:

```dart
for (final type in [String, MainApp]) {
  print(type);
}
```

However I get the expected hover and not a crash. Can you also confirm whether it happens only on the device type you're using, or also on something like Windows Desktop?

Thanks!

**Comment by andynewman10** [comment]
I got this error this afternoon on my (unfortunately) complex project.
It happened on VS code, Windows 11, real device (Android 13, Pixel 6a), Flutter 3.13.7.
Sorry I cannot be more helpful.

**Comment by cnayan** [comment]
I see the VS Code Dart Extension crashing in 2 ways:
1. Hovering over a variable when debugging - This happens under special circumstances, but quite often.
2. General crash when debugging. Here is a crash message:
`
===== CRASH =====
ExceptionCode=-1073741819, ExceptionFlags=0, ExceptionAddress=00007FF65FA8FAF0
version=3.1.4 (stable) (Tue Oct 17 14:55:53 2023 +0000) on "windows_x64"
pid=15472, thread=6992, isolate_group=main(00000249FD2A2250), isolate=(nil)(0000000000000000)
os=windows, arch=x64, comp=no, sim=no
isolate_instructions=7ff65f8b6ca0, vm_instructions=7ff65f8b6cb0
fp=249fd35fab0, sp=c4d4efbd18, pc=7ff65fa8faf0
Stack dump aborted because GetAndValidateThreadStackBounds failed.
  pc 0x00007ff65fa8faf0 fp 0x00000249fd35fab0 Dart_IsPrecompiledRuntime+0x1ee370
`

The above crash message was produced when using "block body":
```dart
j = tokens.indexWhere((x) {
  return re!.hasMatch(x.word) == true;
}, idx);
```
But it works fine when it is "expression body":
```dart
j = tokens.indexWhere((x) => re!.hasMatch(x.word) == true, idx);
```

**Comment by DanTup** [comment]
@cnayan the crash you've posted seems like a different issue (a VM crash) - please file that at https://github.com/dart-lang/sdk (and include as much info as you can, including the entire message/output).

The other error posted at the top here (with a Dart stack trace) it's less clear to me what's the cause, so if anyone has steps to reproduce, that would help. A log file (captured with the **Dart: Capture Debugging Logs**) could also be useful, though you'd need to start the logging before starting the debug session and it could end up being a large log (and contain information from your application).

**Comment by mysCod3r** [comment]
some issue.
- When I move the cursor over the variable containing the url, it crashes. If I don't move the cursor to variable, there will be no crash.
- After deleting the async methods under the variable, the same operations will no longer be a problem.
- I thought this issue might be related to the media package I'm using because when I don't enable debug mode, it doesn't execute beyond line 26. (There are no warnings or errors displayed).

note: It seems like media is working in the application, and there's no issue with the drawing of the relevant widgets.

https://github.com/Dart-Code/Dart-Code/assets/76634747/1fb5a009-4f80-4df7-9861-d307b852a6df

**Comment by DanTup** [comment]
@mysCod3r are you able to share a sample project that can trigger this?

**Comment by petrnymsa** [comment]
Experiencing same issue, but cant provide sample project.

```txt
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.22621.2715], locale en-US)
    ! Warning: `flutter` on your path resolves to C:\Users\nymsa\fvm\versions\stable\bin\flutter, which is not inside your current Flutter SDK checkout at C:\Users\nymsa\fvm\versions\3.13.9. Consider adding C:\Users\nymsa\fvm\versions\3.13.9\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\Users\nymsa\fvm\versions\stable\bin\dart, which is not inside your current Flutter SDK checkout at C:\Users\nymsa\fvm\versions\3.13.9. Consider adding C:\Users\nymsa\fvm\versions\3.13.9\bin to the front of your path.
[├ö┬ú├┤] Windows Version (Installed version of Windows is version 10 or higher)
[├ö┬ú├┤] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[├ö┬ú├┤] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.5.3)
    ├ö┬ú├╣ Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[├ö┬ú├┤] Android Studio (version 2021.3)
[├ö┬ú├┤] Android Studio (version 2022.3)
[├ö┬ú├┤] VS Code (version 1.84.2)
[├ö┬ú├┤] Connected device (4 available)
[├ö┬ú├┤] Network resources

! Doctor found issues in 2 categories.

```

VSCode: 1.84.2
DartCode: v3.78.0

**Comment by DanTup** [comment]
Based on https://github.com/dart-lang/sdk/issues/53637#issuecomment-1762305041 this might be an issue that has recently been fixed. If you're seeing this on Flutter 3.13 or earlier, I would recommend upgrading to 3.16 to see if that helps.

**Comment by JCKodel** [comment]
It is working now, thank you.
