### ISSUE TITLE
Cannot run VS code USB debug session on Pixel 6a - works on wireless. Exception reported in log.

### ISSUE THREAD

**Issue by andynewman10** [Dart-Code/Dart-Code#4802]
Only for one application, I cannot start a VS code USB debug session on my Pixel 6a. It always fails. Wireless debugging, on the other hand, always works.

Another application I'm working on does not exhibit the problem.

I am using a USB-C to USB-C cable, on a USB-C-equipped motherboard.

USB charging seems fine on the device (I tried two different cables, to no avail).

Starting a debug session using the same application on my Z5 Compact Android 7.1.1 over USB works fine, but this is using another USB-A to micro-USB cable.

When I start a debug session and it fails, the device becomes disconnected, I can no longer see it in VS code.

**To Reproduce**

When starting a debug session, here is the error I reliably (always) get - I used [Dart: Capture Debugging Logs command](https://dartcode.org/docs/logging/#capture-debugging-logs) to get information about the error:

```
[   +4 ms] Stopping app 'app-debug.apk' on Pixel 6a.
[        ] executing: C:\Users\andy\AppData\Local\Android\sdk\platform-tools\adb.exe -s 29231JEGR03669 shell am force-stop com.XXXXgame.application
[ +232 ms] executing: C:\Users\andy\AppData\Local\Android\sdk\platform-tools\adb.exe -s 29231JEGR03669 shell pm list packages com.XXXXgame.application
[ +170 ms] Installing APK.
[   +1 ms] executing: C:\Users\andy\AppData\Local\Android\sdk\platform-tools\adb.exe -s 29231JEGR03669 install -t -r C:\Users\andy\Documents\repos\gitlab-test\flutter-application\build\app\outputs\flutter-apk\app-debug.apk
[+9684 ms] Performing Streamed Install
           adb: failed to install C:\Users\andy\Documents\repos\gitlab-test\flutter-application\build\app\outputs\flutter-apk\app-debug.apk:
[   +1 ms] Error: ADB exited with exit code 1
[        ] Warning: Failed to install APK.
[   +1 ms] Performing Streamed Install

           adb: failed to install C:\Users\andy\Documents\repos\gitlab-test\flutter-application\build\app\outputs\flutter-apk\app-debug.apk:
[        ] Error launching application on Pixel 6a.
Exited (sigterm)
[   +5 ms] 
#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:662:9)
           <asynchronous suspension>
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)
           <asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#4      CommandRunner.runCommand
command_runner.dart:212
           <asynchronous suspension>
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)
           <asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)
           <asynchronous suspension>
#8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
#10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

**Expected behavior**

No error.

 - Operating System and version: Windows 11
 - VS Code version: 1.83.1
 - Dart extension version: 3.74.0
 - Dart/Flutter SDK version: latest (3.13.7 and related dart version)
 - Target device (if the issue relates to Flutter debugging): Google Pixel 6a, Android 13

Flutter doctor:
 
```
[√] Flutter (Channel stable, 3.13.7, on Microsoft Windows [version 10.0.22000.2538], locale fr-FR)
    • Flutter version 3.13.7 on channel stable at C:\Users\andy\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (9 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\andy\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.0.2)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.0.31919.166
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2022.2)
    • Android Studio at C:\Users\andy\Documents\Applications\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at C:\Users\andy\Documents\Applications\IntelliJ
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.83.1)
    • VS Code at C:\Users\andy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.74.0

[√] Connected device (4 available)
    • E5823 (mobile)    • CB5A28LMYH • android-arm64  • Android 7.1.1 (API 25)
    • Windows (desktop) • windows    • windows-x64    • Microsoft Windows [version 10.0.22000.2538]
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 118.0.5993.71
    • Edge (web)        • edge       • web-javascript • Microsoft Edge 118.0.2088.46
    ! Device 29231JEGR03669 is offline.

[√] Network resources
    • All expected network resources are available.

• No issues found!

```

**Comment by andynewman10** [comment]
I just borrowed a USB-A to USB-C cable and could start a debug session just fine. All USB-C to USB-C cables I have are either faulty, or my USB-C motherboard plug is damaged. Either way, it is not a software issue.

**Comment by DanTup** [comment]
Ah, glad you figured it out!
