### ISSUE TITLE
Cannot launch Flutter 3.19.1 debug session (Android 7, Windows). Was working with 3.16.9 just before Flutter upgrade.

### ISSUE THREAD

**Issue by andynewman10** [Dart-Code/Dart-Code#5006]
**Describe the bug**

Debugging my Flutter app cannot be done. The debug session just dies at the beginning, before the application is launched.

**To Reproduce**

1. Launch VS Code and open a workspace
2. Issue a 'flutter clean' (is there anything I can further do to completely purge my ancient build?)
3. Restart VS Code
4. Issue a 'flutter pub get'
5. Start debugging

**Expected behavior**

The debug session should start, it was starting fine with Flutter 3.19.1.

**Please complete the following information:**

You can run the **Dart: Collect Diagnostic Information** command from the VS Code command palette (`F1`) to easily capture this information or provide it manually.

That's what I did, it finishes with the following log entries (see 3rd line especially for an exception):

```
[9:23:30 PM] [General] [Info] [Launch Flutter (E5823)] <== [Flutter] [  +13 ms] "flutter run" took 42 496ms.
[9:23:30 PM] [DAP] [Info] <== {"seq":30426,"type":"event","body":{"message":"<== [Flutter] [stderr] [91, ...]"},"event":"dart.log"}
[9:23:30 PM] [DAP] [Info] <== {"seq":30427,"type":"event","body":{"category":"stderr","output":"[   +4 ms] \n           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)\n           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:730:9)\n           <asynchronous suspension>\n           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1389:27)\n           <asynchronous suspension>\n           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)\n           <asynchronous suspension>\n           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)\n           <asynchronous suspension>\n           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:355:9)\n           <asynchronous suspension>\n           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)\n           <asynchronous suspension>\n           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:295:5)\n           <asynchronous suspension>\n           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:119:9)\n           <asynchronous suspension>\n           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)\n           <asynchronous suspension>\n           #10     main (package:flutter_tools/executable.dart:90:3)\n           <asynchronous suspension>\n\n\n"},"event":"output"}
[9:23:30 PM] [General] [Info] [Launch Flutter (E5823)] <== [Flutter] [stderr] [91, ...]
[9:23:30 PM] [DAP] [Info] <== {"seq":30428,"type":"event","body":{"message":"<== [Flutter] [  +65 ms] ensureAnalyticsSent: 64ms\n"},"event":"dart.log"}
[9:23:30 PM] [DAP] [Info] <== {"seq":30429,"type":"event","body":{"category":"console","output":"[  +65 ms] ensureAnalyticsSent: 64ms\n"},"event":"output"}
[9:23:30 PM] [DAP] [Info] <== {"seq":30430,"type":"event","body":{"message":"<== [Flutter] [        ] Running 1 shutdown hook\n"},"event":"dart.log"}
[9:23:30 PM] [General] [Info] [Launch Flutter (E5823)] <== [Flutter] [  +65 ms] ensureAnalyticsSent: 64ms
[9:23:30 PM] [General] [Info] [Launch Flutter (E5823)] <== [Flutter] [        ] Running 1 shutdown hook
[9:23:30 PM] [DAP] [Info] <== {"seq":30431,"type":"event","body":{"category":"console","output":"[        ] Running 1 shutdown hook\n"},"event":"output"}
[9:23:30 PM] [DAP] [Info] <== {"seq":30432,"type":"event","body":{"message":"<== [Flutter] [  +10 ms] Shutdown hooks complete\n"},"event":"dart.log"}
[9:23:30 PM] [General] [Info] [Launch Flutter (E5823)] <== [Flutter] [  +10 ms] Shutdown hooks complete
[9:23:30 PM] [DAP] [Info] <== {"seq":30433,"type":"event","body":{"category":"console","output":"[  +10 ms] Shutdown hooks complete\n"},"event":"output"}
[9:23:30 PM] [DAP] [Info] <== {"seq":30434,"type":"event","body":{"message":"<== [Flutter] [        ] exiting with code 1\n"},"event":"dart.log"}
[9:23:30 PM] [DAP] [Info] <== {"seq":30435,"type":"event","body":{"category":"console","output":"[        ] exiting with code 1\n"},"event":"output"}
[9:23:30 PM] [General] [Info] [Launch Flutter (E5823)] <== [Flutter] [        ] exiting with code 1
[9:23:30 PM] [DAP] [Info] <== {"seq":30436,"type":"event","body":{"message":"<== [Flutter] Process exited (1)"},"event":"dart.log"}
[9:23:30 PM] [DAP] [Info] <== {"seq":30437,"type":"event","body":{"output":"\nExited (1).\n"},"event":"output"}
[9:23:30 PM] [DAP] [Info] <== {"seq":30438,"type":"event","body":{},"event":"terminated"}
[9:23:30 PM] [General] [Info] [Launch Flutter (E5823)] <== [Flutter] Process exited (1)
[9:23:30 PM] [DAP] [Info] ==> {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":6}
[9:23:30 PM] [DAP] [Info] <== {"seq":30439,"type":"response","command":"disconnect","request_seq":6,"success":true}
[9:23:30 PM] [DAP] [Info] Stopping debug session a8d5e893-9626-4dbe-84d1-853e8f7eb3a5
[9:23:30 PM] [DAP] [Info] Debug session a8d5e893-9626-4dbe-84d1-853e8f7eb3a5 exit: code: 1, signal: undefined
[9:23:30 PM] [DAP] [Info] Debug session a8d5e893-9626-4dbe-84d1-853e8f7eb3a5 errored: {}
Sat Feb 24 2024 [21:23:44 GMT+0100 (Central European Standard Time)] Log file ended
```

 - Operating System and version: Windows 11, latest updates
 - VS Code version: 1.86.2
 - Dart extension version: v3.82.0
 - Dart/Flutter SDK version: 3.19.1
 - Target device (if the issue relates to Flutter debugging): Android 7.1.1, Sony Z5C

**Comment by DanTup** [comment]
Does this issue reproduce if you run `flutter run` from the terminal?

**Comment by andynewman10** [comment]
Thanks for your quick answer.
It indeed doesn't.

```
Launching lib\main.dart on E5823 in debug mode...
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H
ERROR:D8: com.android.tools.r8.kotlin.H

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform firebase-auth-22.3.1.aar (com.google.firebase:firebase-auth:22.3.1)...
```
I guess I need to investigate this. Ouch, I hope this isn't to Gradle-ly and AGP related, I'm having nightmares about this. So far I have been unable to use AGP 8.x.

I can successfully run a debug session on iOS from my Mac using the same code base.

**Comment by andynewman10** [comment]
I could successfully upgrade to Kotlin 1.9.x and AGP 8.x, it was painful but did work in the end. This is somewhat required for Flutter 3.19.1. The debug session can now be started successfully. Sorry for the false alarm.
