### ISSUE TITLE
"The Flutter Daemon has terminated" when connecting a physical android device in USB tethering mode

### ISSUE THREAD

**Issue by Andrew-Bekhiet** [Dart-Code/Dart-Code#5099]
**Describe the bug**
Flutter Daemon is terminated when connecting a physical android device in USB tethering mode
It works normally when I connect it without tethering mode

**To Reproduce**
1. Connect Android Device
2. Choose USB tethering from Android USB settings

**Expected behavior**
I would have expected that the device wouldn't appear as an available device in devices list and that the daemon continues running normally

**Please complete the following information:**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.89.20240501
Flutter extension: 3.89.20240501 (activated)

App: Visual Studio Code
App Host: desktop
Version: linux 1.88.1

Workspace type: Flutter (LSP)

Dart (3.3.4): /media/androidq/data/flutter/bin/cache/dart-sdk
Flutter (3.19.6): /media/androidq/data/flutter (Linux (linux-x64/linux))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/media/androidq/data/flutter/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.3.4 (stable) (Tue Apr 16 19:56:12 2024 +0000) on "linux_x64"
- on linux / Linux 6.5.0-28-generic "#"29-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar 28 23:46:48 UTC 2024
- locale is en_US.UTF-8

#### Project info

- sdk constraint: '>=3.2.0 <4.0.0'
- dependencies: **irrelevant**
- dev_dependencies: build_runner, flutter_lints, flutter_native_splash, flutter_test, json_serializable
- elided dependencies: 1

#### Process info

| Memory |  CPU | Elapsed time | Command line                                                                           |
| -----: | ---: | -----------: | -------------------------------------------------------------------------------------- |
|  63 MB | 0.1% |        03:59 | dart devtools --machine --allow-embedding                                              |
| 410 MB | 2.0% |        03:59 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.89.20240501 |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/media/androidq/data/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.19.6, on Ubuntu 23.10 6.5.0-28-generic, locale en_US.UTF-8)
    • Flutter version 3.19.6 on channel stable at /media/androidq/data/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/androidq/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/androidq/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2023.2)
    • Android Studio at /home/androidq/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.88.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.89.20240501

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: /home/androidq/Android/Sdk/platform-tools/adb
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:75:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:549:36)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart:518:21)
      <asynchronous suspension>
      #4      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:216:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:739:34)
      <asynchronous suspension>
      #6      Future.any.onValue (dart:async/future.dart:608:5)
      <asynchronous suspension>


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by andrewkolos** [comment]
Yes, once the [change](https://github.com/flutter/flutter/commit/ce822ec8bb15e44de72f5a449c00dedcc21d74e8) lands in the stable channel, we'll get more information about these exceptions (which is included in `flutter doctor` output).

**Comment by DanTup** [comment]
@Andrew-Bekhiet if you can reliably reproduce this issue and are comfortable temporarily switching to Flutter's `master` channel, you might be able to capture more information about the error that might confirm whether it's the same issue noted above.

**Comment by Andrew-Bekhiet** [comment]
Sure

<summary><strong>New output from 'flutter doctor'</strong></summary>

`/media/androidq/data/flutter/bin/flutter doctor -v`

```text
[✓] Flutter (Channel master, 3.22.0-31.0.pre.24, on Ubuntu 23.10 6.5.0-28-generic, locale en_US.UTF-8)
    • Flutter version 3.22.0-31.0.pre.24 on channel master at /media/androidq/data/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e5f7800171 (19 minutes ago), 2024-05-13 07:37:27 -0400
    • Engine revision 0050bf9a80
    • Dart version 3.5.0 (build 3.5.0-148.0.dev)
    • DevTools version 2.36.0-dev.5

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/androidq/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/androidq/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[✓] Android Studio (version 2023.2)
    • Android Studio at /home/androidq/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.89.20240501

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Error: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable: /home/androidq/Android/Sdk/platform-tools/adb
      Error details: Process exited abnormally with exit code 1:
      * daemon not running; starting now at tcp:5037
      ADB server didn't ACK
      Full server startup log: /tmp/adb.1000.log
      Server had pid: 210464
      --- adb starting (pid 210464) ---
      05-13 14:56:14.544 210464 210464 I adb     : main.cpp:63 Android Debug Bridge version 1.0.41
      05-13 14:56:14.544 210464 210464 I adb     : main.cpp:63 Version 35.0.1-11580240
      05-13 14:56:14.544 210464 210464 I adb     : main.cpp:63 Installed as /home/androidq/Android/Sdk/platform-tools/adb
      05-13 14:56:14.544 210464 210464 I adb     : main.cpp:63 Running on Linux 6.5.0-28-generic (x86_64)
      05-13 14:56:14.544 210464 210464 I adb     : main.cpp:63 
      05-13 14:56:14.544 210464 210464 I adb     : auth.cpp:416 adb_auth_init...
      05-13 14:56:14.545 210464 210464 I adb     : auth.cpp:152 loaded new key from '/home/androidq/.android/adbkey' with fingerprint 2B3010E4542B30344A977C856E06156CB9032BF90E32EB577A4C6C84796F9594
      05-13 14:56:14.545 210464 210464 I adb     : auth.cpp:391 adb_auth_inotify_init...
      05-13 14:56:15.544 210464 210464 E adb     : usb_libusb.cpp:571 failed to open device: Access denied (insufficient permissions)
      05-13 14:56:15.544 210464 210464 I adb     : transport.cpp:1150 RZ8N21PFJGM: connection terminated: failed to open device: Access denied (insufficient permissions)

      * failed to start daemon
      adb: failed to check server version: cannot connect to daemon
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:75:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:548:36)
      <asynchronous suspension>
      #3      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
      <asynchronous suspension>
      #4      DeviceManager.refreshAllDevices (package:flutter_tools/src/device.dart:218:40)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:715:34)
      <asynchronous suspension>
      #6      Future.any.onValue (dart:async/future.dart:618:5)
      <asynchronous suspension>


[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by DanTup** [comment]
@Andrew-Bekhiet thanks! This looks a little different to https://github.com/flutter/flutter/issues/125971#issuecomment-2101093702 since it seems less of an intermittent connectivity issue:

```
      05-13 14:56:14.545 210464 210464 I adb     : auth.cpp:391 adb_auth_inotify_init...
      05-13 14:56:15.544 210464 210464 E adb     : usb_libusb.cpp:571 failed to open device: Access denied (insufficient permissions)
      05-13 14:56:15.544 210464 210464 I adb     : transport.cpp:1150 RZ8N21PFJGM: connection terminated: failed to open device: Access denied (insufficient permissions)
```

What happens if you run `/home/androidq/Android/Sdk/platform-tools/adb devices -l` directly in a terminal, do you see a similar error?

**Comment by Andrew-Bekhiet** [comment]
Yes same error

```
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 1479482
--- adb starting (pid 1479482) ---
05-13 16:39:35.358 1479482 1479482 I adb     : main.cpp:63 Android Debug Bridge version 1.0.41
05-13 16:39:35.358 1479482 1479482 I adb     : main.cpp:63 Version 35.0.1-11580240
05-13 16:39:35.358 1479482 1479482 I adb     : main.cpp:63 Installed as /home/androidq/Android/Sdk/platform-tools/adb
05-13 16:39:35.358 1479482 1479482 I adb     : main.cpp:63 Running on Linux 6.5.0-28-generic (x86_64)
05-13 16:39:35.358 1479482 1479482 I adb     : main.cpp:63 
05-13 16:39:35.358 1479482 1479482 I adb     : auth.cpp:416 adb_auth_init...
05-13 16:39:35.358 1479482 1479482 I adb     : auth.cpp:152 loaded new key from '/home/androidq/.android/adbkey' with fingerprint 2B3010E4542B30344A977C856E06156CB9032BF90E32EB577A4C6C84796F9594
05-13 16:39:35.358 1479482 1479482 I adb     : auth.cpp:391 adb_auth_inotify_init...
05-13 16:39:36.358 1479482 1479482 E adb     : usb_libusb.cpp:571 failed to open device: Access denied (insufficient permissions)
05-13 16:39:36.358 1479482 1479482 I adb     : transport.cpp:1150 RZ8N21PFJGM: connection terminated: failed to open device: Access denied (insufficient permissions)

* failed to start daemon
adb: failed to check server version: cannot connect to daemon

```

**Comment by DanTup** [comment]
@Andrew-Bekhiet thanks for confirming. In that case I think this should be reported against the Android SDK. I think the best way to report these is through the IDE or link detailed at https://developer.android.com/studio/report-bugs#report-bug

It's probably worth including the log file that's generated (your output shows "Full server startup log: /tmp/adb.1000.log").

I think it's probably also worth filing an issue in Flutter (https://github.com/flutter/flutter/) because even if ADB is completely failing and broken, perhaps it shouldn't crash the Flutter tool, maybe it should keep running and just not return any devices (maybe @christopherfujino has opinions on this.. it might make the issue less visible, but maybe the solution to that is to have a way to report errors rather than terminating?).

**Comment by Andrew-Bekhiet** [comment]
Ok great, I will close this issue and open an issue in Android SDK later
I will wait for [christopherfujino](https://github.com/christopherfujino) opinion on this, then maybe open an issue in flutter repo

**Comment by vshvedov** [comment]
@Andrew-Bekhiet you can start adb daemon as root -- at least it will solve the permission issue for now
