### ISSUE TITLE
Running tests in sub dart-only package of a flutter pub-workspace

### ISSUE THREAD

**Issue by mrgnhnt96** [Dart-Code/Dart-Code#5375]
**Describe the bug**
I am not able to run tests within a dart-only package which is within a pub-workspace that contains separate flutter sub packages.

Here is my file structure (vaguely)

```text
.
├── packages
│   ├── application (dart only)
│   │   ├── test
│   │   │   └── some_test.dart
│   │   └── pubspec.yaml
│   └── ui (flutter)
│       └── pubspec.yaml
├── pubspec.yaml
└── pubspec.lock
```

When trying to run any tests using the play buttons next to tests or the `Run | Debug` quick runners above the `main` function, 

<div>
  <img width="131" alt="image" src="https://github.com/user-attachments/assets/9f967926-ff05-4b48-9869-8dab28476f40" />
  <img width="141" alt="image" src="https://github.com/user-attachments/assets/8326be90-d04c-495d-9dcc-b758a016f313" />
</div>

The error that I get when running these tests is:
```console
The current Flutter SDK version is 3.19.5.

Because <package-name> depends on patrol_finders 2.1.2 which requires Flutter SDK version >=3.22.0, version solving failed.


Exited (255).
```

While I understand that flutter is being used in the workspace, I would still expect `dart` to be the command used in the sub packages that don't depend on Flutter.

---

It's important to note that when I run `dart test` the output is as expected

```console
$ dart test test/lib/blocs/host_profile_bloc_test.dart
Building package executable... 
Built test:test.
00:00 +14: All tests passed!                        
```

<details>
<summary>Dart: Collection Diagnostic Information</summary>

**!! ⚠️ PLEASE REVIEW THIS REPORT FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!**

<details>

<summary><strong>Workspace Environment</strong></summary>

```text
Dart Code extension: 3.103.20241211
Flutter extension: 3.103.20241202 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.96.0

Workspace type: Dart, Flutter (LSP)
Workspace name: cushions

Dart (3.6.0): /Users/morgan/fvm/versions/3.27.1/bin/cache/dart-sdk
Flutter (3.27.1): /Users/morgan/fvm/versions/3.27.1 (Morgans iPhone (ios/ios))

```

</details>

<details>

<summary><strong>Output from 'dart info'</strong></summary>

`/Users/morgan/fvm/versions/3.27.1/bin/cache/dart-sdk/bin/dart info`

If providing this information as part of reporting a bug, please review the information
below to ensure it only contains things you're comfortable posting publicly.

#### General info

- Dart 3.6.0 (stable) (Thu Dec 5 07:46:24 2024 -0800) on "macos_arm64"
- on macos / Version 15.0 (Build 24A335)
- locale is en-US

#### Process info

|  Memory |  CPU | Elapsed time | Command line                                                                               |
| ------: | ---: | -----------: | ------------------------------------------------------------------------------------------ |
|   27 MB | 0.0% |        42:27 | dart devtools --machine --allow-embedding --dtd-uri ws:<path>/kVehX8_d3KU=                 |
| 3566 MB | 0.0% |        42:28 | dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.103.20241211    |
|   13 MB | 0.0% |     19:56:23 | dart test test/.test_optimizer.dart --coverage=coverage --test-randomize-ordering-seed random |
|   32 MB | 0.0% |        42:28 | dart tooling-daemon --machine                                                              |
|   65 MB | 0.0% |        42:28 | flutter_tools.snapshot daemon                                                              |

</details>

<details>

<summary><strong>Output from 'flutter doctor'</strong></summary>

`/Users/morgan/fvm/versions/3.27.1/bin/flutter doctor -v`

```text
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.27.1 on channel stable at /Users/morgan/fvm/versions/3.27.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (3 days ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/morgan/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/morgan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.96.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.103.20241202

[✓] VS Code (version 1.90.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.89.20240501

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • Morgans iPhone (mobile)         • [REDACTED]                 • ios            • iOS 18.2 22C152
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 131.0.6778.141
    ! Error: Browsing on the local area network for Morgans iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

</details>
</details>

**Comment by mrgnhnt96** [comment]
I've also noticed this behavior when running `Pub: Get Packages`, `Dart: Add Dependency` `Dart: Add Dev Dependency`

**Comment by DanTup** [comment]
I don't seem to be able to reproduce this.. I created a Dart and Flutter app both in `packages/` and set up the workspace in an ancestor `pubspec.yaml`, but running the Dart tests works fine:

![image](https://github.com/user-attachments/assets/580f1943-d399-4209-b001-d7cb352b80b5)

However, it's not clear to me what the dependencies are in your project:

> Because <package-name> depends on patrol_finders 2.1.2 which requires Flutter SDK version >=3.22.0, version solving failed.

What is `<package-name>`?

If you're able to provide steps to reproduce, or a sample project that triggers the issue, that will make it much easier to debug. Thanks!

**Comment by mrgnhnt96** [comment]
I redacted the name of the package and replaced it with <package-name>.

I attached
[dependencies.json](https://github.com/user-attachments/files/18200422/dependencies.json)
 the list of dependencies and each of their dependencies

I'll see if I can get a public repro for you

**Comment by mrgnhnt96** [comment]
Interesting.. I was able to get the same result as you. However after adding `patrol_finders` to my dev dependencies I started getting an error

```console
Because ui depends on patrol_finders any which requires the Flutter SDK, version solving failed.

Flutter users should use `flutter pub` instead of `dart pub`.
```

I then removed `patrol_finders` from the dev_dependencies and I started getting this error

```console
Because ui depends on flutter_test from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

Flutter users should use `flutter pub` instead of `dart pub`.
```

Removing `flutter_test` got me to this error

```console
Because ui depends on flutter from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.

Flutter users should use `flutter pub` instead of `dart pub`.
```

And removing flutter, I was finally able to run the test

https://github.com/mrgnhnt96/workspace_bug_repro

**Comment by mrgnhnt96** [comment]
The only way that I am able to use the play buttons within VsCode is by commenting out

```yaml
resolution: workspace
```

Then running

```console
dart pub get
```

After that, everything works as expected, until I revert the changes and get the dependencies again

**Comment by mrgnhnt96** [comment]
Its all good! Hope you had a great New Year!

Yes I have a minimal repo here [https://github.com/mrgnhnt96/workspace_bug_repro](https://github.com/mrgnhnt96/workspace_bug_repro).

> Do I understand correctly that you're using patrol_finders as a dev dependency of a Dart-only project? 

No, I am using `patrol_finder`within the `ui` (flutter) package of the same workspace

```txt
.
├── application
│   └── pubspec.yaml # dart only
├── ui
│   └── pubspec.yaml # flutter
└── pubspec.yaml # flutter (workspace root)
```

_My previous comment was a little vague, sorry about that. I edited the comment to be a bit more descriptive_

**Comment by SupposedlySam** [comment]
Followed your steps @mrgnhnt96 and it works great for me as well

![image](https://github.com/user-attachments/assets/55e7bd55-f71f-409b-87d9-304f0dc65181)

Here's my `fvm flutter doctor -v` output
```sh
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.1.1 24B91 darwin-arm64, locale en-US)
    • Flutter version 3.27.0 on channel stable at /Users/e86258/fvm/versions/3.27.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (4 weeks ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2
```

and my versions of the dart-code extension
```sh
cursor --list-extensions --show-versions | grep -i dart
dart-code.dart-code@3.102.0
dart-code.flutter@3.102.0
```

**Comment by SupposedlySam** [comment]
My guess is that your global version of Flutter/Dart on your path is different than what you expect.

Does running `flutter doctor -v` and using vscode's command palette to launch `flutter doctor` (cmd+shift+p) point to the same version / location?

![image](https://github.com/user-attachments/assets/07690e98-e6b6-4179-a9ba-2d69b66528b5)

**Comment by mrgnhnt96** [comment]
Here's the info you requested

![image](https://github.com/user-attachments/assets/1596e05a-1f84-4644-8460-76e698c883c8)

<details>
<summary>Debugging Logs</summary>

```console
!! ⚠️ PLEASE REVIEW THIS LOG FOR SENSITIVE INFORMATION BEFORE SHARING ⚠️ !!
Dart Code extension: 3.102.0
Flutter extension: 3.103.20241202 (activated)

App: Visual Studio Code
App Host: desktop
Version: mac 1.96.3

Workspace type: Dart, Flutter (LSP)
Workspace name: workspace_repro

Dart (3.6.0): /Users/morgan/fvm/versions/3.27.1/bin/cache/dart-sdk
Flutter (3.27.1): /Users/morgan/fvm/versions/3.27.1 (No device)


Logging Categories:
    General, AnalyzerTiming, CommandProcesses, DartTest, DartToolingDaemon, DAP, VmService, DevTools, FlutterDaemon, FlutterRun, FlutterTest, WebDaemon

Wed Jan 15 2025 [12:10:41 GMT-0700 (Mountain Standard Time)] Log file started
[12:10:42 PM] [General] [Info] Starting debug session...
[12:10:42 PM] [General] [Info]     workspace: /Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro
[12:10:42 PM] [General] [Info]     program  : /Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro/packages/application/test/application_test.dart
[12:10:42 PM] [General] [Info] Setting cwd based on likely entry point: /Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro
[12:10:42 PM] [General] [Info] Using workspace as cwd: /Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro
[12:10:42 PM] [General] [Info] Found better project root to use as cwd: /Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro/packages/application
[12:10:42 PM] [General] [Info] Program (/Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro/packages/application/test/application_test.dart) not recognised as Flutter or Web, will use Dart debugger
[12:10:42 PM] [General] [Info] Detected launch project as Dart
[12:10:42 PM] [General] [Info] Detected launch project as a Test project
[12:10:42 PM] [General] [Info] Using DartTest debug adapter for this session
[12:10:42 PM] [General] [Info] Checking for errors before launching
[12:10:42 PM] [General] [Info] Debug session starting...
    {
        "name": "Dart ",
        "noDebug": true,
        "request": "launch",
        "type": "dart",
        "program": "/Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro/packages/application/test/application_test.dart",
        "dartCodeDebugSessionID": "session-c5f92",
        "projectRootPath": "/Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro/packages/application",
        "cwd": "/Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro/packages/application",
        "toolEnv": {
            "FLUTTER_HOST": "VSCode",
            "PUB_ENVIRONMENT": "vscode.dart-code"
        },
        "sendLogsToClient": true,
        "sendCustomProgressEvents": true,
        "allowAnsiColorOutput": true,
        "additionalProjectPaths": [
            "/Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro"
        ],
        "args": [],
        "vmAdditionalArgs": [],
        "toolArgs": [],
        "vmServicePort": 0,
        "dartSdkPath": "/Users/morgan/fvm/versions/3.27.1/bin/cache/dart-sdk",
        "maxLogLineLength": 2000,
        "debugSdkLibraries": true,
        "debugExternalPackageLibraries": true,
        "showDartDeveloperLogs": true,
        "evaluateGettersInDebugViews": true,
        "showGettersInDebugViews": true,
        "evaluateToStringInDebugViews": true,
        "debuggerType": 1
    }
[12:10:42 PM] [General] [Info] Using dart_test debugger for DartTest
[12:10:42 PM] [General] [Info] SDK DAP setting is true, set by sdkDaps experiment
[12:10:42 PM] [General] [Info] Running SDK DAP Dart VM in undefined: /Users/morgan/fvm/versions/3.27.1/bin/cache/dart-sdk/bin/dart debug_adapter    --test and options {"env":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"}}
[12:10:42 PM] [DAP] [Info] Starting debug session ec82f877-7fd4-4109-8365-0c490a338903
[12:10:42 PM] [DAP] [Info] ==> {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"dart","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en","supportsProgressReporting":true,"supportsInvalidatedEvent":true,"supportsMemoryReferences":true,"supportsArgsCanBeInterpretedByShell":true,"supportsMemoryEvent":true,"supportsStartDebuggingRequest":true,"supportsANSIStyling":true,"supportsDartUris":true},"type":"request","seq":1}
[12:10:42 PM] [DAP] [Info] <== {"seq":1,"type":"response","body":{"exceptionBreakpointFilters":[{"default":false,"filter":"All","label":"All Exceptions"},{"default":true,"filter":"Unhandled","label":"Uncaught Exceptions"}],"supportsClipboardContext":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsDelayedStackTraceLoading":true,"supportsEvaluateForHovers":true,"supportsLogPoints":true,"supportsRestartFrame":true,"supportsRestartRequest":false,"supportsTerminateRequest":true,"supportsValueFormattingOptions":true,"supportsANSIStyling":true},"command":"initialize","request_seq":1,"success":true}
[12:10:42 PM] [DAP] [Info] <== {"seq":2,"type":"event","body":{},"event":"initialized"}
[12:10:42 PM] [DAP] [Info] ==> {"command":"launch","arguments":{"name":"Dart ","noDebug":true,"request":"launch","type":"dart","program":"/Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro/packages/application/test/application_test.dart","dartCodeDebugSessionID":"session-c5f92","projectRootPath":"/Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro/packages/application","cwd":"/Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro/packages/application","toolEnv":{"FLUTTER_HOST":"VSCode","PUB_ENVIRONMENT":"vscode.dart-code"},"sendLogsToClient":true,"sendCustomProgressEvents":true,"allowAnsiColorOutput":true,"additionalProjectPaths":["/Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro"],"args":[],"vmAdditionalArgs":[],"toolArgs":[],"vmServicePort":0,"dartSdkPath":"/Users/morgan/fvm/versions/3.27.1/bin/cache/dart-sdk","maxLogLineLength":2000,"debugSdkLibraries":true,"debugExternalPackageLibraries":true,"showDartDeveloperLogs":true,"evaluateGettersInDebugViews":true,"showGettersInDebugViews":true,"evaluateToStringInDebugViews":true,"debuggerType":1,"__sessionId":"ec82f877-7fd4-4109-8365-0c490a338903"},"type":"request","seq":2}
[12:10:42 PM] [DAP] [Info] ==> {"command":"configurationDone","type":"request","seq":3}
[12:10:42 PM] [DAP] [Info] <== {"seq":3,"type":"response","command":"configurationDone","request_seq":3,"success":true}
[12:10:42 PM] [DAP] [Info] ==> {"command":"threads","type":"request","seq":4}
[12:10:42 PM] [DAP] [Info] <== {"seq":4,"type":"response","command":"launch","request_seq":2,"success":true}
[12:10:42 PM] [DAP] [Info] <== {"seq":5,"type":"response","body":{"threads":[]},"command":"threads","request_seq":4,"success":true}
[12:10:42 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"debugSession":{"debuggerType":"DartTest","id":"ec82f877-7fd4-4109-8365-0c490a338903","name":"Dart ","projectRootPath":"/Users/morgan/Documents/develop.nosync/flutter_projects/workspace_repro/packages/application"}},"eventKind":"debugSessionStarted","streamId":"Editor"}}
[12:10:42 PM] [DAP] [Info] ==> {"command":"source","arguments":{"sourceReference":0,"source":{"path":"replinput"}},"type":"request","seq":5}
[12:10:42 PM] [DAP] [Info] <== {"seq":6,"type":"response","body":{"error":{"format":"{message}","id":1,"variables":{"message":"Bad state: source reference is no longer valid","stack":"#0      DartDebugAdapter.sourceRequest (package:dds/src/dap/adapters/dart.dart:1806:7)\n#1      BaseDebugAdapter.handle (package:dds/src/dap/base_debug_adapter.dart:141:20)\n#2      BaseDebugAdapter.handleIncomingRequest (package:dds/src/dap/base_debug_adapter.dart:449:7)\n#3      BaseDebugAdapter._handleIncomingMessage (package:dds/src/dap/base_debug_adapter.dart:311:7)\n#4      ByteStreamServerChannel._readMessage (package:dds/src/dap/protocol_stream.dart:82:18)\n#5      ByteStreamServerChannel.listen.<anonymous closure> (package:dds/src/dap/protocol_stream.dart:53:24)\n#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1609:10)\n#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:366:11)\n#8      _DelayedData.perform (dart:async/stream_impl.dart:542:14)\n#9      _PendingEvents.handleNext (dart:async/stream_impl.dart:647:11)\n#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:618:7)\n#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)\n#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)\n#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)\n#14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)\n"}}},"command":"source","message":"Bad state: source reference is no longer valid","request_seq":5,"success":false}
[12:10:43 PM] [DAP] [Info] <== {"seq":7,"type":"event","body":{"category":"stderr","output":"Because ui depends on flutter_test from sdk which doesn't exist (the Flutter SDK is not available), version solving failed.\n"},"event":"output"}
[12:10:43 PM] [DAP] [Info] <== {"seq":8,"type":"event","body":{"category":"stderr","output":"\n"},"event":"output"}
[12:10:43 PM] [DAP] [Info] <== {"seq":9,"type":"event","body":{"category":"stderr","output":"Flutter users should use `flutter pub` instead of `dart pub`.\n"},"event":"output"}
[12:10:43 PM] [DAP] [Info] <== {"seq":10,"type":"event","body":{"category":"stderr","output":"\n"},"event":"output"}
[12:10:43 PM] [DAP] [Info] <== {"seq":11,"type":"event","body":{"output":"\nExited (255).\n"},"event":"output"}
[12:10:43 PM] [DAP] [Info] <== {"seq":12,"type":"event","body":{},"event":"terminated"}
[12:10:43 PM] [DAP] [Info] ==> {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":6}
[12:10:43 PM] [DAP] [Info] <== {"seq":13,"type":"response","command":"disconnect","request_seq":6,"success":true}
[12:10:43 PM] [DAP] [Info] Stopping debug session ec82f877-7fd4-4109-8365-0c490a338903
[12:10:43 PM] [DAP] [Info] Debug session ec82f877-7fd4-4109-8365-0c490a338903 errored: {}
[12:10:43 PM] [DAP] [Info] Debug session ec82f877-7fd4-4109-8365-0c490a338903 exit: code: undefined, signal: undefined
[12:10:43 PM] [DartToolingDaemon] [Info] ==> {"jsonrpc":"2.0","method":"postEvent","params":{"eventData":{"debugSessionId":"ec82f877-7fd4-4109-8365-0c490a338903"},"eventKind":"debugSessionStopped","streamId":"Editor"}}
Wed Jan 15 2025 [12:10:45 GMT-0700 (Mountain Standard Time)] Log file ended
```
</details>

<details>
<summary>Flutter: Run Flutter Doctor</summary>

```console
[flutter] flutter doctor -v
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.0 24A335 darwin-arm64, locale en-US)
    • Flutter version 3.27.1 on channel stable at /Users/morgan/fvm/versions/3.27.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 17025dd882 (4 weeks ago), 2024-12-17 03:23:09 +0900
    • Engine revision cb4b5fff73
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/morgan/Library/Android/sdk
    • Platform android-35, build-tools 34.0.0
    • ANDROID_HOME = /Users/morgan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16A242d
    • CocoaPods version 1.16.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0-17.0.10b1087.21-11572160)

[✓] VS Code (version 1.96.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.103.20241202

[✓] VS Code (version 1.90.0-insider)
    • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
    • Flutter extension version 3.89.20240501

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile)     • emulator-5554             • android-arm64  • Android 14 (API 34) (emulator)
    • Morgans iPhone (mobile)         • 00008140-0004510C2E88801C • ios            • iOS 18.3 22D5034e
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 15.0 24A335 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 15.0 24A335 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 132.0.6834.83
    ! Error: Browsing on the local area network for Morgans iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
exit code 0
```
</details>

I even tried creating a new profile with no settings, only the dart code extension, and I got the same result.

**Comment by DanTup** [comment]
Thanks - unfortunately there's nothing indicative of the issue in the log. Is it possible you are able to zip up your repro folder entirely (including the `.dart_tool` folder) and share it? You can remove any `build` folder if it exists so it shouldn't be too big.

**Comment by mrgnhnt96** [comment]
[repro.zip](https://github.com/user-attachments/files/18505622/repro.zip)

Here you go! Hopefully this shows something helpful. If it helps with the rabbit chase, I'm happy to jump onto a video call or something.

**Comment by DanTup** [comment]
Thanks! The repro didn't help directly, as I still couldn't reproduce - however I diffed our logs and noticed in mine `FLUTTER_ROOT` was being set and it's not in yours.

I did some digging, and found that we (the extension) only sets `FLUTTER_ROOT` if it's _not_ already set. This makes me think you may have a `FLUTTER_ROOT` env var set. So I tested with that set for me, and I still couldn't repro - however if I set it to an _invalid_ location, then I do repro your issue.

So, my next question is what is your `FLUTTER_ROOT` env variable set to? (I think running `echo $FLUTTER_ROOT` in the built-in terminal should give you the same value we'd see). If it's not a real Flutter SDK, can you try removing (or fixing) it?

**Comment by mrgnhnt96** [comment]
Ah, that’s very interesting. I checked all my dotfiles, but I couldn’t find any `FLUTTER_ROOT` variable. To confirm, I echoed the variable in the system terminal, and as expected, it didn’t exist.

![Image](https://github.com/user-attachments/assets/1ddbf7f9-8725-4739-be5f-6791df570049)

However, when I ran the same command in the integrated terminal, I saw:

![Image](https://github.com/user-attachments/assets/9c5962ee-5b02-4b4e-9c74-8edf75a87755)

This path doesn’t exist, which aligns with your observation:

> if I set it to an invalid location, then I do repro your issue

So where did this path come from?

I’ve searched to figure out what might be setting the `FLUTTER_ROOT variable` but haven’t had any luck so far. I went through all relevant settings.json files in VSCode (workspace, and user) where `dart.flutterSdkPath(s)` might be configured. These settings were commented out a while back during debugging:

```json5
    "dart.flutterSdkPaths": ["~/fvm/versions"],
    "dart.sdkPaths": [
        "~/.dvm/darts/"
    ],
```

I also checked VSCode Insiders to see if it was setting `FLUTTER_ROOT`. It wasn’t. In fact, I could run tests as expected using "Run" there.

Interestingly, I noticed the setting `"dart.addSdkToTerminalPath": false` in my configuration. When I changed this value to true, the `FLUTTER_ROOT` variable disappeared.  (coincidence maybe? 🤔 )

Now that the `FLUTTER_ROOT` variable is gone, I can run tests as expected 🚀. However, I still don’t know what was causing it to be set in the first place. If you have any ideas, I’d love to hear them. Otherwise, I think this issue can be considered resolved.

Thanks for helping me figure this out!

---

> If the workspace references Flutter, does this mean running dart test for a Dart project within the workspace should also require a Flutter SDK?

If that’s the case, would it mean that `dart test`, `dart pub`, etc., would stop working for pure Dart packages in a workspace that includes any Flutter dependency?

**Comment by DanTup** [comment]
> Interestingly, I noticed the setting "dart.addSdkToTerminalPath": false in my configuration. When I changed this value to true, the FLUTTER_ROOT variable disappeared. (coincidence maybe? 🤔 )

Coincidence I think, that setting only affects `PATH`.

Is it possible you have had VS Code open for a long time, and it had inherited this env variable at some point in the past? Environment variables are passed to processes when they spawn from the parent, but they don't get updated. So if you launched VS Code from a terminal that had that variable set, it would keep it until you restarted VS Code (possibly all of the windows, because they may share a root process).

I would probably try rebooting (or at least, closing all VS Code instances and opening again) to verify the issue doesn't come back. If not, we can close this, and if it does, we can try to figure out where it's coming from.

Thanks!

**Comment by mrgnhnt96** [comment]
Not sure exactly what caused it, I have reset my computer a couple of times at least within the time that this issue has been open. And I have definitely closed VSCode completely too.

I reset my computer and everything is working as expected now. Hopefully it doesn't happen again!

**Comment by DanTup** [comment]
Great, glad it's sorted - if it does come back, I would first try a VS Code restart to see if that fixes it (if you're launching VS Code from a terminal, first check if it's defined in that terminal), and we might need to try to understand where it's coming from.

**Comment by sigurdm** [comment]
>  does this mean running dart test for a Dart project within the workspace should also require a Flutter SDK?
Yeah - I think so - because we require the whole workspace to resolve together, and that requires the flutter sdk (though `bin/dart` from a flutter sdk should be fine).

**Comment by vonhezhou** [comment]
for anyone came here:
this has some thing to do with having links in dart/flutter executable path. especially when using fvm.
e.g. 

- ~/fvm/default/bin is added to path
- ~/fvm/default is a link to ~/fvm/versions/stable
- so ~/fvm/default/bin/dart is actually ~/fvm/versions/stable/bin/dart

solution:

add ~/fvm/versions/stable/bin to path instead.

**Comment by DanTup** [comment]
@vonhezhou if you're able to reliably repro this, would you mind filing a new issue and with as much detail as possible so I can try to repro this? Please also include your versions of VS Code, the Dart extension, `fvm`, and what OS you're on. Thanks!

**Comment by vonhezhou** [comment]
> [@vonhezhou](https://github.com/vonhezhou) if you're able to reliably repro this, would you mind filing a new issue and with as much detail as possible so I can try to repro this? Please also include your versions of VS Code, the Dart extension, `fvm`, and what OS you're on. Thanks!

i can reproduce it with the provided minimal repo.zip. i fix it by:

1. remove FLUTTER_ROOT env variable and 
2. change path from "~/fvm/default/bin" to "~/fvm/versions/stable/bin"
3. reboot

I try added these back, reboot. can't reproduce any more. Sorry
