### ISSUE TITLE
Diagnostics provider may try to use a disposed diagnostics collection

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#792]
Since we can't check if it's disposed, we my need to make this provider disposable and have a flag?

```
1) "after each" hook:
     Uncaught Error: illegal state - object is disposed
      at s.e._checkDisposed (.vscode-test/stable/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:599:811)
      at s.e.set (.vscode-test/stable/VSCode-linux-x64/resources/app/out/vs/workbench/node/extensionHostProcess.js:597:669)
      at DartDiagnosticProvider.handleErrors (out/src/providers/dart_diagnostic_provider.js:2:534)
      at DartDiagnosticProvider.analyzer.registerForAnalysisErrors.es (out/src/providers/dart_diagnostic_provider.js:1:5965)
      at subscriptions.slice.forEach.sub (src/services/stdio_service.ts:11:59)
      at Array.forEach (native)
      at Analyzer.notify (src/services/stdio_service.ts:11:59)
      at Analyzer.handleNotification (src/analysis/analyzer_gen.ts:4:14)
      at Analyzer.handleMessage (src/services/stdio_service.ts:11:59)
      at fullBuffer.split.filter.forEach.m (src/services/stdio_service.ts:10:46)
      at Array.forEach (native)
      at Analyzer.processMessageBuffer (src/services/stdio_service.ts:10:46)
      at Socket.process.stdout.on.data (src/services/stdio_service.ts:4:44)
      at readableAddChunk (_stream_readable.js:178:18)
      at Socket.Readable.push (_stream_readable.js:136:10)
      at Pipe.onread (net.js:560:20)
```

**Comment by DanTup** [comment]
This particular instance was caused by the extension trying to do a silent reload while it was analyzing (because in tests I was changing the log file). Similar thing could happen to users if they edit the config while we're analyzing.

**Comment by DanTup** [comment]
Looks like we don't clean up the subscriptions when we close an stdio_service. Possible fix may be something like this:

<img width="1048" alt="screen shot 2018-05-16 at 1 25 19 pm" src="https://user-images.githubusercontent.com/1078012/40116801-b4ef519c-590c-11e8-8725-dc5ffacffe3f.png">
