### ISSUE TITLE
Debugger tests on Travis Linux/macOS get weird paths starting with three slashes

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#795]
```text
2) flutter test debugger stops at a breakpoint:
      AssertionError: stopped location: path mismatch
      + expected - actual
      -///home/travis/build/Dart-Code/Dart-Code/test/test_projects/flutter_hello_world/test/hello_test.dart
      +/home/travis/build/Dart-Code/Dart-Code/test/test_projects/flutter_hello_world/test/hello_test.dart
      
      at DebugClient.assertPath (node_modules/vscode-debugadapter-testsupport/src/debugClient.ts:417:11)
      at waitForEvent.then.then.response (node_modules/vscode-debugadapter-testsupport/src/debugClient.ts:349:10)
      at <anonymous>
```

**Comment by DanTup** [comment]
Opened https://github.com/flutter/flutter/issues/16352

**Comment by DanTup** [comment]
Seems fixed.
