### ISSUE TITLE
The Dart Analyzer has terminated.

### ISSUE THREAD

**Issue by festelo** [Dart-Code/Dart-Code#894]
Happens after starting any project. (Even creating new) 
Worked fine until I upgraded flutter to beta 3

Flutter doctor:
```
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 10.0.16299.371], locale ru-RU)
    • Flutter version 0.3.2 at C:\flutter
    • Framework revision 44b7e7d3f4 (3 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Users\eee\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[√] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Dart Code extension version 2.12.1

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

From debug tools:
```
Analysis failed: e:\Projects\flutter\speakit\test\widget_test.dart
```

```
NoSuchMethodError: The getter 'lineStarts' was called on null.
Receiver: null
Tried calling: lineStarts
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:481)
#2      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#3      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#4      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#5      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#6      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#7      FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#8      FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#9      FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#10     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#11     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#12     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#13     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#14     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#15     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#16     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#17     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#18     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#19     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#20     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#21     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#22     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#23     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#24     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#25     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#26     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#27     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#28     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#29     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#30     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#31     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#32     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#33     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#34     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#35     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#36     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#37     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:528)
#38     FileSystemState.getFileForUri (package:analyzer/src/dart/analysis/file_state.dart:829)
#39     FileState._fileForRelativeUri (package:analyzer/src/dart/analysis/file_state.dart:591)
#40     FileState.refresh (package:analyzer/src/dart/analysis/file_state.dart:523)
#41     FileSystemState.getFileForPath (package:analyzer/src/dart/analysis/file_state.dart:789)
#42     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1147)
<asynchronous suspension>
#43     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1008)
<asynchronous suspension>
#44     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1925)
<asynchronous suspension>
#45     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1868)
#46     new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#47     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#48     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#49     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#50     _rootRun (dart:async/zone.dart:1126)
#51     _CustomZone.run (dart:async/zone.dart:1023)
#52     runZoned (dart:async/zone.dart:1501)
#53     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#54     Driver.start (package:analysis_server/src/server/driver.dart:443)
#55     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#56     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#57     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```
```
NoSuchMethodError: The getter 'libraryNameOffset' was called on null.
Receiver: null
Tried calling: libraryNameOffset
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      FileState.isPart (package:analyzer/src/dart/analysis/file_state.dart:262)
#2      _TopLevelNameDeclarationsTask.perform (package:analyzer/src/dart/analysis/driver.dart:2376)
<asynchronous suspension>
#3      AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:974)
<asynchronous suspension>
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:1925)
<asynchronous suspension>
#5      AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:1868)
#6      new AnalysisServer (package:analysis_server/src/analysis_server.dart:395)
#7      SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:79)
#8      StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37)
#9      Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444)
#10     _rootRun (dart:async/zone.dart:1126)
#11     _CustomZone.run (dart:async/zone.dart:1023)
#12     runZoned (dart:async/zone.dart:1501)
#13     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:484)
#14     Driver.start (package:analysis_server/src/server/driver.dart:443)
#15     main (file:///E:/b/build/slave/Windows_Engine/build/src/third_party/dart/pkg/analysis_server/bin/server.dart:12)
#16     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```
```
Error: This socket has been ended by the other party
	at Socket.writeAfterFIN [as write] (net.js:305:12)
	at Analyzer.sendMessage (C:\Users\eee\.vscode\extensions\Dart-Code.dart-code-2.12.1\out\src\services\stdio_service.js:56:28)
	at Analyzer.sendMessage (C:\Users\eee\.vscode\extensions\Dart-Code.dart-code-2.12.1\out\src\analysis\analyzer.js:66:19)
	at Promise (C:\Users\eee\.vscode\extensions\Dart-Code.dart-code-2.12.1\out\src\services\stdio_service.js:51:18)
	at Promise (<anonymous>)
	at Analyzer.sendRequest (C:\Users\eee\.vscode\extensions\Dart-Code.dart-code-2.12.1\out\src\services\stdio_service.js:40:16)
	at Analyzer.analysisUpdateContent (C:\Users\eee\.vscode\extensions\Dart-Code.dart-code-2.12.1\out\src\analysis\analyzer_gen.js:517:21)
	at FileChangeHandler.onDidOpenTextDocument (C:\Users\eee\.vscode\extensions\Dart-Code.dart-code-2.12.1\out\src\analysis\file_change_handler.js:22:23)
	at FileChangeHandler.disposables.push.vs.workspace.onDidOpenTextDocument (C:\Users\eee\.vscode\extensions\Dart-Code.dart-code-2.12.1\out\src\analysis\file_change_handler.js:10:79)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:646:564
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:686:588)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:324
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

**Comment by DanTup** [comment]
@bwilkerson @scheglov Maybe a server bug? Have you seen this before?

**Comment by bwilkerson** [comment]
That's definitely a server bug.

I don't know whether it's still a bug on bleeding edge. The line numbers in the stack traces are very far from where the code is today, so at the very least there have been some changes to the file since the version being run by the user. Whether those changes are related to this bug I don't know.

We need to see whether we can reproduce this behavior on bleeding edge.

**Comment by festelo** [comment]
It works fine with flutter v0.4.3 from dev channel. So I think that we can close the issue.
