### ISSUE TITLE
flutter_tester isn't quitting properly

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#933]
When trying to run tests on Windows I frequently see this:

```
PS M:\Coding\Applications\Dart-Code\test\test_projects\flutter_hello_world> flutter run -t lib\main.dart -d flutter-tester
Launching lib\main.dart on Flutter test device in debug mode...
compiler message: Unhandled exception:
FileSystemException: Cannot open file, path = 'build\app.dill' (OS Error: The requested operation cannot be performed on a file with a user-mapped section open.
, errno = 1224)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:354)
#1      _RootZone.runUnary (dart:async/zone.dart:1381)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:129)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
#4      Future._propagateToListeners (dart:async/future_impl.dart:662)
#5      Future._completeWithValue (dart:async/future_impl.dart:477)
#6      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#9      _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

The file is locked by an existing `flutter_tester.exe` process.

**Comment by DanTup** [comment]
It's unrelated to flutter_tester staying around, I can repro after a clean with no processes running...

**Comment by DanTup** [comment]
Moved the original issue to https://github.com/flutter/flutter/issues/17833, but we may still have a cleanup issue in Dart Code.
