### ISSUE TITLE
when debugging, received an 'Only absolute paths are supported' from the analysis server

### ISSUE THREAD

**Issue by devoncarew** [Dart-Code/Dart-Code#946]
### What I was doing

- debugging an app
- the app itself hit an exception (correctly), which caused a `dart:` library file to open in VS Code
- Dart-Code send the `dart:` url in as the path (`dart:io-patch/socket_patch.dart`) to the analysis server
- see the exception below :)

I think that dart-code here should send the path to the `socket_patch.dart` file on the file system, or - if this file is just a temporary file who's source was downloaded from the VM - should likely not inform the analysis server about the file.

### Request

While responding to request: `analysis.updateContent`

### Versions

- Dart SDK 2.0.0-edge.785f36853ff0e6cd6d605471fb3aa82a1df1ffd4
- Flutter SDK 0.4.6-pre.23
- Visual Studio Code 1.23.1
- Dart Code 2.12.1

### Analyzer Info

The analyzer was launched using the arguments:

```text
/Users/devoncarew/projects/dart-lang/dart-sdk/sdk/xcodebuild/ReleaseX64/dart-sdk/bin/snapshots/analysis_server.dart.snapshot
--client-id=Dart-Code.dart-code
--client-version=2.12.1
```

### Exception

Invalid argument(s): Only absolute paths are supported: dart:io-patch/socket_patch.dart

```text
#0      AnalysisDriver._throwIfNotAbsolutePath (package:analyzer/src/dart/analysis/driver.dart:1726)
#1      AnalysisDriver.changeFile (package:analyzer/src/dart/analysis/driver.dart:576)
#2      AnalysisServer.updateContent.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1029)
#3      _HashMapValueIterable.forEach.<anonymous closure> (dart:collection-patch/dart:collection/collection_patch.dart:469)
#4      _HashMap.forEach (dart:collection-patch/dart:collection/collection_patch.dart:165)
#5      _HashMapValueIterable.forEach (dart:collection-patch/dart:collection/collection_patch.dart:468)
#6      AnalysisServer.updateContent.<anonymous closure> (package:analysis_server/src/analysis_server.dart:1028)
#7      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:363)
#8      AnalysisServer.updateContent (package:analysis_server/src/analysis_server.dart:998)
#9      AnalysisDomainHandler.updateContent (package:analysis_server/src/domain_analysis.dart:399)
#10     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:273)
#11     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:722)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#13     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:718)
#14     _rootRun (dart:async/zone.dart:1126)
#15     _CustomZone.run (dart:async/zone.dart:1023)
#16     runZoned (dart:async/zone.dart:1490)
#17     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:717)
#18     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#19     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:210)
#20     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#21     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#22     _rootRunUnary (dart:async/zone.dart:1134)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#27     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#28     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#29     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#30     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154)
#31     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129)
#32     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#33     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#34     _rootRunUnary (dart:async/zone.dart:1134)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031)
#36     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#37     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#38     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#39     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#40     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#41     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#42     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#43     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#44     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#45     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#46     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#47     _rootRunUnary (dart:async/zone.dart:1134)
#48     _CustomZone.runUnary (dart:async/zone.dart:1031)
#49     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#53     _StreamController._add (dart:async/stream_controller.dart:639)
#54     _StreamController.add (dart:async/stream_controller.dart:585)
#55     _Socket._onData (dart:io-patch/socket_patch.dart:1672)
#56     _rootRunUnary (dart:async/zone.dart:1138)
#57     _CustomZone.runUnary (dart:async/zone.dart:1031)
#58     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
#59     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#60     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#61     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#62     _StreamController._add (dart:async/stream_controller.dart:639)
#63     _StreamController.add (dart:async/stream_controller.dart:585)
#64     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1245)
#65     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:797)
#66     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#67     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#68     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:113)
#69     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:166)
```

Diagnostics requested after the error occurred are:

```js
[
    {
        "name": "/Users/devoncarew/projects/devoncarew/mserve.dart",
        "explicitFileCount": 7,
        "implicitFileCount": 443,
        "workItemQueueLength": 0,
        "cacheEntryExceptions": []
    }
]
```

**Comment by DanTup** [comment]
This is fixed this via #874. If you use the latest beta ([here](https://github.com/Dart-Code/Dart-Code/releases/tag/v2.13.0-beta.4)) it shouldn't occur. There was a (IMO huge) breaking change so that `TestDocument.isUntitled` no longer returns `true` for non-file uris.
